### ISSUE TITLE
Filter bar on table bad button alignments

### ISSUE THREAD

**Issue by NoahNxT** [Sequel-Ace/Sequel-Ace#1609] opened 2022-11-10 11:37 UTC
**Version & Build**
- Version 4.0.1
- Build 20039

**Source**
- Homebrew

**macOS version**
- 13.0 (22A380)

**Processor Type**
- 2,3 GHz 8-Core Intel Core i9

**MySQL Version:**
- MySQL 5.7

**Description**
When I'd like to add some filters in my tables the filter nav bar button like `+` and `-` are aligned over the filter button.
![image](https://user-images.githubusercontent.com/58152024/201080887-6fb334cd-abde-4664-a0ec-c2112593c3c1.png)

**Steps To Reproduce**
1. Open table
2. cmd + F

**Expected Behaviour**
That the buttons should be aligned next to each other so that they are usable.

**Comment by Kaspik** [comment] 2022-11-10 11:42
Duplicate of https://github.com/Sequel-Ace/Sequel-Ace/issues/1596, fixed in RC and Beta.

**Closed by Kaspik** 2022-11-10 11:42 UTC
