### ISSUE TITLE
Cannot create foreign key when skip-show-database is in .cnf

### ISSUE THREAD

**Issue by cappadaan** [Sequel-Ace/Sequel-Ace#875] opened 2021-02-15 09:32 UTC
V3.2.0

Cannot create foreign key, references dropdowns are both empty, when they do exist.

<img width="329" alt="Screenshot 2021-02-15 at 10 31 22" src="https://user-images.githubusercontent.com/25279400/107928815-16d95580-6f79-11eb-8935-58e4da69eaf8.png">

**Comment by cappadaan** [comment] 2021-02-15 18:03
Just checked, this feature works in 3.1.1

**Comment by Jason-Morcos** [comment] 2021-02-16 05:34
> Just checked, this feature works in 3.1.1

Can you please include all the standard debug into that's in the template? macOS version, download source, mysql version...

Any errors/crashes in the console?

**Comment by Jason-Morcos** [comment] 2021-02-16 05:35
@gduh Likely related to https://github.com/Sequel-Ace/Sequel-Ace/pull/808, I assume

**Comment by gduh** [comment] 2021-02-16 07:55
@Jason-Morcos it's possible. To fill in the list of databases, I use a common method. 
Well, I need more information : 
- messages from the console
- version of mysql/mariadb used
- does this always occur ? If not, step to reproduce and if possible the tables structure.

**Comment by cappadaan** [comment] 2021-02-16 08:10
"messages from the console"

Can you explain how to?

**Comment by gduh** [comment] 2021-02-16 08:42
In the toolbar you have the Console Icon on the right side : 
![image](https://user-images.githubusercontent.com/15440947/108038387-0f7a8080-703b-11eb-9b8b-6c479e3cb521.png)
There is some information that could be interesting !

**Comment by cappadaan** [comment] 2021-02-16 08:56
- Mariadb 10.5.8
- there is nothing in the console
- It always happens, I cannot create any FK relations on any tables, both dropdowns are always empty / cannot be selected

**Comment by Jason-Morcos** [comment] 2021-02-17 02:20
I wonder if it's something about mysql 5.5.5/MariaDB 10.5.8. Working fine for me on MySQL 5.7. Anyone have an instance to try to reproduce this against, @Sequel-Ace/all?

**Comment by gduh** [comment] 2021-02-17 08:02
On a MBP Intel, I upgraded  from 10.4.6 to 5.5.5/10.5.8 --> OK
I check on mysql  Ver 15.1 Distrib 5.5.68-MariaDB Linux --> OK
I check on mysql Ver 15.1 Distrib 10.4.17-MariaDB Linux --> OK

**Comment by cappadaan** [comment] 2021-02-17 08:07
Maybe its related but when i am connected to the database, the dropdown in the menu with label "select database" is also empty

<img width="214" alt="Screenshot 2021-02-17 at 09 07 41" src="https://user-images.githubusercontent.com/25279400/108174339-9e50d100-70ff-11eb-968b-9c43f0db3630.png">

**Comment by gduh** [comment] 2021-02-17 13:13
If you cannot choose a database, I don't understand how you can have the ability to create a foreign key !

It seems to be connected to the mariaDB, but unfortunately it seems unable to list the databases.

**Comment by cappadaan** [comment] 2021-02-17 13:35
I think I know the cause:

skip-show-database is in my my.cnf

Can you add a check, or at least show the current database?

**Comment by gduh** [comment] 2021-02-17 13:59
Ok, so, the documentation says : 

_This prevents people from using the SHOW DATABASES statement if they do not have the SHOW DATABASES privilege. This can improve security if you have concerns about users being able to see databases belonging to other users. Its effect depends on the SHOW DATABASES privilege: If the variable value is ON, the SHOW DATABASES statement is permitted only to users who have the SHOW DATABASES privilege, and the statement displays all database names. If the value is OFF, SHOW DATABASES is permitted to all users, but displays the names of only those databases for which the user has the SHOW DATABASES or other privilege._

If you are using a user with no privilege, it will not be possible to select any databases because it will not be possible to guess its name.

@Jason-Morcos  Is there any point in checking the value of the skip-show-database variable at this time ?

**Comment by cappadaan** [comment] 2021-02-17 14:02
But if there are no database to select, why no just show at least the tables from the current database (just like the previous version worked)

This will solve it.

**Comment by Jason-Morcos** [comment] 2021-02-19 03:12
> But if there are no database to select, why no just show at least the tables from the current database (just like the previous version worked)
> 
> This will solve it.

@gduh Would you be comfortable making this change? Basically if we either can't get the list of DBs or the DB list is empty, fallback on the previous behavior (switch to the current db tables variant and just disable the db selector). I agree with @cappadaan's suggestion here.

**Comment by gduh** [comment] 2021-02-19 07:52
@Jason-Morcos I'm ok for the change.

I think there are several points to take into account : 
- Display a message box to inform the user (?)
- Disable the db selector
- Change the behavior when creating a foreign key if the db dropdown is empty and fill in the tables dropdown with the defaults
- And maybe other things... like disabling most db menu items
Tell me if you agree with all of these points and if you see other points ?

I will be off the next 5/6 days, I will make the change afterwards.

**Comment by Jason-Morcos** [comment] 2021-02-20 06:16
> @Jason-Morcos I'm ok for the change.
> 
> 
> 
> I think there are several points to take into account : 
> 
> - Display a message box to inform the user (?)
> 

Nah, maybe at the most populate the db selector with a string "couldn't list DBs" or something 

> - Disable the db selector
> 

Yes, I agree

> - Change the behavior when creating a foreign key if the db dropdown is empty and fill in the tables dropdown with the defaults

Yes, I agree


> 
> - And maybe other things... like disabling most db menu items

I wouldn't worry about this for a bug fix PR, but it's definitely something to think about.

> 
> Tell me if you agree with all of these points and if you see other points ?
> 
> 
> 
> I will be off the next 5/6 days, I will make the change afterwards.

Awesome! Once you have a chance, we'll get the PR merged and out as soon as possible

**Comment by gduh** [comment] 2021-03-02 20:42
@Jason-Morcos  Just to keep you inform, I started the change today.

**Comment by gduh** [comment] 2021-03-04 20:51
@Jason-Morcos
I added a check at each new connection, it's ok for that.
But I'm not able to list the tables of the databases selected by default since the function `select database()` return null. This is because no database was specified when connecting. In fact, if we want a default database selected, the only way is to specify the database on the connection panel, if not, it will not be possible to list the tables.
In any case, the databases are always available through queries if the user knows them. Depending on privileges of course.

**Comment by Jason-Morcos** [comment] 2021-03-05 05:17
> @Jason-Morcos
> I added a check at each new connection, it's ok for that.
> But I'm not able to list the tables of the databases selected by default since the function `select database()` return null. This is because no database was specified when connecting. In fact, if we want a default database selected, the only way is to specify the database on the connection panel, if not, it will not be possible to list the tables.
> In any case, the databases are always available through queries if the user knows them. Depending on privileges of course.

If I follow I think that makes sense. I think if select database() returns null we should do what @cappadaan said and just disable the DB selector in the relation setup and just fallback on the behavior like it used to be (no database specified in list tables)

**Closed** 2021-03-07 18:34 UTC
Labels: Bug
