### ISSUE TITLE
The problem of code completion Still exists

### ISSUE THREAD

**Issue by bpzhang** [Sequel-Ace/Sequel-Ace#670] opened 2020-12-22 06:16 UTC
Sequel Ace Version: 3.0.1 3008
macOS Version: 10.15.7
Processor Type (Intel/Apple): Intel
MySQL Version: 5.7.12

![image](https://user-images.githubusercontent.com/1734396/102855779-36b03980-4460-11eb-80f7-4a1fe68bfd64.png)

**Comment by Jason-Morcos** [comment] 2020-12-22 06:21
I don't have the slightest idea what this issue is about from the title and content. Please follow the template and for a new issue and provide details such as expected and actual results, and steps to reproduce. If an issue is related to a previous issue, please link that previous issue.

Closing issue, but would be very happy to take a look at a similar issue that follows the template and includes the necessary info to understand what the problem is.

**Closed by Jason-Morcos** 2020-12-22 06:21 UTC
