### ISSUE TITLE
Ability to left align the icons in the header

### ISSUE THREAD

**Issue by webtoolbox** [Sequel-Ace/Sequel-Ace#578] opened 2020-11-30 18:07 UTC
When opening Sequel Ace in full screen mode, the icons are all the way to the right and the tables are all the way to the left. It makes it tedious when selecting various different tables and then wanting to switch the view (query editor, browse, etc). It would be more user-friendly if the icons were left-aligned or at least if that option were given.

**Comment by Kaspik** [comment] 2020-11-30 18:18
Duplicate of https://github.com/Sequel-Ace/Sequel-Ace/issues/562, https://github.com/Sequel-Ace/Sequel-Ace/issues/544 and https://github.com/Sequel-Ace/Sequel-Ace/issues/534

**Closed by Kaspik** 2020-11-30 18:18 UTC
