### ISSUE TITLE
Able to open right click menu while editing value resulting in crash

### ISSUE THREAD

**Issue by daraeman** [Sequel-Ace/Sequel-Ace#1446] opened 2022-04-12 11:10 UTC
- Sequel Ace Version (including build number): 3.5.2 (20033)
- Sequel Ace Source (App Store/GitHub/Homebrew): Homebrew
- macOS Version: 11.6.1
- Processor Type (Intel/Apple): Intel
- MySQL Version: Multiple
- macOS Localization: US

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

Yes

**Description**
It is possible to delete a row while the value edit dialog is open, causing the app to crash when the dialog is closed.

**Steps To Reproduce**
1. Double click on a value to edit in the content pane.
2. Once the value edit dialog is open, right click on the row (even though the rows are gray it is still possible)
3. Delete the row
4. Click Cancel or Ok on the edit dialog
5. The app will now crash

**Expected Behaviour**

It shouldn't be possible to right click on the rows while the value edit dialog is open (and also the app shouldn't crash if the row goes away during editing)

**Related Issues**

**Additional Context**

<img width="844" alt="context menu while dialog open" src="https://user-images.githubusercontent.com/933763/162946726-a8ac2bb1-2bc7-421d-90ab-2ddfa3cd4b3f.png">
[crash_log.txt](https://github.com/Sequel-Ace/Sequel-Ace/files/8472298/crash_log.txt)

**Comment by luis-** [comment] 2022-04-13 05:48
Did a super quick test and was able to reproduce and fix with the following:

in `Source/Controllers/MainViewControllers/TableContent/SPTableContent.m`
```objc
- (BOOL)tableView:(NSTableView *)tableView shouldSelectRow:(NSInteger)rowIndex
{
    if (fieldEditor) return NO; // added this line
    return tableView == tableContentView ? tableRowsSelectable : YES;
}
```

My working copy is currently a mess due to some enhancements I'm in the middle of so if anybody wants to tackle testing
and creating the pull-request for this then please do so -- otherwise, I can do so in the next couple days.

**Comment by Kaspik** [comment] 2022-08-07 17:28
Fixed in https://github.com/Sequel-Ace/Sequel-Ace/pull/1525, thanks for the tip!

**Closed by Kaspik** 2022-08-07 17:28 UTC
Labels: Bug
