### ISSUE TITLE
Alert each time I export a database as .sql to Desktop

### ISSUE THREAD

**Issue by scott-slash** [Sequel-Ace/Sequel-Ace#870] opened 2021-02-12 17:17 UTC
- Sequel Ace Version (including build number): 3.2.0 Build 3019
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 11.2.1
- Processor Type (Intel/Apple): Intel i7
- MySQL Version: varies depending on hosting
- macOS Localization: US English

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Every version I have tried from the Mac App Store has this issue. I'm guessing it's sandboxing-related.

**Description**
When I export any database as a .sql or .csv file, I get an error that Sequel Pro
**Steps To Reproduce**
1. File -> Export...
2. The save dialog defaults to my Desktop, which is where I want to save my export. When I click the Export button in the dialog, I get an alert with the message "The target export folder is not writable. Please select a new location and try again."
3. If I repeat the process and select the Desktop folder in the save dialog, then click "Export", it works fine. I just have to explicitly select my Desktop folder every time.

**Expected Behaviour**
When doing steps 1 and 2 above, I should not get any error messages regarding my Desktop being writable.

**Related Issues**
None found

**Additional Context**
Screenshots attached
![save dialog](https://user-images.githubusercontent.com/54366210/107799965-c9b07600-6d23-11eb-9866-c111e5b71c80.png)
![not writeable error](https://user-images.githubusercontent.com/54366210/107799968-ca490c80-6d23-11eb-8644-73ee8fcbbfb1.png)
![about](https://user-images.githubusercontent.com/54366210/107799969-ca490c80-6d23-11eb-9244-3234cf3a1ddc.png)

**Comment by jamesstout** [comment] 2021-02-12 17:39
Can you show us your _Preferences->Files_ screen please?

Also, if possible, your prefs `.plist`:

`/Users/<user>/Library/Containers/com.sequel-ace.sequel-ace/Data/Library/Preferences/com.sequel-ace.sequel-ace.plist`

In particular the values for:

```
SPSecureBookmarksDoNotShow
SPSecureBookmarksHaveBeenMigrated
SPStaleSecureBookmarks
SPSecureBookmarks
SPSecureBookmarksOldFormat
```
Thanks

**Comment by scott-slash** [comment] 2021-02-12 17:44
Thanks for the quick reply! Here are the requested attachments.
[com.sequel-ace.sequel-ace copy.plist.zip](https://github.com/Sequel-Ace/Sequel-Ace/files/5973499/com.sequel-ace.sequel-ace.copy.plist.zip)
![Screen Shot 2021-02-12 at 11 40 33 AM](https://user-images.githubusercontent.com/54366210/107803031-b2738780-6d27-11eb-9001-7c1c340672c4.png)

**Comment by jamesstout** [comment] 2021-02-12 20:19
OK, I see the issue. Will take a look tomorrow.

**Comment by jamesstout** [comment] 2021-02-13 00:26
PR submitted #871

**Comment by stefanoio** [comment] 2021-02-20 09:27
I just checked on v3.2.1 from MAS which should include https://github.com/Sequel-Ace/Sequel-Ace/pull/871 on M1 Big Sur 11.2.1 (20D74) but the issue is not fixed for me. Tell me if I can provide any more information. Thank you!

[com.sequel-ace.sequel-ace.plist.zip](https://github.com/Sequel-Ace/Sequel-Ace/files/6014506/com.sequel-ace.sequel-ace.plist.zip)

<img width="698" alt="Schermata 2021-02-20 alle 10 22 25" src="https://user-images.githubusercontent.com/1315456/108590868-06085580-7366-11eb-8650-109bad78f708.png">
<img width="712" alt="Schermata 2021-02-20 alle 10 22 15" src="https://user-images.githubusercontent.com/1315456/108590878-14567180-7366-11eb-8929-a7ec176f2788.png">
<img width="812" alt="Schermata 2021-02-20 alle 10 20 23" src="https://user-images.githubusercontent.com/1315456/108590881-1a4c5280-7366-11eb-9d14-14f36a6b5545.png">
<img width="773" alt="Schermata 2021-02-20 alle 10 21 30" src="https://user-images.githubusercontent.com/1315456/108590887-1fa99d00-7366-11eb-9158-ad373876e653.png">
<img width="372" alt="Schermata 2021-02-20 alle 10 21 48" src="https://user-images.githubusercontent.com/1315456/108590888-233d2400-7366-11eb-98de-0f54dea45bc3.png">

**Comment by Jason-Morcos** [comment] 2021-02-20 19:12
> I just checked on v3.2.1 from MAS which should include #871 on M1 Big Sur 11.2.1 (20D74) but the issue is not fixed for me. Tell me if I can provide any more information. Thank you!

@jamesstout Looks like #871 didn't quite fix the issue. Any ideas?

**Comment by scott-slash** [comment] 2021-02-20 23:48
I had to revoke all the directories from Sequel Ace, then add them again, even after the bug fix. Started working fine for me after that

**Comment by Jason-Morcos** [comment] 2021-02-20 23:59
> I had to revoke all the directories from Sequel Ace, then add them again, even after the bug fix. Started working fine for me after that

Ahhh good info to know. Thanks, @scott-slash!
@stefanoio Can you try this and let us know if it fixes the issue?

**Comment by stefanoio** [comment] 2021-02-21 07:43
> > I had to revoke all the directories from Sequel Ace, then add them again, even after the bug fix. Started working fine for me after that
> 
> Ahhh good info to know. Thanks, @scott-slash!
> @stefanoio Can you try this and let us know if it fixes the issue?

Unfortunately for me this works only for the current session: if I close the app and reopen it then the issue reappears. BTW this was the same behaviour I noticed before https://github.com/Sequel-Ace/Sequel-Ace/pull/871: revoke+readd already did fix the problem for the ongoing session.
@scott-slash can you confirm if the fix on your side is working even after closing the app?
Thank all of you guys!

**Comment by jamesstout** [comment] 2021-02-22 05:22
I had another go: PR #897

**Closed** 2021-02-22 07:07 UTC
Labels: Bug, Fixed & Pending Release
