### ISSUE TITLE
High CPU usage in background in the App from the App Store

### ISSUE THREAD

**Issue by aglukharev3c** [Sequel-Ace/Sequel-Ace#1647] opened 2022-12-08 12:38 UTC
Today I installed the app from the App Store and I noticed an extremely high CPU usage. My M1 Pro was so hot!!! I tried to reboot a computer and it helped a bit but anyway with 3 opened tabs without any queries usage is quite a high - more than 100%.
<img width="735" alt="cpu_usage" src="https://user-images.githubusercontent.com/110167375/206447479-85902dbf-e84e-488a-b4c6-fa096b524821.png">

Then I removed the app and installed it via Brew. And that solved the issue - usage 0.5%. The app works perfectly. I guess you have to check the app in the App Store.

Thank you for the great product.

**Comment by Kaspik** [comment] 2022-12-08 12:40
Duplicate of https://github.com/Sequel-Ace/Sequel-Ace/issues/1625

**Closed by Kaspik** 2022-12-08 12:40 UTC
