### ISSUE TITLE
PostgreSQL Support

### ISSUE THREAD

**Issue by lowercase00** [Sequel-Ace/Sequel-Ace#143] opened 2020-07-01 03:29 UTC
Being a long time user of Sequel Pro, I'm pretty happy this is going on, thanks a lot for your work.
One things that always lacked in Sequel Pro was PostgreSQL support.
It would be great to see this added to the roadmap.
Thanks!

**Comment by smpita** [comment] 2020-08-29 20:33
+1

**Comment by boxed** [comment] 2020-10-21 08:57
The homepage of sequel pro does mention it a bit vaguely.. did any of that work carry over?

**Comment by Jason-Morcos** [comment] 2020-10-21 15:39
> The homepage of sequel pro does mention it a bit vaguely.. did any of that work carry over?

We're a direct fork of Sequel Pro so anything in Sequel Pro is most likely in Ace. Go ahead and give it a try.

As to new support for additional DBs - definitely a good idea, but we have a lot of work to do modernizing the core of the app itself before we add support for additional databases. We'd absolutely review a PR that added/enhanced PostgreSQL support!

**Comment by samuelbradshaw** [comment] 2020-10-29 01:20
For what it's worth, I wasn't able to connect to a PostgreSQL database in Sequel Ace, so I think work to support PostgreSQL was probably started in Sequel Pro but never completed.

**Comment by Kaspik** [comment] 2020-11-19 16:45
That's correct. PostgreSQL framework was part of Sequel Ace, but never finished, and never worked. It was also removed from codebase couple of weeks ago as it would have to be rewritten anyways.

We are not planning to bring any other database type for now, as we need to stabilize Sequel Ace with MySQL, so I'łl close this also as a duplicate of https://github.com/Sequel-Ace/Sequel-Ace/issues/61.

**Closed by Kaspik** 2020-11-19 16:45 UTC
Labels: Enhancement, PR Welcome

**Comment by Sylk** [comment] 2021-01-26 16:29
Is this potentially in the pipeline at any point though?

**Comment by mfehr94** [comment] 2021-01-26 16:36
@Sylk not in the near future.

**Comment by Kaspik** [comment] 2021-01-26 16:38
It doesn't make sense to introduce another complexity to app this unstable currently. We need to catch up with major infra changes and improvements - then we can think about this, sorry.

**Comment by Sylk** [comment] 2021-01-26 17:43
> It doesn't make sense to introduce another complexity to app this unstable currently. We need to catch up with major infra changes and improvements - then we can think about this, sorry.

So you consider SQL ace to be unstable? Huh. Never considered that. Appreciate the update though from both of you guys. Cheers.

> @Sylk not in the near future.

Thank you for the response.

**Comment by Kaspik** [comment] 2021-01-26 17:46
Unstable in developer point of view meaning hard to introduce new features and app infra being outdated - sequel-pro was abandoned for years - it will take time for us to catch up and be able to build new stuff quickly... and no one wants to spend months on building PostgreSQL . :)

Wouldn't say unstable for users - of course there are bugs and crashes, but that's why we are focused on these and not on new stuff.

**Comment by tilhoft** [comment] 2021-03-15 11:57
:(

**Comment by Gigamick** [comment] 2022-02-03 21:00
+1 for PG

**Comment by Flcwl** [comment] 2023-02-16 14:21
Why not？

**Comment by iamalisajid** [comment] 2023-08-31 09:50
+1

**Comment by qousarbashir** [comment] 2023-09-19 17:52
+1 for PG

**Comment by fuzzy76** [comment] 2023-09-21 07:08
Please don't use +1, use 👍 on the issue to vote.

**Comment by loeffel-io** [comment] 2023-10-24 08:30
+1

**Comment by meetalodariya** [comment] 2024-02-26 07:52
+1

**Comment by jwidavid** [comment] 2024-05-14 05:40
+1

**Comment by nurlandev** [comment] 2024-05-28 05:27
+1

**Comment by nawazzzz** [comment] 2024-08-17 09:45
I tried, it isn't working :(

**Comment by brandoneubank** [comment] 2024-10-09 03:18
+1 for postgres support.
