### ISSUE TITLE
Importing CSV

### ISSUE THREAD

**Issue by serbanc66** [Sequel-Ace/Sequel-Ace#436] opened 2020-10-26 14:39 UTC
- Sequel Ace Version: 2.2.2 build 2104
- macOS Version: 10.13.6
- MySQL Version: 5.6.17

**Description**
When import data from csv file with the option "first line contains field names" flagged, Sequel-Ace doesn't show the name of the field in parsing window, but the first record to import. In Sequel Pro with this option flagged the name field was showed and it was possible associate the columns to be import with field names.

In attached picts the same file csv to be import in Sequel Pro and in Ace Sequel.
In the second is not possible combine the name of columns included in csv file.

![Schermata 2020-10-26 alle 15 35 11](https://user-images.githubusercontent.com/50914241/97186187-446b7a80-17a1-11eb-98ca-e1bff89aebee.png)

![Schermata 2020-10-26 alle 15 36 09](https://user-images.githubusercontent.com/50914241/97186218-4f260f80-17a1-11eb-92be-fabc2ca07322.png)

**Comment by Jason-Morcos** [comment] 2020-10-26 21:55
Not sure why this is broken. What version of Sequel Pro are you using in that screenshot? Is that the release version or the nightly build of Sequel Pro, and what does it look like in the other Sequel Pro version? I don't think we've messed with CSV import stuff, at least not much, yet.

**Comment by Kaspik** [comment] 2020-10-26 22:09
Happened to me once, just close (cancel) the import, and try it again (don't remember if I restarted the app too). Wanted to check what's going on, but haven't happened since then, so de-prioritized.

**Comment by jamesstout** [comment] 2020-10-27 07:47
Switch "First line contains field names" off - then you get the first line.

Seem like some logic has got switched somewhere - trying to track it down.

**Comment by serbanc66** [comment] 2020-10-27 07:50
I used a released version  not a nigthly build. Below the release.
Thanks

Sergio



Il giorno 26 ott 2020, alle ore 22:56, Jason Morcos <notifications@github.com> ha scritto:


Not sure why this is broken. What version of Sequel Pro are you using in that screenshot? Is that the release version or the nightly build of Sequel Pro, and what does it look like in the other Sequel Pro version? I don't think we've messed with CSV import stuff, at least not much, yet.

**Comment by Kaspik** [comment] 2020-10-27 19:47
So this works exactly as SequelPro in nightly builds, but differently than in latest stable SequelPro that is suuuuper old.

It looks like if you check the checkbox, it removes the first row completely, but you can uncheck it to see if columns are matching, and then check it again.

Not sure why this was changed, but it was a long long time ago.
Not sure what we want to do here. :)

**Comment by Kaspik** [comment] 2020-10-27 20:00
Got it: https://github.com/sequelpro/sequelpro/commit/c196132146dab618005bd88057dd61764f855808

This works as intended. If you want to preview the columns match, uncheck it, then check it again and continue with the import.

It works like that since January 2016, right after last release of Sequel Pro.

Closing as this doesn't seem like a bug. :)

**Closed by Kaspik** 2020-10-27 20:00 UTC
Labels: PR Welcome, bug

**Comment by webmdt** [comment] 2021-12-17 04:09
Please re-open this issue. This same issue has occured on every version of Sequel Ace I've used. 

Currently running:
Version 3.4.2
Build 20016

**Comment by Jason-Morcos** [comment] 2021-12-17 05:09
Did you read @Kaspik's last comment on this thread? Do you disagree with his response in some way?

**Comment by kyeasting** [comment] 2024-03-14 22:04
I am also experiencing this bug in Sequel Ace
Version 4.0.13
Build 20062

**Comment by lindensmith** [comment] 2024-12-18 06:48
Still a bug in Sequel Ace 
Version 4.1.6 
Build 20078
