### ISSUE TITLE
Warning should be shown when Keychain cannot be used due to Cleartext plugin being enabled

### ISSUE THREAD

**Issue by wrmoon** [Sequel-Ace/Sequel-Ace#285] opened 2020-08-07 15:22 UTC
Passwords are not getting saved at all. No entries in keychain for Sequel Ace.

Sequel Ace version 2.1.5
MacOs 10.15.5 (19F101)
MacBook Pro (15-inch, 2019) 

Would appreciate any suggestions to help debug this

**Comment by Jason-Morcos** [comment] 2020-08-08 06:31
Can you provide more detail as to what the issue is as you are experiencing it? When do you expect a password to be saved and it's not being saved?

**Comment by wrmoon** [comment] 2020-08-12 13:16
Steps to recreate:

1. File | New Connection Tab
1. Click on + button to create a new connection
1. Fill out Host, Username, Password
1. Click on "Save changes" button
1. Notice that the connection has been stored as a new favorite in your list
1. Also notice that the password field is now empty. If you try to connect to this database, it will fail if it requires a password. (I get an Access denied popup)

I noticed that there are NO entries in my keychain for passwords for Sequel Ace (though there were for Sequel Pro)

**Comment by Jason-Morcos** [comment] 2020-08-13 15:50
This is a very strange issue. I definitely cannot reproduce. 
Perhaps this is not a Sequel Ace issue per say and more a Mac-specific issue? Have you tried repairing the keychain (or any of these other tips)? https://discussions.apple.com/thread/2716932

**Comment by stychos** [comment] 2020-08-13 21:50
Hm.. can this be relevant? https://github.com/Sequel-Ace/Sequel-Ace/blob/7a71505561648c752f5c95c2d061cace480a83cf/Source/SPKeychain.m#L47

**Comment by stychos** [comment] 2020-08-13 22:21
Yes, looks like the possible source of trouble. I tried with this env var set and lost Keychain access:
```zsh
 % LIBMYSQL_ENABLE_CLEARTEXT_PLUGIN=1 /Applications/Sequel\ Ace.app/Contents/MacOS/Sequel\ Ace
2020-08-14 01:19:31.277 Sequel Ace[44057:10824358] Failed to set (systemColorOfName) user defined inspected property on (SPButtonBar): [<SPButtonBar 0x7f85b5e35070> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key systemColorOfName.
2020-08-14 01:19:31.497 Sequel Ace[44057:10824358] LIBMYSQL_ENABLE_CLEARTEXT_PLUGIN is set. Disabling keychain access. See Issue #2437
```
@wrmoon what your output of the console command `echo $LIBMYSQL_ENABLE_CLEARTEXT_PLUGIN`? Or try to launch via terminal as in my example, please.

**Comment by wrmoon** [comment] 2020-08-16 15:16
@stychos That's the culprit alright!

When I launch SA from a terminal window, passwords are saved correctly. When I launch from spotlight search (cmd-space) it doesn't work. 

I opened SA from the spotlight search, and checked the environment variables (`ps eww <pid>`). Sure enough, I see ` LIBMYSQL_ENABLE_CLEARTEXT_PLUGIN=yes`

**Comment by stychos** [comment] 2020-08-16 15:20
I think it maybe hidden in your .bash_profile, .zshrc or in mysqld launcher. Try to verify that places.

**Comment by wrmoon** [comment] 2020-08-16 15:26
But now I wonder _why_ keychain access is disabled when the cleartext plugin is enabled. Couldn't the password be intercepted even if the password isn't stored in the keychain?

**Comment by stychos** [comment] 2020-08-16 15:32
Sorry, I can't answer you this question. You can try to read related issues in Sequel Pro tracker to have more vision: https://github.com/sequelpro/sequelpro/issues/2437 and https://github.com/sequelpro/sequelpro/issues/2247

**Comment by Jason-Morcos** [comment] 2020-08-16 17:40
At the very least, it might be good if we popped up a one-time alert indicating to the user that keychain cannot be used because MySQL clear text is enabled? It is confusing that the end user can't tell what's going on!

**Comment by stychos** [comment] 2020-08-16 17:42
> At the very least, it might be good if we popped up a one-time alert indicating to the user that keychain cannot be used because MySQL clear text is enabled? It is confusing that the end user can't tell what's going on!

Thought about that too. Maybe we need to change the issue title and/or description appropriately and keep this open for a while?

**Comment by wrmoon** [comment] 2020-08-17 14:11
In case someone has the same issue and reads this thread, I fixed my problem by moving `~/Library/LaunchAgents\mysql.plist` elsewhere, and rebooting. Not sure what program put that there, but it looks like I didn't need it anyway.

**Comment by Kaspik** [comment] 2021-01-08 18:19
I'm gonna close this for now, as we haven't seen any other issues really and it's solved afaik. :)

**Closed by Kaspik** 2021-01-08 18:19 UTC
Labels: Enhancement, PR Welcome
