### ISSUE TITLE
Query History

### ISSUE THREAD

**Issue by danieleratti** [Sequel-Ace/Sequel-Ace#778] opened 2021-01-12 08:42 UTC
Both in version 3.1.0 build 3013 (AppStore) and in the previous one (I've just updated), I see the Query History containing always the same query repeated many times. I think is the first query you run after the last history cleaning.

<img width="269" alt="Schermata 2021-01-12 alle 09 35 48" src="https://user-images.githubusercontent.com/1781218/104289604-9fb42b80-54b9-11eb-930e-c5ae212c7086.png">

It seems systematically. Steps to reproduce:
1) Open SequelAce, go in the Query section, clean the query history and run something like "SELECT * FROM XXX WHERE YYY" and other different queries
2) Close and reopen SequelAce
3) In the Query History, you'll find a list of many repeated items, which are the first query you run (sometimes it's truncated)

**Comment by jamesstout** [comment] 2021-01-12 10:11
@danieleratti  "history cleaning" = "Clear Global History" ?

**Comment by jamesstout** [comment] 2021-01-12 10:25
Could you possibly please run this from a terminal?

`/usr/libexec/PlistBuddy -c 'Print SPMigratedQueriesFromPrefs' "/Users/$(whoami)/Library/Containers/com.sequel-ace.sequel-ace/Data/Library/Preferences/com.sequel-ace.sequel-ace.plist"`

Thanks

**Comment by jamesstout** [comment] 2021-01-12 11:39
Actually, don't worry. It's caused by this code I added:

https://github.com/Sequel-Ace/Sequel-Ace/commit/dcc488b8bd27ee171d5103c63d40c60a247122d1#diff-f7c77a01ff6a4ae160e9a454898d9219c948bf1e602a254fe058489449d026aeR4127-R4134

I need to parse and remove dupes.

**Comment by jamesstout** [comment] 2021-01-12 15:47
@danieleratti How's this?

https://user-images.githubusercontent.com/1576190/104337420-708cd100-5530-11eb-80be-4a3ad84aac75.mp4

**Comment by danieleratti** [comment] 2021-01-12 16:59
> @danieleratti "history cleaning" = "Clear Global History" ?
Yes


> Could you possibly please run this from a terminal?
> 
> `/usr/libexec/PlistBuddy -c 'Print SPMigratedQueriesFromPrefs' "/Users/$(whoami)/Library/Containers/com.sequel-ace.sequel-ace/Data/Library/Preferences/com.sequel-ace.sequel-ace.plist"`
> 
> Thanks

I've run it, but still the behavior is wrong.


> @danieleratti How's this?
> 
>  hist.mp4

The feature of saving the last unexecuted query is very cook!


Here is the behavior I'm experiencing:

https://user-images.githubusercontent.com/1781218/104346470-c1d09c80-54ff-11eb-86c9-b4d7d047a6ff.mov

**Comment by jamesstout** [comment] 2021-01-13 10:12
> > Could you possibly please run this from a terminal?
> > `/usr/libexec/PlistBuddy -c 'Print SPMigratedQueriesFromPrefs' "/Users/$(whoami)/Library/Containers/com.sequel-ace.sequel-ace/Data/Library/Preferences/com.sequel-ace.sequel-ace.plist"`
> > Thanks
> 
> I've run it, but still the behavior is wrong.
 
I just needed the output, does it return `true`?

This is a weird one then. I can't reproduce.

Could you please give me the output of:

`which sqlite3`

`"$(which sqlite3)" --version`

Maybe (if you have brew)

`/usr/local/opt/sqlite/bin/sqlite3 --version`

Also, if you have a sqlite editor? 

If so could you check the data in: `/Users/$(whoami)/Library/Containers/com.sequel-ace.sequel-ace/Data/Library/Application Support/Sequel Ace/Data/queryHistory.db`

If not would you be able to post the db here? Just with those three queries?

Thanks
James

**Comment by jamesstout** [comment] 2021-01-13 10:18
Also, macOS version please.

**Comment by jamesstout** [comment] 2021-01-13 11:17
Hmmm: https://www.sqlite.org/lang_vacuum.html

> The VACUUM command may change the ROWIDs of entries in any tables that do not have an explicit INTEGER PRIMARY KEY.

We don't have an explicit integer primary key, we're using the actual query string. And, just before the app terminates, we call `vacuum`. Could be related.

@danieleratti Can I ask you to open two tabs, perform your SQL per the video in one tab, then close it, then, without closing the app, reopen it and check the history please?

**Comment by pemiranda** [comment] 2021-01-14 23:19
Not sure if this bug is related but since I installed this new version 3.1.0 Build 3013 of Sequel Ace, the filters added to a table view are not persisted when switching to another table. I have to re-create each table's filter whenever I switch between tables. I also see that the Table History is not never updated in this case. It's a super annoying bug. For now I'm opening a new tab and connecting to the same DB host just to look at another table without losing my filters in the other tabs.

**Comment by Jason-Morcos** [comment] 2021-01-15 02:16
> Not sure if this bug is related but since I installed this new version 3.1.0 Build 3013 of Sequel Ace, the filters added to a table view are not persisted when switching to another table. I have to re-create each table's filter whenever I switch between tables. I also see that the Table History is not never updated in this case. It's a super annoying bug. For now I'm opening a new tab and connecting to the same DB host just to look at another table without losing my filters in the other tabs.

Duplicate of issue #770, which has been fixed and will be included in the next release. Unrelated to this issue about query history.

**Comment by Kaspik** [comment] 2021-01-15 18:10
Beta 1 is out, closing this now. We hope to have a release out soon as well (probably starting next week)

**Closed by Kaspik** 2021-01-15 18:10 UTC
Labels: Bug
