### ISSUE TITLE
Query Editor Needs Appearance Auto-Switching (Dark/Light) Support

### ISSUE THREAD

**Issue by xackery** [Sequel-Ace/Sequel-Ace#312] opened 2020-08-22 05:04 UTC
Similar issue might be #100  but this isn't exactly same...

I was using sequel pro until today (love this tool by the way!) and just hopped on Sequel Ace.
I use Dark Theme everywhere.
When I started this up, everything was dark theme except the query editor.
I wrote this vs code inspired theme quickly, but feel this isn't a difficult feature to consider: 
<img width="226" alt="Screen Shot 2020-08-21 at 10 02 22 PM" src="https://user-images.githubusercontent.com/845670/90949075-0432f900-e3fa-11ea-8aac-64ad6eaa0e08.png">

Would love to have a ready made dark theme query editor color theme, or even just a drop down of suggestions for folks to flip between?

Maybe consider allowing a theme for dark and light, assuming someone is using the Appearance Auto switching.

Thanks!

**Comment by Kaspik** [comment] 2020-12-19 09:46
Duplicate of https://github.com/Sequel-Ace/Sequel-Ace/issues/145 btw, I'll close this one.

**Closed by Kaspik** 2020-12-19 09:46 UTC
Labels: Enhancement, Low priority, PR Welcome
