### ISSUE TITLE
3.2.1. Opens new connection window after clicking on icon

### ISSUE THREAD

**Issue by cappadaan** [Sequel-Ace/Sequel-Ace#891] opened 2021-02-19 14:27 UTC
- open DB connection in SA
- open other application window
- click on icon SA in menu
- normally the active DB connection should open but the "home" screen is shown to create a new connection
- the existing DB connection is still active, but there is just another window created

This does not always happens but at least 1 every 4 clicks on the menu icon or maybe less.

This issue started with 3.2.1

**Comment by mfehr94** [comment] 2021-02-19 14:57
@cappadaan can you please use the issue template?

**Comment by Kaspik** [comment] 2021-02-19 15:22
Duplicate of https://github.com/Sequel-Ace/Sequel-Ace/issues/892

**Closed by Kaspik** 2021-02-19 15:22 UTC
