### ISSUE TITLE
Unable to open About/Preferences/Update unless already connected to a DB

### ISSUE THREAD

**Issue by alex-malone** [Sequel-Ace/Sequel-Ace#1027] opened 2021-04-08 14:59 UTC
- Sequel Ace Version (including build number): v3.3.0, Build 3026
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 11.2.3
- Processor Type (Intel/Apple): Intel
- MySQL Version: 8.0.21
- macOS Localization: en-GB

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

Issue is also present in 3.3.1 (3027) - Beta 1.

**Description**

A new user downloads Sequel Ace and attempts to get to 'Preferences' from the connection window. They are unable to do so as the option is greyed out.

<img width="363" alt="Screenshot 2021-04-08 at 14 52 05" src="https://user-images.githubusercontent.com/71494048/114048489-876a6780-9882-11eb-9af5-ccdef5507db4.png">

**Steps To Reproduce**
1. Download and run version v3.3.0 (3026) or 3.3.1 (3027) - Beta 1
2. From the connection window attempt to open 'Preferences' or 'About' - these options are both greyed out and cannot be selected, the keyboard shortcut also does not work.
3. The only way I found to open these is to first connect to a database, they then become selectable

**Expected Behaviour**

User should be able to open 'Preferences', About' or 'Check for updates' from the connection window

![connectionwindow](https://user-images.githubusercontent.com/71494048/114049367-4d4d9580-9883-11eb-9636-070a957f3daf.png)

**Related Issues**

None found

**Comment by Kaspik** [comment] 2021-04-08 15:00
Duplicate of https://github.com/Sequel-Ace/Sequel-Ace/issues/1025

**Closed by Kaspik** 2021-04-08 15:00 UTC
