### ISSUE TITLE
table filtering not available by default

### ISSUE THREAD

**Issue by mcinp** [Sequel-Ace/Sequel-Ace#1587] opened 2022-10-21 10:37 UTC
Several versions ago table view was always opened with "Filter Content" panel available. At some point the functionality was removed and now every time table panel is opened for every new connection, I need to go to Table menu and select "Filter Content" option for which there's even not a keyboard shortcut defined.
Please bring back opening table view with filter content panel enabled by default or provide a configuration option for this.

**Comment by Kaspik** [comment] 2022-10-21 20:31
Filter content has "CMD+S" if you are on Content of the table.

**Comment by mcinp** [comment] 2022-10-22 13:05
Ok, but the shortcut somehow isn't visible on the list.
![Screenshot 2022-10-22 at 15 04 10](https://user-images.githubusercontent.com/5221388/197340495-b529a662-dd6c-4e32-b19b-62992bc15e4f.jpg)
Still I think having it turned on by default would save time for many. I almost never use table view without a filter.

**Comment by Jason-Morcos** [comment] 2022-10-22 22:08
Duplicate of:
- https://github.com/Sequel-Ace/Sequel-Ace/issues/1547
- https://github.com/Sequel-Ace/Sequel-Ace/issues/1517

**Closed by Jason-Morcos** 2022-10-22 22:08 UTC
