### ISSUE TITLE
Error for “Copy as Markdown”:

### ISSUE THREAD

**Issue by chenny** [Sequel-Ace/Sequel-Ace#1724] opened 2023-03-10 04:05 UTC
Error for “Copy as Markdown”:
/bin/bash: /usr/bin/python2.7: No such file or directory
![image](https://user-images.githubusercontent.com/883329/224220526-e6008431-bc0d-4664-a54b-477d3315061d.png)
<img width="342" alt="image" src="https://user-images.githubusercontent.com/883329/224220675-9ae579bd-d553-437f-8109-128051b3750d.png">

**Comment by Jason-Morcos** [comment] 2023-03-11 19:23
Duplicate of https://github.com/Sequel-Ace/Sequel-Ace/issues/1227

**Closed** 2023-03-11 19:23 UTC
