### ISSUE TITLE
Closing tab in Structure view causes freeze

### ISSUE THREAD

**Issue by nexbridge** [Sequel-Ace/Sequel-Ace#1628] opened 2022-11-22 10:22 UTC
- Sequel Ace Version: 4.0.3 (also replicated on 4.0.1)
- Sequel Ace Source: App Store
- macOS Version: 12.6.1 (also replicated on 11.7)
- Processor Type: Intel

Steps to reproduce:

1. Open at least two connection tabs
2. Click on a table on one of the tabs and go to Structure view
3. Close that tab

For me this causes Sequel Ace to freeze.  I've attached an Apple bug report in case it helps.

[bug_report.txt](https://github.com/Sequel-Ace/Sequel-Ace/files/10066377/bug_report.txt)

**Comment by FrancoisDucobu** [comment] 2022-11-29 10:13
same for me

**Comment by s22-tech** [comment] 2022-12-04 18:01
I'm having a similar problem.  Once I open more than 2 tabs, the app freezes and displays the spinning beach ball.  The only way out is to force quit the app.

v4.0.3 downloaded from GitHub
MacOS 10.15.7

**Comment by DannyJJK** [comment] 2022-12-06 20:40
I was initially unable to reproduce the issue on a local database connection, however I set up a SSH connection and tried connecting to the database via SSH, which allowed me to reproduce this issue.

Steps to reproduce:

- Open at least two connection tabs **where one is an SSH connection**
- Click on a table on the tab **that is connected via SSH** and go to Structure view
- Close that tab

**Comment by Kaspik** [comment] 2022-12-20 15:26
Is this happening on 4.0.4 as well?

**Comment by s22-tech** [comment] 2022-12-20 15:59
Yes.  At least it is for me.

**Comment by nexbridge** [comment] 2022-12-20 16:11
@Kaspik Yes it's still happening in 4.0.4.

**Comment by Jason-Morcos** [comment] 2022-12-30 00:25
@Kaspik I assume this is some sort of memory leak issue? Any hints where to look?

**Comment by Iv4nS** [comment] 2023-05-26 19:18
Still a bug for me and every time i open a tab by mistake I know it will freeze, and right on, after closing the tab... all freezes

**Comment by s22-tech** [comment] 2023-06-14 04:21
Same here, still.  I had to resort to using the latest nightly build (5446) of Sequel Pro just to be able to have multiple tabs open.  I sure hope S.A. is able to fix this problem.

**Comment by s22-tech** [comment] 2023-06-14 04:33
I just tried experimenting here.  I installed older versions of SA going back to 3.1.1 and had the same problem with those versions, as well.  It's been awhile so I'm not positive, but I'm pretty sure there was a version of SA that didn't have this problem.  If that's the case, then maybe some settings/prefs file has become corrupted?

**Comment by s22-tech** [comment] 2023-07-14 14:04
Good news!  Version 4.0.6 seems to have fixed the problem for me.  I have 4 tabs open right now (3 localhost and 1 remote) and it's not freezing up.  This is fantastic.  Thank you!

**Comment by s22-tech** [comment] 2023-07-15 17:03
One more update.  Today I tried opening just 2 tabs with connections to my remote server (no localhost connections) and SA froze.  So nothing is any better on this problem.  I'll wait for the next version before trying again.

**Comment by Jason-Morcos** [comment] 2023-07-25 00:06
I can't reproduce this issue, unfortunately. If you can locally and can find a fix, we're happy to review any pull requests from the community!

**Comment by luis-** [comment] 2023-08-13 19:33
I believe #1817 will fix this.

**Comment by s22-tech** [comment] 2023-08-14 00:45
Let's hope so.  I'm pulling for you, Luis.  Thanks!

**Closed** 2023-08-14 08:59 UTC
Labels: Bug

**Comment by s22-tech** [comment] 2023-08-14 15:13
We're so close I can almost taste it.

I downloaded 4.0.7rc1 and proceeded to open multiple tabs to my server by control clicking on the table names in the Tables column and selecting "Open Table in New Tab", and got up to 4 tabs open with no problem.  I then opened a 5th tab from another db on the same server and that one opened without a problem.

So I moved that last tab to a window of it's own and opened a 6th tab from the same db, and SA froze up with the spinning icon.

In the Activity Monitor, I saw there were 6 instances of ssh open, so I closed them one by one to see it that would get SA to come back to life, but it didn't and I ended up having to force quit SA.

Since I was opening tabs by control clicking on the table names, I decided to try again, this time opening new tabs using Cmd-T.  I opened 4 tabs that way, then I created a new window using Cmd-N and opened 4 more tabs successfully, for a total of 8.  It's still running with those 8 tabs open.

So it appears that if we stay away from right-clicking, SA will behave properly.  I'll keep testing, but just wanted to let you know the success I had this morning.  Thank you, Luis!

**Comment by s22-tech** [comment] 2023-08-14 15:28
After about 45 minutes, I navigated to an open tab, clicked the Structure button, and then clicked the little X to close the tab and got the Mac's spinning beachball, not SA's spinner icon that I was getting before.  This appears to be the same problem @nexbridge reported in the OP.

**Comment by Jason-Morcos** [comment] 2023-09-04 20:18
I believe this fix will be included in 4.0.8 and was not part of 4.0.7

**Comment by s22-tech** [comment] 2023-10-06 08:41
This problem seemed to be fixed in 4.0.9.  I was able to open 4 connections to my server without a problem.  

Today I updated to 4.0.10 and the problem returned.  Opening 2 connections to my remote server froze the app, so I reverted back to 4.0.9 and things are back to normal.  I'm staying put for the foreseeable future.

**Comment by Jason-Morcos** [comment] 2023-10-06 23:10
@luis- Did I somehow accidentally revert your change? Otherwise I'm not sure why the issue would have come back in 4.0.10.

**Comment by luis-** [comment] 2023-10-07 23:29
No, doesn't look like the change was reverted. I'm not able to reproduce the issue on `4.0.10`

@s22-tech , if you get a chance, can you try getting a bug report on `4.0.10` so I can take a look at the call stack at the time the hang happens.

**Comment by s22-tech** [comment] 2023-10-08 11:45
@Luis <https://github.com/luis-> - Sure.  What do you mean by “bug report”, though?  Is there a way to generate one from within Sequel Ace, or are you referring to the Console.app?

**Comment by luis-** [comment] 2023-10-08 22:01
Hey @s22-tech, by bug report I was referring to text file in original post i.e. the macos crash/hang report. I believe it gets auto generated when you kill/force-quit Sequel Ace after it hangs -- it may also be available form console app like you mentioned or you can also generate it yourself using `spindump` when Sequel Ace hangs. Something like  `sudo spindump <PID> -onlyTarget -noBinary -stackshotsOnly -reveal` where `PID`  is process id for Sequel Ace.

Thanks a bunch if you are able to get this info! I was able to reproduce issue originally reported but I have had no luck trying to reproduce again after my initial fix so report would definitely help.

Cheers!
