### ISSUE TITLE
Opens new window instead of existing when clicking on icon in taskbar

### ISSUE THREAD

**Issue by cehmke91** [Sequel-Ace/Sequel-Ace#938] opened 2021-03-04 14:30 UTC
- Sequel Ace Version (including build number): 3.3.2
- Sequel Ace Source (App Store/GitHub/Homebrew): Homebrew
- macOS Version: 11.2.1
- Processor Type (Intel/Apple): Intel
- MySQL Version: 5.7
- macOS Localization: none

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes

**Description**
I have a window open, when I click on the icon in the taskbar it opens a new window and brings that one to the front instead of bringing the already open window to the front. 

**Steps To Reproduce**
1. Open SequelAce
2. Connect to a database
2. Open other programs, let their windows have focus
3. Click on taskbar shortcut to bring sequelAce into focus + foreground
4. Observe it opens the 'start screen'
5. A separate window with the connected database still exists.

**Expected Behaviour**
I expect that if the program is running and I click on the taskbar icon that it brings the running window to front and focus, as other programs on the mac do.

**Additional Context**
I'm using 2 monitors with lots of programs open. 
iTerm, Tower, VS Code, Chrome, Postman, Spotify, Spark, Slack, Whatsapp, Signal, and Evernote are all also open. I use ShiftIt to snap programs to halves of the screens and bring into focus the ones I need at the time.

**Comment by Kaspik** [comment] 2021-03-04 14:32
Duplicate of https://github.com/Sequel-Ace/Sequel-Ace/issues/892, fixed in 3.2.3 already.

**Closed by Kaspik** 2021-03-04 14:32 UTC
