### ISSUE TITLE
Custom Bundle Keyboard Shortcuts require (re)activation after Update

### ISSUE THREAD

**Issue by Stavrica** [Sequel-Ace/Sequel-Ace#323] opened 2020-08-27 17:27 UTC
- Sequel Ace Version: 2.1.6 (Build 2074)
- macOS Version: 10.15.6
- MySQL Version: n/a

The keyboard-shortcut-combination for custom bundles that are not included in the standard Sequel Ace distribution cease to function after installing update from the Mac App store.

This has been an ongoing issue with all previous Sequel Ace versions.

(The current workaround is to view the custom bundle in the Bundle Editor window and click [Save] to reapply the key bindings.)

**Comment by Jason-Morcos** [comment] 2020-08-31 00:49
@jamesstout Perhaps this was caused by the dupe bundles fix? https://github.com/Sequel-Ace/Sequel-Ace/pull/146

**Comment by Jason-Morcos** [comment] 2020-10-05 03:10
@Stavrica I worked on a possible fix for this issue, but then realized that I actually cannot reproduce your issue. Is it possible that the keyboard shortcut you are trying to use conflicts with a default bundle?

If anyone at @Sequel-Ace/all is able to reproduce this issue and can test if the fix PR referenced above then fixes it, that would be great. I went straight to trying to fix the issue, assuming I had validated I could reproduce it already in August, but I cannot repro to test my fix.

**Comment by Stavrica** [comment] 2020-10-05 06:15
The issue did not recur on the last Sequel-Ace update (via the MacOS App Store). Though, it did occur during the previous 4 updates. Perhaps some other change in the interim resolved it? 

For what it’s worth, I can confirm that I did not change anything on my end in the meanwhile...

Ovid

-WAMEDES FOOTER: 259321-

**Comment by Jason-Morcos** [comment] 2020-10-05 23:36
Glad it's working now! Definitely let us know if it happens again!

**Closed by Jason-Morcos** 2020-10-05 23:36 UTC
Labels: Highest Priority, PR Welcome, bug
