### ISSUE TITLE
Query window editing performance gets really slow with large queries

### ISSUE THREAD

**Issue by AstroBoy269** [Sequel-Ace/Sequel-Ace#638] opened 2020-12-16 21:09 UTC
- Sequel Ace Version: 3.0.0
- macOS Version: 11.1
- Processor Type (Intel/Apple): Intel
- MySQL Version: 5.6

**Description**
As the text in query window gets longer and longer the performance of typing in the window gets slower and slower.

**Steps To Reproduce**
1. Paste a rather large query see bottom of the report for an example
2. Then just start editing the query and you should be able to see how sluggish the window has become
3. If you delete some text the window performance returns to normal, in the example query delete everything within the `in` clause and you'll be able to edit the query again at full speed.

**Expected Behaviour**
The previous version did not have this slow-down.  And we have some massive queries.

`select `location_hierarchies`.`unit_id` as `unit_id`, count(`messages`.`id`) as `message_count`, coalesce(timediff(now(), from_unixtime(max(`unix_timestamp`))), "829:59:59") AS `age` from `location_hierarchies` as `location_hierarchies` left join `dispense_messages` as `messages` on `messages`.`location_hierarchy_id` = `location_hierarchies`.`id` and event_date BETWEEN DATE_SUB(now(), INTERVAL 7 DAY) AND now() where `location_hierarchies`.`unit_id` in (18, 1648, 2152, 3536, 3537, 3538, 3539, 3541, 3543, 19, 3818, 3820, 3822, 3823, 3824, 3825, 3827, 3828, 3829, 3830, 3832, 3833, 5471, 2200, 3308, 3309, 3310, 3311, 3312, 3313, 3314, 3315, 3316, 3317, 1002, 1006, 2812, 2813, 2814, 1017, 1019, 1020, 1021, 1022, 1023, 1385, 3071, 3072, 3073, 3074, 3075, 3076, 3077, 3078, 3079, 3080, 3081, 3082, 3083, 1754, 2573, 2574, 2575, 2578, 2579, 2580, 2582, 2583, 2584, 2596, 2597, 1753, 2586, 2590, 2591, 2592, 2991, 3287, 3288, 3289, 3290, 7079, 4014, 4015, 5458, 4318, 4320, 4321, 4322, 4323, 4324, 4325, 4326, 4327, 4328, 4329, 4330, 4331, 4332, 4333, 4334, 6338, 6340, 6341, 6342, 6344, 6345, 6346, 6347, 6353, 6354, 6355, 6356, 6357, 6358, 6360, 6361, 6362, 6363, 6366, 6367, 6368, 6369, 6371, 6372, 6373, 1281, 1342, 1490, 1532, 1572, 1590, 1605, 2741, 2743, 2744, 2745, 2746, 2747, 2748, 2749, 2750, 2751, 2752, 2753, 2754, 2755, 2757, 2758, 8736, 1823, 1825, 2000, 2001, 2003, 2331, 2332, 2333, 2334, 2336, 2337, 2338, 2339, 2340, 2342, 6798, 6800, 2109, 2110, 3423, 3424, 3425, 3426, 3427, 3428, 3435, 3436, 3437, 3438, 3439, 3440, 3441, 3442, 3443, 3444, 3445, 3446, 3447, 3448, 3454, 3455, 3457, 3458, 3459, 3460, 3556, 3557, 5194, 5283, 5284, 5285, 5286, 5287, 5289, 5290, 5291, 5292, 5293, 5294, 5295, 5296, 5298, 5299, 5300, 6036, 6037, 6038, 6039, 6040, 6041, 6783, 6784, 6785, 6786, 6787, 6788, 6789, 6790, 6791, 8752, 8755, 8756, 8757, 8758, 2008, 2010, 2343, 2344, 2345, 2346, 2159, 2160, 2161, 2162, 2163, 2164, 8873, 2609, 2610, 2611, 7507, 2680, 2681, 2685, 2686, 5439, 5442, 5443, 5444, 5445, 5446, 5447, 5448, 5450, 5451, 5452, 5453, 5454, 5459, 8093, 6807, 6808, 6809, 6810, 6811, 6812, 6813, 6814, 6818, 6819, 5464, 5465, 8087, 8088, 8090, 8094, 8095, 6891, 6892, 6893, 7072, 7073, 7074, 18, 1648, 2152, 3536, 3537, 3538, 3539, 3541, 3543, 19, 3818, 3820, 3822, 3823, 3824, 3825, 3827, 3828, 3829, 3830, 3832, 3833, 5471, 2200, 3308, 3309, 3310, 3311, 3312, 3313, 3314, 3315, 3316, 3317, 1002, 1006, 2812, 2813, 2814, 1017, 1019, 1020, 1021, 1022, 1023, 1385, 3071, 3072, 3073, 3074, 3075, 3076, 3077, 3078, 3079, 3080, 3081, 3082, 3083, 1754, 2573, 2574, 2575, 2578, 2579, 2580, 2582, 2583, 2584, 2596, 2597, 1753, 2586, 2590, 2591, 2592, 2991, 3287, 3288, 3289, 3290, 7079, 4014, 4015, 5458, 4318, 4320, 4321, 4322, 4323, 4324, 4325, 4326, 4327, 4328, 4329, 4330, 4331, 4332, 4333, 4334, 6338, 6340, 6341, 6342, 6344, 6345, 6346, 6347, 6353, 6354, 6355, 6356, 6357, 6358, 6360, 6361, 6362, 6363, 6366, 6367, 6368, 6369, 6371, 6372, 6373, 1281, 1342, 1490, 1532, 1572, 1590, 1605, 2741, 2743, 2744, 2745, 2746, 2747, 2748, 2749, 2750, 2751, 2752, 2753, 2754, 2755, 2757, 2758, 8736, 1823, 1825, 2000, 2001, 2003, 2331, 2332, 2333, 2334, 2336, 2337, 2338, 2339, 2340, 2342, 6798, 6800, 2109, 2110, 3423, 3424, 3425, 3426, 3427, 3428, 3435, 3436, 3437, 3438, 3439, 3440, 3441, 3442, 3443, 3444, 3445, 3446, 3447, 3448, 3454, 3455, 3457, 3458, 3459, 3460, 3556, 3557, 5194, 5283, 5284, 5285, 5286, 5287, 5289, 5290, 5291, 5292, 5293, 5294, 5295, 5296, 5298, 5299, 5300, 6036, 6037, 6038, 6039, 6040, 6041, 6783, 6784, 6785, 6786, 6787, 6788, 6789, 6790, 6791, 8752, 8755, 8756, 8757, 8758, 2008, 2010, 2343, 2344, 2345, 2346, 2159, 2160, 2161, 2162, 2163, 2164, 8873, 2609, 2610, 2611, 7507, 2680, 2681, 2685, 2686, 5439, 5442, 5443, 5444, 5445, 5446, 5447, 5448, 5450, 5451, 5452, 5453, 5454, 5459, 8093, 6807, 6808, 6809, 6810, 6811, 6812, 6813, 6814, 6818, 6819, 5464, 5465, 8087, 8088, 8090, 8094, 8095, 6891, 6892, 6893, 7072, 7073, 7074) group by `location_hierarchies`.`unit_id``

**Query Editor Settings**
![Screen Shot 2020-12-20 at 2 06 34 PM](https://user-images.githubusercontent.com/10376292/102722065-a2fa3400-42cc-11eb-8bef-ccf2992f6c7e.png)

**Comment by Kaspik** [comment] 2020-12-16 21:47
Please always printscreen your query editor settings from Sequel Ace preferences.

We made major improvements to Query Editor syntax highlighting and I would like to tackle these issues as well. We were not experiencing performance issues with hundreds of lines (https://github.com/Sequel-Ace/Sequel-Ace/issues/573, https://github.com/Sequel-Ace/Sequel-Ace/issues/269, https://github.com/Sequel-Ace/Sequel-Ace/pull/563), so would like to see what's wrong with this one.

**Comment by jordie23** [comment] 2020-12-17 04:42
Performance seems slow when there's subqueries. The more there are, the slower the query editor is. This also happens when it's just another query in the editor and not the active query.

**Comment by rbalslev** [comment] 2020-12-29 09:15
I see it's been given "highest priority" so I realize it's redundant to ask for it here, but just to let you know that this problem means we'll have to (find a way to) revert to a previous version as we edit SPs a lot, and that is impossible in latest version.
Merry Christmas! Keep up the good work.

**Comment by Kaspik** [comment] 2020-12-29 09:23
The more queries you paste here, the more testing we will have, so feel free to attach here txt files with your queries that are causing slowness. Also let us know if you tried to completely wipe and then install Sequel Ace fresh new.

**Comment by acerock6** [comment] 2020-12-29 12:50
Attached a txt below that is causing slow performance during editing (version: 3.0.1 MacOS: 10.15.6)




-- IP apps and attributes

select l.id , tag_name user_category, lw.past_customer 'repeat', timestampdiff(hour, max(luh.review_status_change_date), now()) recency,
if(bank_statement_status in ('VALID','UPLOADED'),1,0) bs_status,
if(current_address_proof_status in ('VALID','UPLOADED'),1,0) cap_status,

 9 - (if(bank_statement_status in ('VALID','UPLOADED'),1,0) 
	  + if(current_address_proof_status in ('VALID','UPLOADED'),1,0) 
	  + if(cancelled_cheque_status in ('VALID','UPLOADED'),1,0) 
	  + if(permanent_address_proof_status in ('VALID','UPLOADED'),1,0) 
	  + if(salary_proof_status in ('VALID','UPLOADED'),1,0) 
	  + if(signature_status in ('VALID','UPLOADED'),1,0) 
	  + if(video_status in ('VALID','UPLOADED'),1,0)
	  + if(pancard_status in ('VALID','UPLOADED'),1,0)
	  + if(selfie_status in ('VALID','UPLOADED'),1,0) 
	  )
	    as docs_pending,
 l.loan_amount, l.external_score, l.pentile, luh.employment_type, kyc_type, 
max(if(old_status='FRAUD_REVIEW' and new_status='IN_PROCESS', 1, 0)) back_move

from loan_application l join loan_udrs_history luh on luh.loan_application_id = l.id
left join kyc_tracking_details k on k.loan_application_id_ref = l.id
left join loan_application_review_workflow lw on lw.loan_application_id_ref = l.id
left join loan_application_metadata m on m.loan_application_id_ref = l.id and tag_name like 'USER_CATEGORY%'
left join loan_application_internal_remarks lr on l.id=lr.loan_application_id
left join loan_applicant_document d on d.loan_application_id_ref = l.id

where l.user_data_review_status = 'in_process'
and luh.user_data_review_status = 'in_process'
and l.app_name not in ('com.tc.moneyview')
and (lw.ops_flow is null or lw.ops_flow not in ('starter_loan'))
and timestampdiff(day, l.review_status_change_date, now()) <= 20
and date(luh.review_status_change_date) > curdate() - interval 2 day 
group by 1;



select distinct(la.loan_application_no),la.kyc_email,la.loan_amount,concat(First_name,' ',last_name) as Name,right(la.kyc_contact_mobile,10) as Mobile,la.user_data_review_status,lar.ekyc_status,lar.user_segment,date(la.review_status_change_date),la.employment_type
from 
loan_application la,
loan_application_review_workflow lar,
loan_application_internal_remarks li
where
la.id = lar.loan_application_id_ref
and la.id=li.loan_application_id
and la.user_data_review_status ='in_process'
and video_status = 'valid'
and selfie_status = 'valid'
and pancard_status = 'valid'
and current_address_proof_status = 'valid'
and permanent_address_proof_status = 'valid'
and salary_proof_status = 'valid'
and bank_statement_status = 'valid'
and la.external_score >= '650'
and la.monthly_income >= '15000'
and cancelled_cheque_status = 'valid'
and la.employment_type ='salaried'
and signature_status = 'valid'
and la.bank_ifsc not like '%YES%';

**Comment by Kaspik** [comment] 2020-12-29 13:13
Spent couple of hours debugging this, couldn't find what's wrong.

Then Google helped me find [this](https://www.thecope.net/2019/09/15/resolving-slow-performance.html) - unfortunately even in Objective-C it's a problematic part - subclassing NSTextStorage causes the slowness and performance issues.

For now Im reverting that functionality which fixes query editor performance.

**Closed** 2020-12-30 10:24 UTC
Labels: Bug, Highest Priority

**Comment by pinpins** [comment] 2021-03-11 19:32
Typing experience is just terrible when you have a lot of SQL text in window.. I think it must be top prio to fix.

**Comment by Kaspik** [comment] 2021-03-11 19:35
We didi revert the slowness that was caused by double click, but right now the top priority is windows hierarchy and structure that will unlock whole new possibilities. We will get to this!

**Comment by pinpins** [comment] 2021-03-11 19:37
Thanks, will keep an eye, should got back to Workbench for now

**Comment by samuelbradshaw** [comment] 2021-03-11 19:41
@pinpins, in case it's helpful, performance in the query editor is much better if the "smart" features are turned off – auto pair characters, auto uppercase, update help while typing, syntax highlight, bracket highlighting, complete with backticks, and auto-completion. I haven't had any issues since turning those off.

**Comment by Drarok** [comment] 2021-07-01 12:20
It's just syntax highlighting for me – I can literally watch characters appear one by one with it turned on, not even with a large query!

![slow](https://user-images.githubusercontent.com/55830/124123322-1ac0cc80-da6f-11eb-9ad7-063ec0f809ce.gif)

**Comment by Jason-Morcos** [comment] 2021-07-04 19:25
PRs are welcome if you've got an idea how to fix it, @Drarok  :)

**Comment by Drarok** [comment] 2021-07-27 23:09
I don't agree with this issue being closed – the underlying problem still exists today?

Are we to take this as a "won't fix", despite it being a major problem day-to-day with only a nuclear workaround?

**Comment by Jason-Morcos** [comment] 2021-07-28 01:44
There is an open duplicate issue for this problem. https://github.com/Sequel-Ace/Sequel-Ace/issues/1071

**Comment by Drarok** [comment] 2021-07-29 09:27
That's the first time that ticket has been mentioned in this thread. Also, that one is a duplicate of _this_ one! 😁

**Comment by NeilSiao** [comment] 2021-09-13 23:22
I just changed default font to others, it becomes normal and very quick,  also We don't need to turn off syntax hightlighting
sequal ace :v.3.4.0 build 3038

**Comment by kwkevinlin** [comment] 2021-09-16 00:51
Using @NeilSiao's suggestion, I changed it to `Menlo` and it also became very quick again. I actually also tried `Arial` and the speed was fine. Of the 4-5 that I tried, it was only the default font that caused issues for me.

Mac OS Big Sur v.11.5.2
Sequel Ace v.3.4.0 build 3038
Apple CPU Intel
DB MySQL

**Comment by Lenitr** [comment] 2021-09-16 08:48
> Using @NeilSiao's suggestion, I changed it to `Menlo` and it also became very quick again. I actually also tried `Arial` and the speed was fine. Of the 4-5 that I tried, it was only the default font that caused issues for me.
> 
> Mac OS Big Sur v.11.5.2
> Sequel Ace v.3.4.0 build 3038
> Apple CPU Intel
> DB MySQL

Thanks for your suggestion for `Menlo` , I've been testing a bit with some huge queries and with syntax highlighting on it seems to work smoothly again. Typing feels instant again, I can't believe that would ever feel like a relief ;)

It even seems to get rid of a delay i sometimes had whenever i executed the first query in a new window. Very odd, I didn't expect the font choice could affect a problem like this but it does seem to be related to the performance issues me and others have reported in multiple different issues here.

I'm not entirely sure how the query editor etc. programmatically work (I'm not an OSX application developer), but I'm wondering if some fonts perhaps have problems rendering properly? Or perhaps since the default option is basically "OS default font" there's something wrong with that detection?
