### ISSUE TITLE
SSL key file "couldn't be opened because you don't have permissions to view it

### ISSUE THREAD

**Issue by DougReider** [Sequel-Ace/Sequel-Ace#81] opened 2020-06-23 13:26 UTC
- Sequel Ace Version: 2.0.0 or 2.0.2
- macOS Version: 10.13.6
- MySQL Version: 10.4.11-MariaDB 

**Description**
When selecting a cert/key file for SSL, you get this message:
![ErrorMsg](https://user-images.githubusercontent.com/52222985/85407892-cd438280-b531-11ea-9acd-e9208942fa71.png)

I figure this is similar to the other sandbox issues, but I didn't see anyone report the exact issue.

**Steps To Reproduce**
1. In connection window, select SSH tab and check "Connect using SSL".
2. Pick one of the "Key File" or "Certificate". Oddly enough, I it accepted my file for "CA Cert".
3. Use the dialog to navigate to the proper location of the file.
4. Select a file.

**Expected Behaviour**
It should be able to read the file, even if it's improperly formatted, the wrong key, or whatever. It's either unable to read the file OR the message is the wrong error message (e.g., if the file is improper).

**Additional Context**
These are the EXACT same files that worked in SequelPro and using the command line.
The rights on these files are:
![Rights](https://user-images.githubusercontent.com/52222985/85407807-b0a74a80-b531-11ea-93cd-cbf33f7f1cc8.png)
As you can see, I've gone so far as to test with world R/W privileges, when originally it was only read.

**Comment by Jason-Morcos** [comment] 2020-06-23 19:32
Possible Duplicate of #52? @jamesstout

**Comment by DougReider** [comment] 2020-06-23 20:17
I read #52. I'm sure the issue is related, but this is slightly different in that a permissions error is being displayed.

**Comment by jamesstout** [comment] 2020-06-24 06:31
It's the sandbox, the open save panel has a delegate that gets called to validate the file URL. In the current code the first thing it does it try to open the file:

https://github.com/Sequel-Ace/Sequel-Ace/blob/399518111dc63211d1b9f21598b5ebcb2a0696e0/Source/SPConnectionController.m#L605-L613

We haven't yet released the code that requests secure access for user-selected files outside the sandbox, so `dataWithContentsOfURL` fails. The error that you see is generated by the Foundation framework, not the SA code.

It should be fixed in an upcoming release. If not, you can build from: https://github.com/jamesstout/Sequel-Ace/tree/more-permissions, or let me know if you want me to produce a build for you to try.

**Comment by Jason-Morcos** [comment] 2020-06-24 22:32
Closing in favor of #52

**Closed by Jason-Morcos** 2020-06-24 22:32 UTC
Labels: bug
