### ISSUE TITLE
Sequel Ace reconnects to local DB instead of remote DB when using SSH

### ISSUE THREAD

**Issue by florianreinhart** [Sequel-Ace/Sequel-Ace#429] opened 2020-10-23 14:21 UTC
- Sequel Ace Version: 2.2.2 (2104)
- macOS Version: 10.15.7
- MySQL Version: 8.0.21

**Description**
I'm connecting to a remote MySQL database using SSH tunneling. I also have a local database for development purposes. The local database is setup exactly like the remote one.

Sequel Ace seems to silently reconnect to the db (e.g. after waking the computer from sleep, switching networks). Sometimes I notice that it has reconnected to the local database, although I was connected to the remote database. I guess Sequal Ace does not reestablish the SSH tunnel and therefore connects to the local database.

**Steps To Reproduce**
1. Create a local and remote MySQL database with the same setup
2. Connect to remote DB with SSH tunneling
3. Cause Sequel Ace to reconnect to the database (e.g. switch networks)
4. Sequel Ace silently reconnects to the local database

**Expected Behaviour**
Sequel Ace should reconnect to the remote database using SSH tunneling.

**Comment by jamesstout** [comment] 2020-10-25 12:15
So you also ssh to the local db? @florianreinhart

**Comment by florianreinhart** [comment] 2020-10-25 13:05
No, I don't use SSH locally.

**Comment by yg-dba** [comment] 2020-10-26 02:59
I also have local MySQL running, as well as remote MySQL connections using SSH.  I have never experienced this issue, even though I don't restart often.  I leave SequelAce open for days.

I do not use an SSH tunnel for the local connection.  For the remote connection, I use an SSH Host with an SSH Key.

SequelAce version 2.2.1
MacOS version 10.14

**Comment by jamesstout** [comment] 2020-10-27 07:03
I can sort of replicate. I have remote db called test, db_name, user and pass the same as a local db running on 127.0.0.1.
I followed:

- Connect to remote DB with SSH tunneling
- Cause Sequel Ace to reconnect to the database (e.g. switch networks)

Nothing happens with just changing networks, but if I connect via WiFi, then switch WiFi off (so Ethernet is used), then refresh then it takes ages to reload a table with one entry. On reconnection, in the debugger, I see the SPMySQLConnection object has:

![Screenshot 2020-10-27 at 2 52 51 PM](https://user-images.githubusercontent.com/1576190/97267309-e99b5700-1864-11eb-9d99-b4b3896d59d4.png)

And the mySQLConnection object also refers to 127.0.0.1

![Screenshot 2020-10-27 at 2 53 04 PM](https://user-images.githubusercontent.com/1576190/97267350-fd46bd80-1864-11eb-976e-3590e1fb7e88.png)
 
With extra logging, you can see it has reconnected:

```
Sequel Ace[1103:2413305] -[SPConnectionController mySQLConnectionEstablished]:2431: mySQLConnectionEstablished
Sequel Ace[1103:2413305] -[SPMySQLConnection isConnected]:320: isConnected called
Sequel Ace[1103:2413305] -[SPMySQLConnection isConnected]:320: isConnected called
Sequel Ace[1103:2414023] -[SPMySQLConnection isConnected]:320: isConnected called
<snip>
Sequel Ace[1103:2415300] -[SPMySQLConnection isConnected]:320: isConnected called
Sequel Ace[1103:2415300] -[SPMySQLConnection isConnected]:320: isConnected called
Sequel Ace[1103:2416157] -[SPMySQLConnection(PrivateAPI) _reconnectAllowingRetries:]:901: reconnection succeeded
Sequel Ace[1103:2417390] -[SPMySQLConnection isConnected]:320: isConnected called
```
However the content of the table is that of the remote db (i put different data in the local and remote tabes so I could check what I was connected to).

Something weird goes on though as all calls to the db are now really slow.

@florianreinhart How did you determine you were connected to the local db?

**Comment by florianreinhart** [comment] 2020-10-27 13:56
@jamesstout Thanks for digging into this.

I discovered this by accident. I usually have Sequel Ace open all the time and connected to the remote database. I noticed one day that a change, which I thought I had made in the remote DB the other day, wasn't there anymore. I checked the local DB and the change was there.

Something like this happened 2 or 3 times. Usually when I wake my Mac from sleep in the morning.

I'll keep an eye on this and will try to find a better way to reproduce it.

**Comment by ronzeidman** [comment] 2021-01-25 07:09
Hi, is there an update on this issue? it wasn't an issue on Sequel pro. Now I experience it all the time... I'm connected through a tunnel that only works through VPN, when the VPN disconnects the tunnel breaks. If I reconnect to the VPN and click on the "reconnect" button on Sequel Ace it doesn't try to restart the tunnel, it just tries to restart the DB connection and connect locally... The only workaround I have now is to create a tunnel myself and maintain reconnect to it when I'm reconnecting the VPN (which disconnects a lot) and have a localhost connection on Sequel Ace. Thanks for looking into it.

**Comment by Jason-Morcos** [comment] 2021-01-26 06:06
No update from me.
@Sequel-Ace/all was anyone able to reproduce this?

**Comment by Jason-Morcos** [comment] 2021-09-12 19:22
This may be fixed in the latest beta, could someone please try and confirm if this is fixed? 

https://github.com/Sequel-Ace/Sequel-Ace/releases

**Comment by ronzeidman** [comment] 2021-09-14 06:03
Works for me! thanks!

**Closed** 2022-01-02 23:49 UTC
Labels: Bug, PR Welcome
