### ISSUE TITLE
Numbers are wrongly formatted as size

### ISSUE THREAD

**Issue by sbhhbs** [Sequel-Ace/Sequel-Ace#541] opened 2020-11-24 07:42 UTC
- Sequel Ace Version: 2.3.0 (Build 2111)
Many numbers are wrongly formatted with a "GiB" suffix like auto_increase, rows etc.

<img width="441" alt="image" src="https://user-images.githubusercontent.com/1070754/100063089-96b8bd80-2e6b-11eb-8a41-faf511a4b939.png">

<img width="243" alt="image" src="https://user-images.githubusercontent.com/1070754/100063056-886aa180-2e6b-11eb-97a5-c0792aa04f32.png">

**Comment by Kaspik** [comment] 2020-11-24 07:46
Duplicate of https://github.com/Sequel-Ace/Sequel-Ace/issues/504

**Closed by Kaspik** 2020-11-24 07:46 UTC

**Comment by Kaspik** [comment] 2020-11-26 10:05
Released 2.3.2 hotfix, available in the AppStore already.
