### ISSUE TITLE
Crash when connecting to a favorite with connection trough ssh that has just been created

### ISSUE THREAD

**Issue by wvell** [Sequel-Ace/Sequel-Ace#764] opened 2021-01-08 15:38 UTC
- Sequel Ace Version (including build number): 3.0.2 Build 3010
- Sequel Ace Source (App Store/GitHub/Homebrew): App store
- macOS Version: 11.1 (20C69)
- Processor Type (Intel/Apple): Intel
- MySQL Version: 5.7.31 - MySQL Community Server
- macOS Localization: en

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
It looks like im using the latest, so yes.

**Description**
The app crashes when you connect to a newly added favorite that connects trough ssh(with private key).

**Steps To Reproduce**
1. Create a new favorite that connects trough ssh
2. After saving the config -> connect

**Expected Behaviour**
It should not crash.

**Comment by Kaspik** [comment] 2021-01-08 15:40
Duplicate of https://github.com/Sequel-Ace/Sequel-Ace/issues/755

**Closed by Kaspik** 2021-01-08 15:40 UTC
