### ISSUE TITLE
Pressing enter to select a filter type starts the filtering, which can return an error message

### ISSUE THREAD

**Issue by samuelbradshaw** [Sequel-Ace/Sequel-Ace#384] opened 2020-10-02 16:11 UTC
- Sequel Ace Version: 2.1.7 (2077)
- macOS Version: macOS Catalina 10.15.7
- MySQL Version: 5.7.31

**Description**
The second drop-down menu in the filter bar allows you to choose which type of filter you want (=, LIKE, IN, etc.). Sometimes when I switch to a different filter, I open the menu and start typing so that the option I'm looking for becomes highlighted, then I press enter to select it. When I press enter, the option becomes selected, but it also causes the filter to start its query before I've typed anything in the text field to filter on. This can cause an error message to appear.

**Steps To Reproduce**
1. Go to the "Content" view on a table with rows that can be filtered.
2. Remove all of the existing filters, then close the filter area, to make sure you're starting with a fresh slate.
3. Tap the filter button at the bottom of the window. The filter area should appear with its default values: Primary key, =, empty text field.
4. Click to open the second drop-down menu (which has "=" selected by default).
5. Type the word "in". This should cause "IN" to be highlighted in the menu.
6. Hit return/enter on the keyboard.

**Expected Behaviour**
"IN" should become selected from the menu, and you should be able to proceed to add text to the text field. This is what I'd expect based on experience with forms on web pages, where pressing enter while a drop-down menu is open selects an item in the drop-down, but doesn't submit the form.

**Actual Behaviour**
"IN" is selected from the menu, and the filter immediately starts, without allowing you to add text in the text field. Because "IN" doesn't allow an empty value, an error message alert appears.

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes, tested in 2.2.0 Beta 4 (2090)

Screenshot:
<img width="1327" alt="Screen Shot 2020-10-02 at 10 02 15 AM" src="https://user-images.githubusercontent.com/7323052/94944355-615ca880-0496-11eb-9e56-a93b66a8846c.png">

**Comment by Jason-Morcos** [comment] 2020-10-02 21:53
Hey @samuelbradshaw, I've noticed you submitting quite a few bug reports over the last couple months; we really appreciate it! However, do you think you'd want to take a stab at fixing this one or any of the others? Unfortunately, there's just not as much bandwidth as we'd like to fix all these issues, but we're quite good about reviewing PRs and helping guide potential fixes. I'd be more than happy to take a look at any PR, even in a WIP form, aimed at fixing this issue!

**Comment by Jason-Morcos** [comment] 2022-01-02 23:49
Closing as I can't reproduce either

**Closed by Jason-Morcos** 2022-01-02 23:49 UTC
Labels: Bug, PR Welcome

**Comment by samuelbradshaw** [comment] 2022-01-03 00:08
The query immediately gets executed when pressing Enter while choosing from the drop-down menu, but I no longer get an error popup.

**Comment by Jason-Morcos** [comment] 2022-01-03 00:08
That seems fine then, if I understand correctly?

**Comment by samuelbradshaw** [comment] 2022-01-03 00:12
I would rather it not execute the query until after I tab to the next field (the text field after the drop-down) and enter some text – because the query returns no results with no text entered in. However, it is better than before.
