### ISSUE TITLE
Tab / Database discrepancy (wrong database selected)

### ISSUE THREAD

**Issue by EricSocs** [Sequel-Ace/Sequel-Ace#1396] opened 2022-02-21 18:33 UTC
Sequel ACE 3.5.0.

On VPN, most databases accessed through VPN.

These are the steps which led to the issue.

Was connected to VPN, had 4 tabs open, all accessing the right database: 

- Tab 2 accessing local database;
- Other tabs accessing remote database.

Mac went to sleep, with tab 2 (local database) selected.

Upon waking: 

- VPN connection lost.
- Database queries are fine in tab 2 (local database).

Then: 

- Reconnected to VPN;
- Switched to tab 1 (remote VPN database);
- Wrong database selected.

```SELECT DATABASE();``` reports queried database is ```database_staging```, whereas the tab shows ```database_sandbox```.

~~It appears that the wrongly selected database is one step down from the list (in my case, the database previously open in tab 1 was database_sandbox, but it actually queried the next database in the list, database_staging).~~ EDIT: Not the case.

_Originally posted by @EricSocs in https://github.com/Sequel-Ace/Sequel-Ace/issues/1207#issuecomment-1044670485_

**Comment by Jason-Morcos** [comment] 2022-03-03 02:58
Strange! @Kaspik any idea what's going on here?

@EricSocs Out of curiosity, are the credentials and mysql port numbers the same for the local connection and the one for the VPN? In other words, if tab 1 just totally didn't SSH and tried to connect locally, would it succeed connecting to the sandbox MySQL?

**Comment by arlomedia** [comment] 2022-03-10 17:49
This happened to me a week or two ago. In my case I'm not using VPN, both databases are on the same remote server and the Mac never went to sleep. I'm using the same connection for both databases and occasionally switching between them with the "Select Database" menu in the top toolbar. At one point I realized the queries I was running were going to the other database, not the one selected in the menu. If it happens again I'll pay more attention to the steps leading up to the problem.

**Comment by arlomedia** [comment] 2022-03-11 19:44
This just happened again a moment ago, and while I didn't notice what steps led to the problem, I can say that it probably isn't related to multiple tabs because I only have one window and one tab open. The Select Database menu includes two databases; one is selected, but Sequel Ace is showing the data from the other. When I switched to the other database and back again, it resumed showing the correct data.

This is the first time I used Sequel Ace today. I left the window open overnight, but my computer did not go to sleep. Oh -- the database that was incorrectly loading was the default database set in my connection bookmark. Maybe the connection was broken overnight and Sequel Ace reconnected automatically, but it connected to the default database rather than the database I was last viewing. If that's what happened, it should check the current value of the Select Database menu and connect to that database instead of the default in the connection bookmark.

**Comment by Jason-Morcos** [comment] 2022-03-13 19:14
> it connected to the default database rather than the database I was last viewing.

Can anyone else confirm that this is what happened for them to (that it connected to the _default_ database)? @Sequel-Ace/all anyone have any idea why that might be happening?

**Comment by gduh** [comment] 2022-03-14 08:48
I haven't been able to reproduce it, but I don't have a VPN, I'm using a remote connection with SSH Tunnel. 
When my remote connection is closed, SACE asks me to reconnect. If not, the tab is closed, otherwise tab # is reconnected to the right database.

**Comment by EricSocs** [comment] 2022-03-28 10:11
Sorry been busy.

> Out of curiosity, are the credentials and mysql port numbers the same for the local connection and the one for the VPN? In other words, if tab 1 just totally didn't SSH and tried to connect locally, would it succeed connecting to the sandbox MySQL?

This does not happen across tabs. I never encountered an issue where the selected database was on a different server from the one originally loaded in a tab. It just seems to pick a database (apparently) at random when a tab has been left open for a while, from the list of databases on a single server.

And to answer your question: no, none of our credentials are the same across servers.

I've upgraded to the latest version. Will report if the issue is still present.

**Comment by Jason-Morcos** [comment] 2022-03-29 06:29
This seems likely related to https://github.com/Sequel-Ace/Sequel-Ace/issues/1254, although I'm really not sure why it's happening at all - PRs aimed at fixing this definitely welcome if anyone has an idea!

**Comment by EricSocs** [comment] 2022-03-29 14:12
Just had a random thought. 

The server I'm usually accessing, and on which this appears to happen the most often, is a test server with 130 databases.

There wouldn't be a limit to the number of items in the dropdown to unsigned byte (127) somewhere in the code, likely to perturb the rendering and selection, would there?

Again, totally random thought.

**Comment by EricSocs** [comment] 2022-03-29 18:24
> In my case, the server I'm connecting to only has two databases.

That rules out the possibility of a signed byte limitation.

**Comment by EricSocs** [comment] 2022-04-01 08:14
Happened again this morning. Latest version.

Woke laptop from sleep.
VPN connection stayed active overnight, did not have to reconnect.
Sequel ACE left open overnight.
Did not change any selection: tab already selected last night was the one I needed.
Ran query SELECT DATABASE();
Result is not the expected one (does not match dropdown selection).

This tab was changed several times yesterday, flipping between databases. It may well be that the application somehow stored the previous database selection, and restored it on wake disregarding the dropdown selection.

**Comment by Kaspik** [comment] 2022-04-01 08:16
I'm more and more convinced it will try to recover from the sleep by selecting random database and the dropdown doesn't match. Still need to find a way how to repro it rather than trying to repro by running SA over night from XCode.

Would love to know if it would work as expected if first thing you do in the morning is select another database in the dropdown?

**Comment by EricSocs** [comment] 2022-04-01 08:19
> Would love to know if it would work as expected if first thing you do in the morning is select another database in the dropdown?

Will try. 

I doubt one needs to wait overnight though. Resuming from sleep is likely sufficient.

**Comment by EricSocs** [comment] 2022-04-14 12:47
This appears either to have been somewhat resolved in Version 3.5.2 - Build 20033, or something else has changed on my machine. Now I'm seeing an error "no database selected" if I try to run a query with the database; the query has been consistently failing, rather than selecting data from another database with a similar structure.

Also, the "No database selected" message occurs multiple times, which I believe is due to multiple tabs being left open; it's always done this when I attempted to run the first query after losing VPN connection: connection errors were shown for every tab open (sometimes in an endless loop), even though I was obviously attempting to run a single query in a single tab. Makes me wonder whether the application cache / keep alive logic is related to the tab discrepancy fault.

**Comment by benritteraptiv** [comment] 2022-07-08 11:50
I saw this behavior yesterday, running Version 3.5.2, Build 20033, on Mac 10.15.6 . I had a database selected, lost VPN when I put my laptop to sleep. When I woke it up and reconnected to VPN, it was running queries against the wrong DB.

**Comment by Jason-Morcos** [comment] 2022-08-16 22:51
Just to be extra sure, is this still happening in the 4.0 beta? https://github.com/Sequel-Ace/Sequel-Ace/releases

**Comment by arlomedia** [comment] 2022-09-25 13:31
The 4.0 beta seems good. I've been running that side by side with the latest production version. For the last three days, I put my computer to sleep at night, and when I started working in the morning, the production version was querying the wrong database but the beta was querying the right database. Thanks!

**Comment by Kaspik** [comment] 2022-09-25 19:27
OH YES, that's such a great news, thanks for testing!

**Comment by Jason-Morcos** [comment] 2022-10-19 21:59
Closing as 4.0.0 has now been released!

**Closed by Jason-Morcos** 2022-10-19 21:59 UTC
Labels: Bug, Highest Priority, Need More Info

**Comment by fmaltez** [comment] 2022-10-27 17:45
Continues active bug in Version 4.0.0 - Build 20036
I'm not using VPN and the computer doesn't obligatorily has to return from sleep for this to happen.

The "visually" selected database in the interface does not match the "actually" selected database used by sequel ace engine.

When clicking to view a table this occurs.
![Screenshot 2022-10-27 at 18 26 45](https://user-images.githubusercontent.com/29949102/198359219-3c7564fb-4b03-4bb0-a423-0ad5f4ffb690.png)

When querying a table this occurs
<img width="371" alt="Screenshot 2022-10-27 at 18 38 32" src="https://user-images.githubusercontent.com/29949102/198360362-ef88fac0-c04e-4284-8edf-d53d54cad85a.png">

The problem is bypassed by switching to another schema in the select menu, and then switching again, and back to the initially "visually only" selected schema.

**Comment by Kaspik** [comment] 2022-10-27 18:09
4.0.0 was fast followed by 4.0.1, can you use that?

**Comment by erikbaan** [comment] 2023-12-27 11:45
Same happening to me with 4.0.13. This happens every time after inactivity for +- 15 minutes.
