### ISSUE TITLE
Unable to maximize window size by default

### ISSUE THREAD

**Issue by cappadaan** [Sequel-Ace/Sequel-Ace#1006] opened 2021-04-07 07:17 UTC
- Sequel Ace Version (including build number): 3.3.0
- Sequel Ace Source (App Store/GitHub/Homebrew): Github
- macOS Version: 11.2.3 
- Processor Type (Intel/Apple): Intel
- MySQL Version: 10.5.9

> click op app icon
> window size is 50% height en 50% width of my resolution

> double click on window => maximizes window
> restart app
> window size is 50% height and 50% width of my resolution

other variant

> manually resize window to max resolution
> restart app
> window size is 50% height and 50% width of my resolution

There doesnt seem to be a way to maximize the window and store that setting.

**Comment by Kaspik** [comment] 2021-04-07 07:22
Window and state restoration is not yet supported, but 3.3.0 added a lot of things that will help us enable it soon! 🤞🏼

Duplicate of https://github.com/Sequel-Ace/Sequel-Ace/issues/729, closing.

**Closed by Kaspik** 2021-04-07 07:22 UTC
