### ISSUE TITLE
Query history, every row is a new query

### ISSUE THREAD

**Issue by cappadaan** [Sequel-Ace/Sequel-Ace#851] opened 2021-02-02 08:42 UTC
V 3.1.1

Since this version the Query history is malfunctioning. Every row in the query editor is now a seperate query.

SELECT
  name
FROM
 table

causes 4 queries in the query history.

**Comment by jamesstout** [comment] 2021-02-02 08:44
dupe of #849

Fixed and awaiting release. Sorry for the inconvenience.

**Closed by jamesstout** 2021-02-02 08:44 UTC
