### ISSUE TITLE
Wishlist : support for AWS Session Manager Tunneling

### ISSUE THREAD

**Issue by jwestbrook** [Sequel-Ace/Sequel-Ace#1474] opened 2022-06-02 18:49 UTC
Per the recent announcement AWS Systems Manager now supports port forwarding to remote servers so a AWS instance can be a jump host but not expose any ports to the internet.

https://aws.amazon.com/about-aws/whats-new/2022/05/aws-systems-manager-support-port-forwarding-remote-hosts-using-session-manager/

for example current SSH Tunnel is 

client => SSH tunnel => jump host => Database Server

with Session manager

client => Session manger Port => jump host instance => RDS

Yep, I get it needs the AWS CLI to be installed and configured correctly, but at this point no other SQL clients support this natively and if I can reduce the ports I have open to the world I will.

**Comment by Jason-Morcos** [comment] 2022-06-20 00:04
I'm gonna go ahead and close this as a duplicate of https://github.com/Sequel-Ace/Sequel-Ace/issues/202.

Unfortunately, the sandbox makes these things difficult because it doesn't let us leverage outside command line tools.

What I'm personally doing as a workaround now is leveraging that new port forwarding feature you mentioned to open a tunnel on my Mac (using the Terminal) and then having Sequel Ace connect to that local port via TCP/IP which does work. I know this isn't ideal :/

**Closed by Jason-Morcos** 2022-06-20 00:04 UTC

**Comment by jwestbrook** [comment] 2022-06-20 01:09
<derp> Forgot about the sandbox restriction - Another thought - using the actual AWS SDK and triggering the SSM command `startSession` which allows you to open a websocket connection - don't know the viability of going down that path, though.

Thanks for replying
