### ISSUE TITLE
MySQL connection stuck on "SHOW VARIABLES"

### ISSUE THREAD

**Issue by KittMedia** [Sequel-Ace/Sequel-Ace#151] opened 2020-07-02 08:20 UTC
- Sequel Ace Version: 2.1.0 Build 2042
- macOS Version: 10.15.5
- MySQL Version: 5.7.29-32-57-log

**Description**
One of my configuration seems to be not working in Sequel Ace. The same configuration does work on Sequel Pro, though.
It’s a very limited SSH connection where only the MySQL service is allowed.

![sequel-ace-stucks-crunch](https://user-images.githubusercontent.com/1018979/86333590-6702e200-bc4c-11ea-8da6-7aa929de9aec.png)

It just says „MySQL connecting…“. If I open the console before trying to connect, you can see that Sequel Ace runs `SHOW VARIABLES;` every second for this connection.

**Expected Behaviour**
The connection is established.

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes!

**Additional Context**
Sorry that I cannot give more information about the server-side configuration since this isn’t administrated by myself.

**Comment by gboudreau** [comment] 2020-07-02 12:19
Seems to be a problem with the MySQL server configuration. Without knowing how the server is configured, or being able to reproduce ourselves, it's going to be tough to understand why this is happening.
Let us know if you can obtain the MySQL's my.cnf config. (It is world-readable by default, because it doesn't include sensitive information, so maybe you can check if you have read access to `/etc/mysql/my.cnf` or similar).

**Comment by KittMedia** [comment] 2020-07-02 12:24
Would it be sufficient to get the content of `SHOW VARIABLES;`? Since Sequel Pro does still work, I can get these information.

**Comment by jamesstout** [comment] 2020-07-03 08:30
Are you definitely on 5.7.29? A bug re `LOCK TABLES` and `SHOW VARIABLES` was fixed in 5.7.29.

https://bugs.mysql.com/bug.php?id=92387

I just replicated it with 5.7.26:

![Screenshot 2020-07-03 at 4 26 43 PM](https://user-images.githubusercontent.com/1576190/86449257-82541700-bd4a-11ea-8d9a-cbe028e8058e.png)

Doesn't stop other connections though, so must be something else...

**Comment by KittMedia** [comment] 2020-07-03 08:44
`5.7.29-32-57-log` is the output of `SELECT VERSION()`; though I think that should be correct.

**Comment by KittMedia** [comment] 2020-07-07 05:32
Interesting, when I tried the beta 5 days ago, it didn’t work. Now with the final version 2.1.1 it works just fine for me. I can now connect to this host. 🙂

**Closed** 2020-07-07 06:36 UTC
Labels: Support
