### ISSUE TITLE
Can not create a new database

### ISSUE THREAD

**Issue by n9yty** [Sequel-Ace/Sequel-Ace#402] opened 2020-10-15 00:56 UTC
- Sequel Ace Version: 2.2.0 Builde 2092
- macOS Version: 10.15
- MySQL Version: 8.0.20

**Description**
I can not create a new database. I get no errors or warnings that I can find, the prompt for name and character sets just goes away and no new database is created. I have tried an older version of Sequel Ace and SequelPro and it works as expected.

**Steps To Reproduce**
1. Connect to server
2. Select "Add Database..."
3. Fill out the data
4. No database created

**Expected Behaviour**
I expect the database to be created. :)

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
This I haven't tried as the release was just made so I assumed it was mostly the newest code, and this is a core function that should be working.

**Comment by Jason-Morcos** [comment] 2020-10-15 02:09
Can reproduce
@Kaspik Looks like this was broken by a modal sheet conversion
The add button just closes the modal and used to rely on `- (void)sheetDidEnd:(id)sheet returnCode:(NSInteger)returnCode contextInfo:(NSString *)contextInfo` on SPDatabaseDocument.m to catch the close and execute the proper action. Perhaps the other database actions may be broken too

**Comment by Kaspik** [comment] 2020-10-15 07:34
Afaik in https://github.com/Sequel-Ace/Sequel-Ace/pull/389/files I did nothing with `createDatabase` and the code in `sheetDidEnd` is still the same. Let me take a look on that tho.

**Comment by Jason-Morcos** [comment] 2020-10-15 14:35
Please try the latest beta and let us know if it's fixed now!

https://github.com/Sequel-Ace/Sequel-Ace/releases

**Comment by hongsolo9** [comment] 2020-10-15 15:40
This latest beta works. Looking forward to install the app from App Store after Apple approval.

**Closed** 2020-10-16 12:40 UTC
Labels: Fixed & Pending Release
