### ISSUE TITLE
Title bar text takes half of the space leaving little room for tool bar

### ISSUE THREAD

**Issue by toddstoffel** [Sequel-Ace/Sequel-Ace#727] opened 2020-12-31 09:09 UTC

**Comment by Jason-Morcos** [comment] 2021-01-02 20:16
Duplicate of #562, #544, #534, #578 and #595

This is a Big Sur thing and unfortunately something we have little to no control over! We're planning on making some future UI changes which may mitigate some of this issue.

**Closed by Jason-Morcos** 2021-01-02 20:16 UTC
