### ISSUE TITLE
"Select all" tables in sidebar behaves really slow

### ISSUE THREAD

**Issue by mgrn0** [Sequel-Ace/Sequel-Ace#864] opened 2021-02-09 15:17 UTC
- Sequel Ace Version (including build number): 3.2.0
- Sequel Ace Source (App Store/GitHub/Homebrew): Github, but also true for App Store
- macOS Version: 10.14.6
- Processor Type (Intel/Apple): Intel
- MySQL Version: 5.7.30
- macOS Localization: EN/US

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?** YES

**Description**
When connected to a database, hitting **Command+A** to select all tables *does* select all tables but it takes a few seconds during which the animation looks freezing the UI. 

**Steps To Reproduce**
1. Connect to a DB, e.g. localhost
2. Hit Command+A in the sidebar / same for _main menu > Edit > Select > All_
   to select all available tables (e.g. in order to export the complete database)

**Expected Behaviour**
All tables of the database should be selected immediately without delay.

**Related Issues**
None that I cold find

**Additional Context**
Attached an animated gif which shows (in ~realtime) how the animation does not play smoothly / fast.
![sequel](https://user-images.githubusercontent.com/3019226/107384406-3b08e280-6af2-11eb-9944-6b3bdf292d5f.gif)

**Comment by gduh** [comment] 2021-02-12 09:24
Cannot reproduce with ACE 3.1.1 from App Store.

Is 3.2 not yet available on the App Store ?

**Comment by mgrn0** [comment] 2021-02-12 09:29
I get 3.1.1 on the app store still, however it also happens with the 3.2.0 beta for me, maybe that is an issue occurring with certain Mac OS versions?

**Comment by gduh** [comment] 2021-02-12 09:56
I use Catalina 10.15.7. The other main difference is that I use MariaDB instead of Mysql, but I'm not sure it can be interfere.

**Comment by mgrn0** [comment] 2021-02-12 10:22
I just tried with MariaDB, same effect.

**Comment by gduh** [comment] 2021-02-12 10:31
Do you have a lot of items (tables, stored proc, ...) in your selection ?

**Comment by mgrn0** [comment] 2021-02-12 10:33
it also happens when connected to a db with ~ 10 tables.

**Comment by Jason-Morcos** [comment] 2021-02-12 23:13
Cannot reproduce as well, but I'm on Big Sur. Does it still happen on the 3.2.0 App Store release as well?

**Comment by mgrn0** [comment] 2021-02-13 14:50
I will check on another machine with Big Sur running later today. I don't get 3.2. through the App Store (yet). Will try with github and beta version.

**Comment by mgrn0** [comment] 2021-02-16 22:04
Checked on a M1 Macbook air with Big Sur running, there with App store version 3.2.0 it does not happen, selecting works like expected.

Might be an issue with my specific OS version, I guess will live with it until I upgrade ;)

**Comment by Kaspik** [comment] 2021-03-03 22:13
Can't reproduce either on M1, so I'll close this now. :)

**Closed by Kaspik** 2021-03-03 22:13 UTC
Labels: Bug, Cannot Reproduce, Low priority, PR Welcome
