### ISSUE TITLE
Find (Command-F) is no longer opens search window

### ISSUE THREAD

**Issue by kaarta-dstrickler** [Sequel-Ace/Sequel-Ace#1020] opened 2021-04-07 21:01 UTC
- Sequel Ace Version (including build number): 3.3.0
- Sequel Ace Source (App Store/GitHub/Homebrew): 3026
- macOS Version: 11.2.3 (20D91)
- Processor Type (Intel/Apple): M1
- MySQL Version: Not sure.
- macOS Localization: English

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
-- No, I don't see it listed, and I can't easily test out the latest version. The version I am using is from the App Store, and appeared to change some visual changes in the last few days.

**Description**
I used to use the command to filter my tables by pressing Command-F. The keystoke no longer brings up the filter window, and if I find the Find command in the menu, it's greyed out. Normal functions I use see to work fine.

**Steps To Reproduce**
1. Open up a Table so it displays the fields & data on the screen.
2. Press Command-F and look for the Find window - it's not there.

**Expected Behaviour**
I expected the Find/Filter window to appear so I could put in text to filter on.

**Related Issues**
Done.

**Additional Context**
None. Thank you for a great product which I use every day!

**Comment by Kaspik** [comment] 2021-04-07 21:02
Duplicate of https://github.com/Sequel-Ace/Sequel-Ace/issues/1014 - already fixed! :)

**Comment by Kaspik** [comment] 2021-04-07 21:03
Btw. filter is still there - it's under `Table`, not `Edit` Main Menu option iirc.

**Closed by Kaspik** 2021-04-07 21:02 UTC

**Comment by kaarta-dstrickler** [comment] 2021-04-07 22:00
My apologies - I didn't see that when I searched for a previous bug.
