### ISSUE TITLE
Default Sort Order / Sequence

### ISSUE THREAD

**Issue by billynoah** [Sequel-Ace/Sequel-Ace#1974] opened 2024-03-07 21:19 UTC
Clicking on a column heading typically results in first sort asc, then sort desc.  For some columns this is fine but for others (like autoincrement) they are sorted asc by default so it's a redundant extra click and table load every time I want to view the newest rows first - which for me is probably a hundred times a day.

I don't have a cut and dry solution proposal but here are a couple of ideas:
- Autoincrement columns could always sort DESC first since the default view is sorted ASC
- Have a preference for the order sequence on click similar to https://datatables.net/reference/option/columns.orderSequence
- Have a preference for default sort when a table is first loaded.  This would actually be ideal except for cases for a table doesn't have a single auto inc column or the primary index is compound.

I'm interested in suggestions and brainstorming if anyone has any ideas

**Comment by samuelbradshaw** [comment] 2024-03-08 00:14
Related: https://github.com/Sequel-Ace/Sequel-Ace/issues/1374. I can understand how it could be helpful depending on your workflow, but I think it might be confusing for some columns to sort ascending and some descending.

**Comment by Jason-Morcos** [comment] 2024-03-08 00:43
Closing as a duplicate of https://github.com/Sequel-Ace/Sequel-Ace/issues/1374

**Closed by Jason-Morcos** 2024-03-08 00:43 UTC
