### ISSUE TITLE
Query Editor uses a different database than the one selected in "Select Database" dropdown

### ISSUE THREAD

**Issue by bbleakley** [Sequel-Ace/Sequel-Ace#2007] opened 2024-04-26 14:25 UTC
- Sequel Ace Version (including build number): 4.0.13 20062
- Sequel Ace Source (App Store/GitHub/Homebrew): app store 
- macOS Version: 14.4.1
- Processor Type (Intel/Apple): Apple
- MySQL Version: 5.7.12
- macOS Localization: US English

**Description**
After leaving Sequel Ace unattended for an extended period, Sequel Ace appears to switch from the selected database to the first database when sorted alphabetically without updating the "Select Database" dropdown. The issue can be resolved by disconnecting and reconnecting or by manually changing the dropdown to a different value and then back to the desired value.

**Steps To Reproduce**
I've used Sequel Ace for a long time now and used it to connect to servers that have multiple databases and never experienced this type of issue. I've started working for a new employer and had to use a VPN to access the server and my assumption is that the issue is connected to that. These steps have reliably reproduced the issue for me:
1. Connect to VPN
2. Connect to database only accessible through VPN in Sequel Ace
3. Select a database other than the first database when sorted alphabetically
4. Disconnect from the VPN
5. Put computer to sleep for the night
6. Reconnect to the VPN
7. Run SELECT DATABASE(); in Sequel Ace

**Expected Behaviour**

Sequel Ace should use the database selected in the "Select Database" dropdown

![database_selection_issue](https://github.com/Sequel-Ace/Sequel-Ace/assets/10534223/87114f78-b234-4a48-bd0e-19fa48d74ab4)

**Comment by Jason-Morcos** [comment] 2024-04-26 17:52
Duplicate of https://github.com/Sequel-Ace/Sequel-Ace/issues/1806

**Closed** 2024-04-26 17:52 UTC
