### ISSUE TITLE
Running query in one window/tabs checks for connectivity status of other windows/tabs

### ISSUE THREAD

**Issue by gms8994** [Sequel-Ace/Sequel-Ace#282] opened 2020-07-30 20:39 UTC
- Sequel Ace Version: 2.1.5
- macOS Version: 10.15.5
- MySQL Version: N/A

**Description**
Running a query against a local server first checks the connected status of remote servers, which may require closing the tabs before continuing (potentially losing user generated queries).

**Steps To Reproduce**
1. Connect to a remote server and run some queries. 
2. In another tab, connect to a local server and run some queries.
3. Disconnect your network connection and try to run queries in the local server window. (It may take a minute before Sequel Ace makes this determination).
4. You'll be prevented from doing so until a check for connectivity for the remote server completes (and subsequently fails and requires you to close the tab).

**Expected Behaviour**
Don't check a background tab connection status, so the tab won't need to be closed. It's a

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
N/A

**Comment by gms8994** [comment] 2020-07-30 20:40
This may not be the running of the query that triggers it, but perhaps just a status bar notification that the connection is gone instead of stealing focus and forcing a close (perhaps reconnect isn't possible)?

**Comment by jamesstout** [comment] 2020-07-31 06:37
I can't reproduce this, I can run the local query, until after a minute or so, I get a prompt saying the remote server connection was lost and I need to [dis|re]connect.

remote: maria 10.4.13
local: 8.0.21

I'll look at the connection code though..

**Comment by jamesstout** [comment] 2020-07-31 08:00
Might be related to updating the query history. The first thing it does is check if it's connected...

```objc
- (void)historyItemsHaveBeenUpdated:(NSNotification *)notification
{
	// Abort if the connection has been closed already - sign of a closed window
	if (![mySQLConnection isConnected]) return;

```

```objc
- (BOOL)isConnected
{
	// If the connection has been allowed to drop in the background, restore it if posslbe
	if (state == SPMySQLConnectionLostInBackground) {
		[self _reconnectAllowingRetries:YES];
	}

	return (state == SPMySQLConnected || state == SPMySQLDisconnecting);
}
```

`_reconnectAllowingRetries` waits 10 seconds, tries to reconnect, then displays the dialog. Still unsure why it's checking the other tab though.

**Comment by jamesstout** [comment] 2020-08-03 08:45
No, it's the `_keepAlive` timer. If no connection, calls `_reconnectAfterBackgroundConnectionLoss` which calls `_reconnectAllowingRetries`, which if all connection attempts fail, calls `_delegateDecisionForLostConnection` which prompts the user to [re|dis]connect.

The timer runs on all connections.

**Comment by Jason-Morcos** [comment] 2020-08-08 06:23
@jamesstout So is this a bug or should we close this issue or what? I'm a little confused what the next step is here! :)

**Comment by jamesstout** [comment] 2020-08-09 08:33
Not entirely sure it's a bug. We could as @gms8994 suggests add this feature:
>perhaps just a status bar notification that the connection is gone instead of stealing focus and forcing a close (perhaps reconnect isn't possible)?

**Comment by Iv4nS** [comment] 2020-08-23 17:55
This is a really big issue in my workflow, I've encountered many times and I always loose my entire tab if I'm unable to reconnect to the server.

**Comment by samuelbradshaw** [comment] 2020-08-23 18:04
I've run into this as well; it would be nice if there were a way to indicate that it's disconnected without blocking the user and closing the tab, so anything you're currently working on in that tab can be copied to somewhere else before closing. A note in the status bar would be good, but I'm not sure if it's visible enough that the user will understand what's happening when they come back to the tab but then can't do anything. I'm not sure what the best UX would be.

**Comment by Iv4nS** [comment] 2020-08-23 18:10
I agree, the best scenario would be to leave it disconnected somehow with an indicator, maybe graying out at all the tables and database selection, with only the queries tab visible and allow reconnection later on when the user decides to (if ever).

Another solution I've thought that it would at least make things somewhat better (if the tab really can't live without the connection) would be to have a button in that same dialog to either save the queries to a file or to the clipboard.

**Comment by Iv4nS** [comment] 2020-08-25 16:52
I would actually classify it as a bug. A very bad analogy would be: You have a browser opened with multiple tabs, one of them mysite.com and another coolsite.com, you are doing things on the coolsite.com tab and for some reason the server hosting mysite.com goes down then your browser forces you back to mysite.com and to either refresh until the server is back or entirely close that tab.

**Comment by indreka** [comment] 2020-12-11 10:29
Can confirm that when connecting to different VPN and while leaving old query window/tab open and then trying to run query in some other window/tab, the previous window/tab steals focus and complains about connection loss and gives only 2 options: reconnect or close
While being in a different VPN, reconnect is not an option and closing the window/tab means losing previous state so it is also not an option actually. Having a "Cancel" there would improve situation.

Checking all tabs/windows connection when doing a query in only ONE should be definitely classified as a bug not to mention a big overhead with many windows open.

**Comment by FaimMedia** [comment] 2020-12-28 16:07
Same problem here, very annoying, if a connection in an other tab is lost, Sequel will hang for like 30 secondes before responding. Even when using a different tab.

**Comment by n9yty** [comment] 2021-03-02 03:12
Still happening to me somewhat regularly, especially with remote connections over ssh, if I leave a window open and come back later, sometimes not even realizing I had an old window, opening a new one, and then things become unresponsive as it complains about the lost connection. There should be a graceful recovery in case a connection is lost, I have tried using "reconnect" many times but it never does and eventually the only way out is to close windows and lose the query.

**Comment by Kaspik** [comment] 2021-04-04 21:08
This _might_ be resolved now. Closing, let us know if it's still an issue!

**Comment by indreka** [comment] 2021-04-06 10:02
This is still not resolved after latest update, the issue is not tab specific, you should be able to reproduce with 2 windows open (both having only one tab).

It should be quite easy to verify:
assuming you have kubernetes and/or docker, run two instances of mysql databases on different ports
In sequel ace, open two connections, one to each database.
Close one of the mysql instances while keeping the other running.
Wait at least 30 minutes, try to run query in a window that was opened to the server that is still running.
Other window (connected to the closed mysql instance) pops info focus and keeps nagging about closing the connection or reconnecting.

**Comment by Kaspik** [comment] 2021-04-06 10:16
Okay, then it's not related to tabbing but to not closing the connections actually - which is duplicate of https://github.com/Sequel-Ace/Sequel-Ace/issues/811

**Comment by indreka** [comment] 2021-04-06 10:23
Umm, are you 100% sure? #811 describes issue that connection remains open even when closing a window/tab this is not relevant to this issue at all.

In the case that I described (and everyone else in this issue have described) the windows/tabs are all open, no one is trying to close anything on their own. Please read the previous comment more thoroughly. I'm talking about actual mysql server instances going away in the background, not sequel ace instances, they are not the same...

**Comment by Kaspik** [comment] 2021-04-06 10:30
Hmm, okay, I read "Close one of the mysql instances while keeping the other running." as close the Sequel Ace instance.

Sounds like it's a mix of #811, https://github.com/Sequel-Ace/Sequel-Ace/issues/658 and slightly https://github.com/Sequel-Ace/Sequel-Ace/issues/345 - the connections are not managed properly right now under some circumstances (computer sleep, memory pressure, ...). Reconnection is problematic and is also a blocker due to not being able to reconnect. Big refactoring is on our roadmap, the tabbing / windows was a first step.

**Comment by indreka** [comment] 2021-04-06 10:32
Ok, thanks for reopening the issue, will keep updating the status with newer releases :)

**Comment by Jason-Morcos** [comment] 2021-09-12 19:23
This should be fixed in the latest beta along with #658! If not, I'll re-open
The fix will be included in release 3.4.1!

**Closed by Jason-Morcos** 2021-09-12 19:23 UTC
Labels: Bug, Need More Info

**Comment by yg-dba** [comment] 2025-01-23 15:50
Thank you for all producing a great SQL client!  I prefer SequelAce over many others.

However, this is still a frustrating issue in release 4.0.1.  

Besides for spinning, it actually sometimes causes SequelAce to crash completely which causes lost work, sometimes after a minute or two after closing the disconnected connection.

Is there a setting that needs to be turned on with the bug fix above to avoid this issue?

**Comment by Kaspik** [comment] 2025-01-23 15:56
@yg-dba Why would you be running 4.0.1?

**Comment by yg-dba** [comment] 2025-01-23 16:12
I had an issue on some version which is why I just stayed on one version.  What version do you recommend?  I'll try to upgrade.

**Comment by Kaspik** [comment] 2025-01-23 16:22
The latest should be the more stable with some bugfixes recently.

**Comment by yg-dba** [comment] 2025-01-30 19:54
I'm not sure if this should be put somewhere else, so please let me know.

At @Kaspik recommendation, I upgraded to the latest version of SequelAce a few days ago.  

Today I got the disconnected warning (even though I think my VPN was connected).  I attempted to reconnect which failed.  I then clicked "Close Connection".  After doing this twice due to multiple tabs to the same connection, it seemed to work fine for about a minute, and then SequelAce crashed.

Attached is the crash report.

[sequelace-crash-report20250130.txt](https://github.com/user-attachments/files/18608008/sequelace-crash-report20250130.txt)

Thank you so much for your help with this!
