### ISSUE TITLE
Rows count wrong formatting

### ISSUE THREAD

**Issue by claudiu-cristea** [Sequel-Ace/Sequel-Ace#553] opened 2020-11-26 10:01 UTC
- Sequel Ace Version: 2.3.1 build 2117
- macOS Version: 11.0.1 (20B29)
- Processor Type (Intel/Apple): 2,3 GHz 8-Core Intel Core i9
- MySQL Version: Ver 8.0.21 for osx10.15 on x86_64 (Homebrew)

**Description**

The rows count formatting, at the bottom of the table browser, is wrong:

- is formatted as decimal 
- it has MiB as units

See the attached screenshot.

<img width="513" alt="rows" src="https://user-images.githubusercontent.com/473868/100336326-b6242780-2fde-11eb-83b4-5794bfe263d3.png">

**Steps To Reproduce**

On a table loot at the bottom status bar. Apply a filter and check again.

**Expected Behaviour**

- integer formatting
- no digital unit

**Comment by Kaspik** [comment] 2020-11-26 10:03
Please, please - use search on github to save us some time. 😞 

Duplicate of https://github.com/Sequel-Ace/Sequel-Ace/issues/545, https://github.com/Sequel-Ace/Sequel-Ace/issues/504, https://github.com/Sequel-Ace/Sequel-Ace/issues/550 and https://github.com/Sequel-Ace/Sequel-Ace/issues/541

**Closed by Kaspik** 2020-11-26 10:03 UTC

**Comment by Kaspik** [comment] 2020-11-26 10:05
Released 2.3.2 hotfix, available in the AppStore already.
