### ISSUE TITLE
Password not sent in 3.0.0 beta

### ISSUE THREAD

**Issue by mrdziuban** [Sequel-Ace/Sequel-Ace#604] opened 2020-12-09 14:03 UTC
- Sequel Ace Version: 3.0.0 beta 3
- macOS Version: 10.14.3
- Processor Type (Intel/Apple): Intel
- MySQL Version: MariaDB 10.4.10

**Description**

When attempting to connect to a database with a username and password, the password is not sent. An "Access denied!" alert appears and says `(using password: NO)`. After closing the alert, the password is no longer filled in the connection details. This happens for both TCP/IP and SSH connections (I have not tested a socket connection).

**Steps To Reproduce**

1. Fill out details for a connection that requires a password
2. Click "Connect" and see "Access denied!" alert
3. Close "Access denied!" alert and see that password is no longer filled in connection details

**Expected Behaviour**

The password should be sent to ensure the connection succeeds.

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

Yes

**Additional Context**

<img width="453" alt="connection details" src="https://user-images.githubusercontent.com/4718399/101639053-d7344180-39fc-11eb-98d1-de9dd0b3f95e.png">

<img width="426" alt="access denied" src="https://user-images.githubusercontent.com/4718399/101639390-40b45000-39fd-11eb-961b-fa6e22c748db.png">

**Comment by Kaspik** [comment] 2020-12-09 14:17
Duplicate of https://github.com/Sequel-Ace/Sequel-Ace/issues/598

Thanks for more details, we are working on this!

**Closed by Kaspik** 2020-12-09 14:17 UTC

**Comment by mrdziuban** [comment] 2020-12-09 14:18
Aha, sorry I missed that one! Thanks for digging into it.
