### ISSUE TITLE
"Edit > Find" conflicting with "Table > Filter Content"?

### ISSUE THREAD

**Issue by Phennim** [Sequel-Ace/Sequel-Ace#1026] opened 2021-04-08 14:53 UTC
- Sequel Ace Version (including build number): Version 3.3.0 Build 3026
- Sequel Ace Source GitHub
- macOS Version: Catalina 10.15.7
- Processor Type (Intel/Apple): Intel
- MySQL Version: -
- macOS Localization: English

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes

**Description**
I used to use CMD+F to search a table, but that is now always grayed out.
It did the same thing that "Table > Filter Content" does now.

**Steps To Reproduce**
1. Open a connection, database and table
2. Press CMD+F

**Expected Behaviour**
Open the table's Content tab and add the 'filter' form above rows.

**Comment by Kaspik** [comment] 2021-04-08 14:55
Duplicate of https://github.com/Sequel-Ace/Sequel-Ace/issues/1014

**Closed by Kaspik** 2021-04-08 14:55 UTC
