### ISSUE TITLE
SSH connection failed when using public key + Yubikey 2FA

### ISSUE THREAD

**Issue by svintus** [Sequel-Ace/Sequel-Ace#339] opened 2020-09-03 21:11 UTC
- Sequel Ace Version: 2.1.7
- macOS Version: 11.0 Beta (20A5354i)
- MySQL Version: 5.7

**Description**
I'm trying to migrate from SequelPro and I'm getting the dreaded "SSH connection failed" dialog. My bastion host uses a combination of public key auth + Yubico PAM 2FA. Normally, ssh will ask for password after validating the public key. SequelPro handles this correctly, but SequelAce fails with `read_passphrase: can't open /dev/tty: Device not configured`, I'm assuming due to Sandbox restrictions. Is there a way around this? The full ssh debug log is below.

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes.

**Additional Context**

    Used command:  /usr/bin/ssh -v -N -S none -o ControlMaster=no -o ExitOnForwardFailure=yes -o ConnectTimeout=10 -o NumberOfPasswordPrompts=3 -o UserKnownHostsFile=/Users/ivan/Library/Containers/com.sequel-ace.sequel-ace/Data/.keys/ssh_known_hosts_strict -F /Users/ivan/.ssh/config -o TCPKeepAlive=no -o ServerAliveInterval=60 -o ServerAliveCountMax=1 X.X.X.X -L 52973:Y.Y.Y.Y:3306

    OpenSSH_8.1p1, LibreSSL 2.7.3
    debug1: Reading configuration data /Users/ivan/.ssh/config
    debug1: /Users/ivan/.ssh/config line 1: Applying options for *
    debug1: Connecting to X.X.X.X [XXXX] port 22.
    debug1: fd 3 clearing O_NONBLOCK
    debug1: Connection established.
    load pubkey "/Users/ivan/.ssh/id_rsa": Operation not permitted
    debug1: identity file /Users/ivan/.ssh/id_rsa type -1
    debug1: identity file /Users/ivan/.ssh/id_rsa-cert type -1
    debug1: identity file /Users/ivan/.ssh/id_dsa type -1
    debug1: identity file /Users/ivan/.ssh/id_dsa-cert type -1
    debug1: identity file /Users/ivan/.ssh/id_ecdsa type -1
    debug1: identity file /Users/ivan/.ssh/id_ecdsa-cert type -1
    debug1: identity file /Users/ivan/.ssh/id_ed25519 type -1
    debug1: identity file /Users/ivan/.ssh/id_ed25519-cert type -1
    debug1: identity file /Users/ivan/.ssh/id_xmss type -1
    debug1: identity file /Users/ivan/.ssh/id_xmss-cert type -1
    debug1: Local version string SSH-2.0-OpenSSH_8.1
    debug1: Remote protocol version 2.0, remote software version OpenSSH_5.3
    debug1: match: OpenSSH_5.3 pat OpenSSH_5* compat 0x0c000002
    debug1: Authenticating to X.X.X.X:22 as 'ivan'
    debug1: SSH2_MSG_KEXINIT sent
    debug1: SSH2_MSG_KEXINIT received
    debug1: kex: algorithm: diffie-hellman-group-exchange-sha256
    debug1: kex: host key algorithm: ssh-rsa
    debug1: kex: server->client cipher: aes128-ctr MAC: hmac-sha2-256 compression: none
    debug1: kex: client->server cipher: aes128-ctr MAC: hmac-sha2-256 compression: none
    debug1: SSH2_MSG_KEX_DH_GEX_REQUEST(2048<8192<8192) sent
    debug1: got SSH2_MSG_KEX_DH_GEX_GROUP
    debug1: SSH2_MSG_KEX_DH_GEX_INIT sent
    debug1: got SSH2_MSG_KEX_DH_GEX_REPLY
    debug1: Server host key: ssh-rsa SHA256:hpmKlDVAAorXqNINZBQt9sUPSBDwXvKKyjf1dgn3BDI
    debug1: Host 'X.X.X.X' is known and matches the RSA host key.
    debug1: Found key in /Users/ivan/Library/Containers/com.sequel-ace.sequel-ace/Data/.keys/ssh_known_hosts_strict:1
    debug1: rekey out after 4294967296 blocks
    debug1: SSH2_MSG_NEWKEYS sent
    debug1: expecting SSH2_MSG_NEWKEYS
    debug1: SSH2_MSG_NEWKEYS received
    debug1: rekey in after 4294967296 blocks
    debug1: pubkey_prepare: ssh_get_authentication_socket: Operation not permitted
    debug1: Will attempt key: /Users/ivan/.ssh/id_rsa
    debug1: Will attempt key: /Users/ivan/.ssh/id_dsa
    debug1: Will attempt key: /Users/ivan/.ssh/id_ecdsa
    debug1: Will attempt key: /Users/ivan/.ssh/id_ed25519
    debug1: Will attempt key: /Users/ivan/.ssh/id_xmss
    debug1: SSH2_MSG_SERVICE_ACCEPT received
    debug1: Authentications that can continue: publickey,password
    debug1: Next authentication method: publickey
    debug1: Trying private key: /Users/ivan/.ssh/id_rsa
    debug1: Remote: Adding to environment: SSH_USER=ivan
    debug1: Remote: Adding to environment: SSH_KEY=ivan-ivan
    Authenticated with partial success.
    debug1: Authentications that can continue: password
    debug1: Next authentication method: password
    debug1: read_passphrase: can't open /dev/tty: Device not configured
    debug1: Authentications that can continue: password
    Permission denied, please try again.
    debug1: read_passphrase: can't open /dev/tty: Device not configured
    debug1: Authentications that can continue: password
    Permission denied, please try again.
    debug1: read_passphrase: can't open /dev/tty: Device not configured
    debug1: Authentications that can continue: password
    debug1: No more authentication methods to try.
    ivan@X.X.X.X: Permission denied (password).

**Comment by stychos** [comment] 2020-09-03 22:33
Duplicate of https://github.com/Sequel-Ace/Sequel-Ace/issues/188

**Closed by stychos** 2020-09-03 22:33 UTC

**Comment by stychos** [comment] 2020-09-03 22:36
Unfortunately, this is because of sandboxing. Core team finds possible ways to resolve this.

**Comment by kdambekalns** [comment] 2020-11-02 06:21
Ah, didn't find this issue, since it's closed–shouldn't it be reopened until solved? At least it would be easier to find and could provide information on the status…

**Comment by Jason-Morcos** [comment] 2020-11-02 06:24
Oops, looked like the flagged the wrong issue. Correct issue is #188 @kdambekalns. This is a duplicate
