### ISSUE TITLE
Editing, inserting, deleting or sorting content table ascending/descending resets the horizontal/vertical position on Content View

### ISSUE THREAD

**Issue by salvor-hardin** [Sequel-Ace/Sequel-Ace#163] opened 2020-07-03 10:00 UTC
Sorting table ascending/descending moves the horizontal position on Content View (for wide tables with a lot of columns) to the left.

On the Content view, when you click over a column name to sort contents ascending/descending, Sequel Ace tends to shift the view horizontally to the left. 

In order to see the column that you've just clicked, the app requires to go to the slider bar to get the contents again back where the column we were applying the sorting filter. 
Very annoying and would be fantastic if the app kept the column on the horizontal position it is before clicking on the column name while sorting.

Thanks for considering.

**Comment by brysonm** [comment] 2020-07-03 21:41
I've noticed that Sequel Pro actually does preserve the scroll position when sorting, so this may be a bug. In Sequel Ace, it seems that both horizontal and vertical positions are reset.

**Comment by salvor-hardin** [comment] 2020-07-08 15:28
Correct, seems Sequel Pro has some method to get you almost to the same vertical position (far from ideal though) but Sequel Ace seems way off and positions you very very far away to the left of where the column has been sorted... hopefully this will be looked at. It is a pain to have to go searching for the column you've just sorted every time and a time waster!

**Comment by samuelbradshaw** [comment] 2020-07-15 02:41
I ran into this yesterday as well.

**Comment by mdriessen** [comment] 2020-07-19 22:36
This seems to be caused by this line which was added for FK navigation. If I just delete the line sorting works as expected and FK navigation resets the scrolling. I think this is a leftover for when the FK navigation scrolled to the correct line instead of using filters (which later was reverted because it didn't navigate to the correct page)? 

`
SPTableContent.m line 900
// Scroll to selection (if needed)
[[tableContentView onMainThread] scrollRowToVisible:[[tableContentView onMainThread] selectedRow]];
`

**Comment by Jason-Morcos** [comment] 2020-07-19 22:48
> This seems to be caused by this line which was added for FK navigation. If I just delete the line sorting works as expected and FK navigation resets the scrolling. I think this is a leftover for when the FK navigation scrolled to the correct line instead of using filters (which later was reverted because it didn't navigate to the correct page)?
> 
> `SPTableContent.m line 900 // Scroll to selection (if needed) [[tableContentView onMainThread] scrollRowToVisible:[[tableContentView onMainThread] selectedRow]];`

You're right, we did revert the scrolling behavior to opt for using filters to follow foreign keys. Looks like that line got lost in the revert! Feel free to PR and will review!

**Comment by salvor-hardin** [comment] 2020-08-11 08:18
Anything new on this one?
Useability is really poor with Sequel Ace due this nasty bug. Each touch on table contents resets the position and I have to figure out the horizontal and vertical positioning every single time... this one is almost a no-go for me TBH.

Should be figurable why the scroll moves after an edit and just prevent that to happen ? Thanks

**Comment by Jason-Morcos** [comment] 2020-08-18 05:01
> Anything new on this one?
> Useability is really poor with Sequel Ace due this nasty bug. Each touch on table contents resets the position and I have to figure out the horizontal and vertical positioning every single time... this one is almost a no-go for me TBH.
> 
> Should be figurable why the scroll moves after an edit and just prevent that to happen ? Thanks


See https://github.com/Sequel-Ace/Sequel-Ace/pull/259#issuecomment-668155389 PR
> I'm closing this PR as we haven't had activity in about two weeks and it seems perhaps a more nuanced approach may be needed. I would be happy to take a look at an approach that would keep a selected row in the view when sorted, but wouldn't shift horizontal position when sorting.

**Comment by alextheinsomniac** [comment] 2020-11-30 00:43
I use multiple MySql clients but I was very pleased to find a more stable version of Sequel Pro as I use it about an hour a day. 

This issue means I'm still using Sequel Pro despite 2/3 crashes a day. Scrolling back to the right every time I sort a column is a massive pain. If it can't be fixed in 2 please ensure it is in 3. Thanks

**Comment by salvor-hardin** [comment] 2020-12-01 09:34
> I use multiple MySql clients but I was very pleased to find a more stable version of Sequel Pro as I use it about an hour a day.
> 
> This issue means I'm still using Sequel Pro despite 2/3 crashes a day. Scrolling back to the right every time I sort a column is a massive pain. If it can't be fixed in 2 please ensure it is in 3. Thanks

I couldn't agree more. 

Even, in the worst case scenario if this cannot be fixed, at least a toggle to avoid scrolling all the way back to the first columns would be acceptable. Every single time the user needs to scroll back to where the edit was and the row and column position are lost, is too much of a pain TBH.

**Comment by Kaspik** [comment] 2020-12-01 10:24
The original reported issue (content doesn't stay on column we are sorting by) is fixed here: https://github.com/Sequel-Ace/Sequel-Ace/pull/575

About the content vertical scroll, I'm really not sure what is the best way to do here.
So in situation where we have limit 500 rows and table has 2 000 rows, user selects row 220. Then hit's any column name to sort by column name. Our selected row becomes row number 1 845 - so in ideal case, we would "search for everything (that would take forever), then split it by number of rows per page, then jump to page where our selected row exists, and display this page, then scroll to selected row".

But we don't live in ideal case world (just yet!), so what should actually happen? I fixed the "preserve offset" too at least (so you will stay on row 220, but it will be different content in the row of course) so it doesn't scroll to top always. But that's not ideal imho.

**Closed** 2020-12-01 10:25 UTC
Labels: Enhancement, Highest Priority

**Comment by salvor-hardin** [comment] 2020-12-01 10:26
Latest beta I’ve just downloaded and tested crashes right away when it tries to connect to any database, so I cannot confirm.

**Comment by Kaspik** [comment] 2020-12-01 10:30
The PR is still open for Beta 2 (and yes, fixes the Beta 1 crash) so give it couple of hours once I merge it. :)

**Comment by Kaspik** [comment] 2020-12-01 10:55
@salvor-hardin Released.

**Comment by alextheinsomniac** [comment] 2020-12-01 23:33
> The original reported issue (content doesn't stay on column we are sorting by) is fixed here: #575
> 
> About the content vertical scroll, I'm really not sure what is the best way to do here.
> So in situation where we have limit 500 rows and table has 2 000 rows, user selects row 220. Then hit's any column name to sort by column name. Our selected row becomes row number 1 845 - so in ideal case, we would "search for everything (that would take forever), then split it by number of rows per page, then jump to page where our selected row exists, and display this page, then scroll to selected row".
> 
> But we don't live in ideal case world (just yet!), so what should actually happen? I fixed the "preserve offset" too at least (so you will stay on row 220, but it will be different content in the row of course) so it doesn't scroll to top always. But that's not ideal imho.
> 
> If what happens is what you all expect, then cool. If not (re: vertical position), please open another issue. I'll close this one as it's fixed now. :)

Not that I would normally look to MS for guidance on usability but sorting on a column preserves the selected row number whilst the data selected moves out of sight. If the column position remains then I'm very happy! I will open a suggestion if I see a workable example of preserving the selected data whilst sorting. You're working on a genuinely useful application Thanks !
