### ISSUE TITLE
Why is 'Choose Database' so far over?

### ISSUE THREAD

**Issue by frumbert** [Sequel-Ace/Sequel-Ace#1161] opened 2021-07-07 01:44 UTC
[macOS 11.4, M1)
Why is the 'Choose database' dropdown so far over to the right of the header bar?

![Screen Shot 2021-07-07 at 11 33 31 am](https://user-images.githubusercontent.com/592257/124686931-53512200-df17-11eb-950c-395de21c0ba2.png)

Wouldn't it be more convenient to work where you already select tables and views?

![mod](https://user-images.githubusercontent.com/592257/124687543-74fed900-df18-11eb-87a3-0fe33b09b43d.jpg)

**Comment by Jason-Morcos** [comment] 2021-07-07 01:47
Duplicate of #562, #544, #534, #578, #595, and #727

This is a Big Sur thing and unfortunately something we have little to no control over! We're planning on making some future UI changes which may mitigate some of this issue.

**Closed** 2021-07-07 01:47 UTC
