### ISSUE TITLE
the v4.0.3 cause cpu very high load

### ISSUE THREAD

**Issue by neelie** [Sequel-Ace/Sequel-Ace#1625] opened 2022-11-19 04:08 UTC
![WX20221120-111928@2x](https://user-images.githubusercontent.com/497278/202881155-c55bdee6-5c8f-4acd-98a0-a62435f2b280.png)

Just open the application, the cpu fan is run fast, and the cpu load is in high level in the activity monitor.
It's okay in version 4.0.2

the macOS version is Ventura 13.0.1 (22A400).

**Comment by neelie** [comment] 2022-11-20 03:27
@Kaspik added some details about this issue. plz confirm is it a common issue.

**Comment by Kaspik** [comment] 2022-11-20 07:54
There ks no reason this should be happening based on the changelog and I can't repro. If others experience this as well we can reopen. ✌🏼

**Comment by skyblue** [comment] 2022-11-22 06:50
same OS version and same issue

**Comment by Nuranto** [comment] 2022-11-22 16:56
Same OS, and same issue here.

**Comment by tgzhafri** [comment] 2022-11-23 02:17
Same OS, and same issue here.
when use SSH connect to server with lots of database stored

**Comment by robjchan** [comment] 2022-11-23 07:49
I'm also experiencing this on Ventura 13.0.1 (22A400) and SSH, it persists even after I close all Windows/Tabs.

I could be mistaken but I'm sure I noticed high CPU on 4.0.2 and Ventura 13.0

**Comment by svetlozaraleksiev** [comment] 2022-11-23 08:56
Same issue.
Using MariaDB databases via SSH Tunnel

**Comment by Kaspik** [comment] 2022-11-23 09:07
Seems like an issue with Ventura and SSH? Can someone verify older Sequel Ace versions? (4.0.x, 3.8.0)

**Comment by happybunnyz** [comment] 2022-11-23 19:22
same issue here

Ventura Version 13.0 (22A380)
Sequel ace : Version 4.0.3 Build 20042

**Comment by wazum** [comment] 2022-11-24 08:48
Same issue here (250% CPU usage), the first time the fan has started on my M1 ;)

Ventura 13.0.1

Sequel Ace
Version 4.0.3
Build 20042

**Comment by Kaspik** [comment] 2022-11-24 09:06
We really need to get info if it's macOS, recent release, or what's the issue and where to start (I'm not using SSH and can't debug).

Can people try older version (3.8.0, 4.0.1/2)? Can someone report on non Ventura or older Ventura (13.0.0) please?

Thanks!

**Comment by happybunnyz** [comment] 2022-11-24 13:24
in my case, It was working  fine under Ventura 13.0.0 and Sequel Ace 4.0.2

**Comment by Kaspik** [comment] 2022-11-24 17:02
@happybunnyz  Can you install 4.0.2 back again from [release page](https://github.com/Sequel-Ace/Sequel-Ace/releases/tag/production%2F4.0.2-20041) to test if it immediately fixes the issue for you?

**Comment by happybunnyz** [comment] 2022-11-24 19:34
@Kaspik i got the same issue on 4.0.2 unfortunatly. 
its was stable for the first hour, but CPU when to 200% after export SQM dump (small file), and would not go slow after 5 min. I had to close Sequel Ace

Ill test 4.0.1 now

**Comment by happybunnyz** [comment] 2022-11-24 21:30
@Kaspik 2.0.1 is pretty stable. I did the same export as before, CPU was normal
I did severals big exports & imports as well, max CPU was at 22%, and went down right after it was finished

**Comment by Kaspik** [comment] 2022-11-24 21:45
There is basically no change in the app between 4.0.1 and 4.0.3... Is it happening only via SSH on the 4.0.3 for you?

**Comment by happybunnyz** [comment] 2022-11-24 22:05
when the issue occurred in 4.0.2, it was indeed via SSH
4.0.1, i used both SSH and local, still didn't have the issue. 

Ill keep testing it tonight

**Comment by tgzhafri** [comment] 2022-11-25 04:23
i used both 4.0.3 and 4.0.2, the high cpu issue occur when i open 2 connections tab localhost and ssh

**Comment by happybunnyz** [comment] 2022-11-25 13:46
still no issue with 4.0.1, same setup as @tgzhafri , one localhost and one ssh connections

**Comment by Jason-Morcos** [comment] 2022-11-25 20:29
Additionally, can folks try the new 4.0.4 beta and see if the SSL update @Kaspik did happened to fix these CPU issues? https://github.com/Sequel-Ace/Sequel-Ace/releases

**Comment by justRau** [comment] 2022-11-28 20:39
Had high CPU issue on 4.0.3 as well when using SSH mode.
Macbook Air M1 16 GB RAM.

Tried https://github.com/Sequel-Ace/Sequel-Ace/releases/download/beta%2F4.0.4-20043/Sequel-Ace-4.0.4-beta1.zip but issue persists – 100-200+ % of constant CPU usage.

CPU is OK when Sequel Ace is freshly opened or browsing Host=127.0.0.1 using TCP/IP mode.
CPU gets high when connected through SSH and stays high even after closing all windows with CMD+W, just the app is left open.

![image](https://user-images.githubusercontent.com/10882793/204376020-363593ed-e821-4697-ac8f-6282b6a387c7.png)

**Comment by martinstoehr** [comment] 2022-11-30 08:11
It's easy to reproduce:
Ventura 13.0.1
Sequel Ace 4.0.3 AppStore
MBP M1 16G

1. Open multiple (4+) tabs with ssh-connection to database
2. cpu-load stays at ~10-20%
3. Close a tab with mouse or ctrl-w
4. cpu-load raises +100% -> ~110%
5. Close another tab
6. cpu-load raises again +100% -> ~210%
7. Close another tab 
8. cpu-load raises again +100% ...

it goes up to 400%, then you can hear your cooling fan raising, if you didn't heard it before ;-)

**Comment by mato61** [comment] 2022-12-01 10:19
Mac pro 2018, Intel chip, version 11.6.7, sequel ace version 4.0.3, build 20042 - no problems with cpu
Mac pro 2020, M1, version 13.0.1 (22A400), sequel ace version 4.0.3, build 20042 - CPU 100% on idle, 200 - 500 when using

**Comment by martinstoehr** [comment] 2022-12-06 08:00
Tested 4 tabs w/ SSH-connections on Ventura 13.0.1:
4.0.3 -> same issue
4.0.2 -> same issue
4.0.1 -> no problems, cpu stays at 20-30%

**Comment by Kaspik** [comment] 2022-12-06 23:24
Thanks @DannyJJK , was able to connect and repro. The issue happens only with SSH connections, and is happening only on 4.x.x versions because of the memory leak fixes. It's another memory leak that causes `NSTask` (backing the SSHTunnel) to jump to 100% CPU when calling `terminate` and I'm not yet sure why.

If folks can in the meantime connect NOT via SSH, it won't be an issue.

**Comment by DannyJJK** [comment] 2022-12-06 23:45
@Kaspik do you think #1628 could be related to this? That issue seems to also be caused by terminating an SSH connection

**Comment by Kaspik** [comment] 2022-12-06 23:46
Yes, it's one and the dame problem.

**Comment by stychos** [comment] 2022-12-13 01:02
I can partially solve it for myself by changing `SPMainQSync` to `SPMainLoopAsync` of the `SPterminate` method of the `SPTaskAdditions.m`. Then it stalls the application instead of silently eating CPU.
But, the stall is happening only when closing the Structure tab, when closing table opened with the other tabs, e.g. Content, everything looks fine.
Don't know how it works and drawbacks of changing Sync to Async, would be happy if this can point someone to the solution.

**Comment by zacharyfreiberg** [comment] 2022-12-13 03:12
People (including myself) commented on a closed ticket about this too: https://github.com/Sequel-Ace/Sequel-Ace/issues/795

**Comment by Kaspik** [comment] 2022-12-13 18:54
Unfortunately I don't think there is a difference, but we are actively debugging this.

**Closed** 2022-12-15 00:41 UTC
Labels: Bug, Help wanted, Highest Priority

**Comment by Kaspik** [comment] 2022-12-15 08:58
Could folks here check the latest beta / RC and let me know if they see an improvement? 🙏🏼  There are still things to fix (memory wise), but CPU should be better.

**Comment by zacharyfreiberg** [comment] 2022-12-15 20:04
I've downloaded 4.0.4 now and am testing this. Currently no issues, I will let you know if I encounter this again. Thank you

**Comment by jaapdevries** [comment] 2022-12-15 20:33
> Tested 4 tabs w/ SSH-connections on Ventura 13.0.1: 4.0.3 -> same issue 4.0.2 -> same issue 4.0.1 -> no problems, cpu stays at 20-30%

Testing with 4.0.4 with 5 ssh connections: around 1% cpu in idle state, running queries etc. between 15-35% (large datasets) and cpu returns to 1% almost instantly when not doing anything.

**Comment by jaapdevries** [comment] 2022-12-15 21:22
@Kaspik no issues anymore on 4.0.4 with cpu load after running 1 hour+

**Comment by Kaspik** [comment] 2022-12-15 21:48
It would happen when you close some tab with SSH connection, but glad it seems to be working!

**Comment by zacharyfreiberg** [comment] 2022-12-15 22:19
No issues after a few hours of running, I've closed tabs with SSH connections

**Comment by stychos** [comment] 2022-12-15 23:14
> Could folks here check the latest beta / RC and let me know if they see an improvement? 🙏🏼 There are still things to fix (memory wise), but CPU should be better.

Sorry for disappointing, but it's still here. Everything fine when closing the tab with Content or any other view, but it still hangs whole app when closing a tab having SSH connection and opened with the Structure view. Must have another connection in other tab to reproduce.

**Comment by Kaspik** [comment] 2022-12-16 14:56
> > Could folks here check the latest beta / RC and let me know if they see an improvement? 🙏🏼 There are still things to fix (memory wise), but CPU should be better.
> 
> Sorry for disappointing, but it's still here. Everything fine when closing the tab with Content or any other view, but it still hangs whole app when closing a tab having SSH connection and opened with the Structure view. Must have another connection in other tab to reproduce.

I was able to repro the CPU, I'm not able to repro this. If you could debug it (and probably have separate issue than this if we can keep this closed), it would be great.

**Comment by Jiia** [comment] 2024-01-26 09:12
I'm running Macbook Pro M2 Max (Ventura) and for the first time ever heard the fans spin at max speed. It was Sequel Ace taking up 800% CPU, when I was just trying to enter the database connection settings and hadn't connected to any database yet.

Switched to Homebrew version and the CPU usage is still at 200-300% without any connections and sitting idle.

**Comment by felixpenrose** [comment] 2024-03-26 11:55
I've been running Ace on Ventura and now Sonoma (14.4) roughly for the past 3 months on a Macbook pro - M2 Pro.
Latest version from brew. Currently 4.0.13

It's been an on and off issue since day one for me. I'm also using SSH connections. I've not noticed the exact flow that causes the issue yet though, but I'll update if I can find the steps to reproduce on my set up.

**Comment by saliabbasraza** [comment] 2024-11-15 10:57
I am also facing the same issue. 
<img width="1090" alt="image" src="https://github.com/user-attachments/assets/8329c163-20b9-48f8-9c67-057a74de3940">
<img width="1097" alt="image" src="https://github.com/user-attachments/assets/38a7b943-9d01-4b75-b02b-854e7058761c">

Version 4.1.5
Build 20077
<img width="598" alt="image" src="https://github.com/user-attachments/assets/29ebefc1-e9db-4aba-b841-b32036376a3a">

<img width="275" alt="image" src="https://github.com/user-attachments/assets/07d9ad36-36f2-4bd8-8e39-a3a50de18d1d">

**Comment by jscheker** [comment] 2024-11-26 15:33
macpro, Sonoma, Sequoia. App version 4.1.5 - the same issue
