### ISSUE TITLE
When doing action like selecting table or filtering table sequel-ace window is going foreground

### ISSUE THREAD

**Issue by roeerokah** [Sequel-Ace/Sequel-Ace#1689] opened 2023-01-22 13:55 UTC
Version 4.0.5
Build 20046
- Sequel Ace Version (including build number):
- Sequel Ace Source (App Store/GitHub/Homebrew): App store
- macOS Version:13.1 (22C65)
- Processor Type (Intel/Apple):intel
- MySQL Version:8.0.23
- macOS Localization:Israel

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?** yes

**Description**
When doing action like selecting table or filtering table sequel-ace window is going foreground
**Steps To Reproduce**
1. have more than one window on your desktop (I have chrome)
2. Open sequel ace
3. go to a table with content (most probably it happen now, if not)
4. use the UI to filter for a value, press enter
5. sequel ace is now on the background and you see the chrome window in front of you

**Expected Behaviour**
sequel ace will still be visible and focus and not in the foreground

**Comment by Jason-Morcos** [comment] 2023-01-22 18:23
Duplicate of #1618

**Closed** 2023-01-22 18:23 UTC
