### ISSUE TITLE
[Feature request] [Keyboard shortcut] Go back / go forward selecting tables

### ISSUE THREAD

**Issue by fulldecent** [Sequel-Ace/Sequel-Ace#1707] opened 2023-02-14 15:20 UTC
Requesting a couple keyboard shortcuts, please:

<kbd>Command</kbd>-<kbd>[</kbd> go to previously selected database table
<kbd>Command</kbd>-<kbd>]</kbd> go to next selected database table

This will work just like a web browser.

If you are hopping around to reference table schemas, maybe your fingers have already typed this expecting it to do that.

**Comment by Jason-Morcos** [comment] 2023-02-15 03:29
This seems like a duplicate of https://github.com/Sequel-Ace/Sequel-Ace/issues/1468

**Closed by Jason-Morcos** 2023-02-15 03:29 UTC
Labels: Low priority
