### ISSUE TITLE
Passwords vanishing

### ISSUE THREAD

**Issue by nofue** [Sequel-Ace/Sequel-Ace#1042] opened 2021-04-09 16:51 UTC
- Sequel Ace Version (including build number): 3.3.0 - 3026
- Sequel Ace Source: App Store
- macOS Version: 11.2.3
- Processor Type: Intel
- MySQL Version: mysql  Ver 15.1 Distrib 10.3.27-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
- macOS Localization: DE-DE

**Is Issue Present in Latest upgrade through "upgrade" within Sequel Ace **

**Description**
Entering the database password first and the MySQL Server IP later, removes the password from the field in the "connection settings dialogue -- SSH connection setup" (right half of window after Cmd+N) for the lack of a proper term.

**Steps To Reproduce**
Cmd+N
Enter database password
Enter server IP
-> database password has gone blank

**Expected Behaviour**

The database password should remain unchanged by whatever operation on a different field in the dialogue. 

**Additional Context**
The same happened with the SSH password in the same panel.

**Comment by Kaspik** [comment] 2021-04-09 16:59
Duplicate of https://github.com/Sequel-Ace/Sequel-Ace/issues/1037 - expected security behavior.

**Closed by Kaspik** 2021-04-09 16:59 UTC
