### ISSUE TITLE
Edit cell as a spreadsheet with an email address in the field

### ISSUE THREAD

**Issue by vbrodrigo** [Sequel-Ace/Sequel-Ace#1189] opened 2021-08-09 02:45 UTC
- Sequel Ace Version (including build number): 3.4.0 / Build 3038
- Sequel Ace Source (App Store/GitHub/Homebrew): GitHub
- macOS Version: Big Sur 11.5.1
- Processor Type (Intel/Apple): Apple M1
- MySQL Version: 8
- macOS Localization: Brasil

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes

**Description**
When I try edit a VARCHAR field, which internal content is an email address (with @), I can't do it as a spreadsheet and then it opens a pop-up (like TEXT field).

**Steps To Reproduce**
1. Create a table with a VARCHAR field 
2. Insert a line and type an email address 
3. Try to edit the field.

**Expected Behaviour**
Be possible to edit as a spreadsheet

**Comment by Jason-Morcos** [comment] 2021-08-20 19:07
I believe this is a duplicate of #1096 and should probably be handled as part of that issue

**Closed by Jason-Morcos** 2021-08-20 19:07 UTC
