### ISSUE TITLE
Window resizing quirky

### ISSUE THREAD

**Issue by nofue** [Sequel-Ace/Sequel-Ace#1043] opened 2021-04-09 16:54 UTC
- Sequel Ace Version (including build number): 3.3.0 - 3026
- Sequel Ace Source: App Store
- macOS Version: 11.2.3
- Processor Type: Intel
- MySQL Version: mysql  Ver 15.1 Distrib 10.3.27-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
- macOS Localization: DE-DE

**Is Issue Present in Latest upgrade through "upgrade" within Sequel Ace **

**Description**
Resizing the Settings window of any given favourite feels clunky. The headline "Enter connection details below, or choose a favorite" goes on top of the fields when the window get's really small.

**Steps To Reproduce**
1. Just try to resize the configuration dialogue window, preferably with SSH settings (as they are the highest).

**Expected Behaviour**
Smooth resizing as with any other window would be nice.

**Comment by Kaspik** [comment] 2021-04-09 17:02
I believe this is duplicate of https://github.com/Sequel-Ace/Sequel-Ace/issues/997 - connections window has some UI issues due to manual layout / framing

**Closed by Kaspik** 2021-04-09 17:02 UTC
