### ISSUE TITLE
add menu check update new version

### ISSUE THREAD

**Issue by maprangsoft** [Sequel-Ace/Sequel-Ace#805] opened 2021-01-19 02:29 UTC
Many times that app store not notify have new version if sequel ace have menu check update would be very nice.

**Comment by Kaspik** [comment] 2021-01-20 08:44
I would say duplicate of https://github.com/Sequel-Ace/Sequel-Ace/issues/85, https://github.com/Sequel-Ace/Sequel-Ace/issues/666 and https://github.com/Sequel-Ace/Sequel-Ace/issues/735.

Do you have auto-updates enabled? If so, after phased rollout is done, it should update in about 2 days if conditions are met.

In the meantime I already suggested this to someone else in older ticket - setup IFTTT notification for GitHub releases if you want! :)
https://rschu.me/github-release-notification-via-ifttt-2346f3a71f3b

or

https://ifttt.com/applets/133919-github-release-notification

**Comment by jamesstout** [comment] 2021-02-10 23:01
Had a go at this: https://github.com/Sequel-Ace/Sequel-Ace/tree/check-for-update

@Jason-Morcos @Kaspik

**Comment by Jason-Morcos** [comment] 2021-02-10 23:19
> Had a go at this: https://github.com/Sequel-Ace/Sequel-Ace/tree/check-for-update
> 
> @Jason-Morcos @Kaspik

Looking at the code looks cool and looks like it would work, wanna PR and we can test it in the next release cycle?

**Closed** 2021-02-19 07:40 UTC
Labels: Feature Request, Fixed & Pending Release, Low priority, PR Welcome
