### ISSUE TITLE
Query: inconsistent "Run Current" query behaviour

### ISSUE THREAD

**Issue by kelvinj** [Sequel-Ace/Sequel-Ace#645] opened 2020-12-17 11:46 UTC
- Sequel Ace Version: 3.0.0 (Build 3007)
- macOS Version: 10.15.7
- Processor Type (Intel/Apple): Intel

**Description**
When using the query editor, if I have write a query, I can "Run Current" usinc Command-R.

However, this option is only available if I don't move my cursor. Upon moving the cursor, the option to "Run Current" disappears, and I can no longer run the current query.

**Steps To Reproduce**
1. Write a query and run it
2. Move the cursor
3. "Run Query" option disappears
4. The current query is no longer highlighted

**Expected Behaviour**

I expect to always be able to run a query if my cursor is placed within a query.

I expect that the current query is always highlighted

**Comment by Kaspik** [comment] 2020-12-17 11:47
Duplicate of https://github.com/Sequel-Ace/Sequel-Ace/issues/640

**Closed by Kaspik** 2020-12-17 11:47 UTC
