### ISSUE TITLE
The sidebar gets smaller every time you open a new tab

### ISSUE THREAD

**Issue by coredumperror** [Sequel-Ace/Sequel-Ace#112] opened 2020-06-26 00:50 UTC
- Sequel Ace Version: 2.0.2
- macOS Version: Mojave

**Description**
Whenever you open a new tab and the Favorites listing is displayed, the sidebar gets smaller than it was the previous time you saw it.

**Steps To Reproduce**
1. Widen the sidebar a lot.
2. Open multiple tabs in a row.
3. The sidebar gets smaller on every new tab, until it can't get any smaller.

**Expected Behavior**
The sidebar should stay the same width unless the user explicitly resizes it.

**Additional Context**
The sidebar seems to share sizes on both the Favorites list and the table listing when you're actually looking at a DB. This should probably not be the case, as table name lengths will be different from one DB to the next, and it would rarely if ever be desirable for it to be the same width as the favorites list. So saving the sidebar width in the DB view on a per-DB basis would also be nice.

**Comment by gboudreau** [comment] 2020-06-26 01:31
Duplicate of #45.

**Closed by gboudreau** 2020-06-26 01:31 UTC
