### ISSUE TITLE
Update from 4.0.1 to 4.0.3 keeps aborting

### ISSUE THREAD

**Issue by LiroyvH** [Sequel-Ace/Sequel-Ace#1626] opened 2022-11-22 00:25 UTC
- Sequel Ace Version (including build number): 4.0.1 20039
- Sequel Ace Source (App Store/GitHub/Homebrew): Pretty sure its from GitHub, been a long time since install.
- macOS Version: Ventura
- Processor Type (Intel/Apple): Apple
- MySQL Version: -
- macOS Localization: Dutch

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Not sure I should try this, considering there wouldn't be any debugging possible once this version is expunged from my Mac? I would've if I had found any other open/closed issue mentioning this, but since it doesn't: I won't try this unless you really want me to, but then I can no longer gather information from the failing 4.0.1 install. 

**Description**
Sequel Ace prompts for updates, downloads it and then the update window disappears. I can re-do this endlessly by manually conjuring it by doing "Check for updates". It will keep saying there's an update, it'll download it and then the window goes away and it never executes the update.

Of course I can manually update OR go to the beta version, but I couldn't find a bug report on this (no open/closed issue mentioning updates, unless I searched wrong perhaps) and figured the devs may wish to get more info/debug in case this happens to more people for whatever reason when trying to download 4.0.3 through the app itself. 

**Steps To Reproduce**
1. Check for updates
2. See it disappear after download

**Expected Behaviour**
It should prompt to "Install and relaunch" or something similar, instead the pop-up with the update progression (download) just disappears the moment it is done downloading 4.0.3. 

**Related Issues**
I ran a search (https://github.com/Sequel-Ace/Sequel-Ace/issues?q=is%3Aissue+update) but could not find anything relevant.

**Additional Context**
1.) It offers to update: "Version 4.0.3 (20042) is available. You are currently running 4.0.1 (20039)". Then I click "Download". A new window appears showing the download progression. Normally this then turns in to "Install and relaunch", but instead the pop-up disappears and the update process stops. I can re-launch it by going to File -> Check for updates. And the same thing will happen, over and over again.
2.) I do not have any crashlogs, as nothing is crashing. I couldn't find a relevant log for the update either. If you need any files, please do let me know including the file location and I'll gladly provide them. 
3.) I don't think there's any other relevant context to be mentioned.

**Comment by Jason-Morcos** [comment] 2022-11-27 20:08
Cannot reproduce and no similar issue reports so closing at this time.
Probably the download got corrupted and you're in some sort of odd loop? I would manually update to 4.0.3. Definitely let us know if you have the same issues trying to update to 4.0.4!

**Closed by Jason-Morcos** 2022-11-27 20:08 UTC
