### ISSUE TITLE
Flexibile Space in toolbar not working

### ISSUE THREAD

**Issue by cappadaan** [Sequel-Ace/Sequel-Ace#555] opened 2020-11-26 12:05 UTC
V 2.3.1

I try to use the Flexibile Space.
- drag in toolbar
- try to change the width but it shows as a vertical line, there seems to be no way to change its dimensions

<img width="102" alt="Screenshot 2020-11-26 at 13 03 08" src="https://user-images.githubusercontent.com/25279400/100348870-d7d5dc80-2fe7-11eb-8fa8-0298d8774cc1.png">

**Comment by Kaspik** [comment] 2020-11-26 12:21
Duplicate of https://github.com/Sequel-Ace/Sequel-Ace/issues/544

This is a Big Sur thing. Version 3.0.0 will have more updates in the Big Sur UI.

**Closed by Kaspik** 2020-11-26 12:21 UTC

**Comment by cappadaan** [comment] 2020-11-26 12:23
you should leave these issues open so everyone can search for them and you avoid these duplicate issue.

**Comment by Kaspik** [comment] 2020-11-26 13:07
Or you could search for issues regardless of if they are open or closed. :) Going through everything retrospectively after release is even more work for us.

**Comment by cappadaan** [comment] 2020-11-26 13:09
whats the logic behind searching in closed issues for an open bug? But its up 2 you.

**Comment by Kaspik** [comment] 2020-11-26 13:14
Well there is multiple reasons:
- v2.3.1 is not the latest release, so it could have been closed anyways in 2.3.2 for example - if user is not on the latest version, he should always search through closed issues as well
- open issue means it's "todo to get fixed" for contributors and people that want to contribute nd collaborate - which is not true in this case, because it's already fixed on master (well not in this case, there is nothing to fix on our side 😄 )
- it's pretty common technique/flow in open source - have you ever seen for example https://swift.org to keep issues open after they are fixed, but not released yet? :)

Anyways thanks for suggestions, we will evaluate this later after the major update is released.
