### ISSUE TITLE
Option to put new toolbar left justified

### ISSUE THREAD

**Issue by ktwbc** [Sequel-Ace/Sequel-Ace#618] opened 2020-12-12 22:34 UTC
The new toolbar which is more Big Sur style on the top is fine except that on larger displays, because the toolbar is right justified it creates a massive space to have to move your mouse cursor from the tables and other things you generally work on on the left side, with the display that is on the right. On laptop screens this isn't as noticeable but larger displays this is very annoying. It would be nice to have a preference to use a left justified menu and put the db selector back on the upper left too

![Screen Shot 2020-12-12 at 4 26 24 PM](https://user-images.githubusercontent.com/624611/101996437-f00c5380-3c97-11eb-8d8e-466c3996543f.png)

**Comment by Jason-Morcos** [comment] 2020-12-12 23:05
I don't believe we have this option for left-justified anymore in Big Sur. @Kaspik is this some option we could even provide or is it technically precluded by Big Sur?

**Comment by Kaspik** [comment] 2020-12-12 23:06
Duplicate of #562, #544, #534, #578 and #595

Please check threads there. (it's slightly updated in 3.0.0 follows Big Sur preferences currently)

**Closed by Kaspik** 2020-12-12 23:06 UTC

**Comment by Kaspik** [comment] 2020-12-12 23:08
It will be "achieve-able" once we migrate to Auto Layout, storyboards and we implement correct sidebar - you can then pin things following the sidebar specs. Unfortunately that's couple of months until we will be able to do it. 😞 

iirc, there are shortcuts to switch the views (content, structure, ...) - it might help you instead of moving the cursor in the meantime. :)

**Comment by ktwbc** [comment] 2020-12-12 23:10
ok. I did search for the word “toolbar” first to find duplicates but because all the other items you referenced are closed, they didn’t come up on the default search (which is just for open items). Maybe leave one pinned open but not actionable so it shows up to avoid duplicates?

**Comment by Kaspik** [comment] 2020-12-13 09:25
Yeah we talked about this too. We are also closing fixed issues, so I recommend searching always in closed as well - it could have been fixed on master in the meantime. :) Thanks for suggestion tho.
