### ISSUE TITLE
Connections don't get closed

### ISSUE THREAD

**Issue by nofue** [Sequel-Ace/Sequel-Ace#1045] opened 2021-04-09 18:13 UTC
- Sequel Ace Version (including build number): 3.3.0 - 3026
- Sequel Ace Source: App Store
- macOS Version: 11.2.3
- Processor Type: Intel
- MySQL Version: mysql  Ver 15.1 Distrib 10.3.27-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
- macOS Localization: DE-DE

**Is Issue Present in Latest upgrade through "upgrade" within Sequel Ace **

**Description**
When opening a lot of connections and closing the connection window immediately seems to leave the connection open. As there is no dedicated "Close connection" functionality, I think closing the window either through the menu or by pressong Cmd+W should also close the connection to the database. 

Anyway, after inspecting some 20 databases, one after the other, Sequel Ace came up with an error (sort of "MySQL says: no file handles left" or the like.) Restarting

service mysql restart

repaired the issue. 

**Expected Behaviour**
As an admin, I have a lot of databases to inspect, and as a developer I deal with even more databases on several machines. It would be nice if the connections closes themselves when closing the connection window.

**Comment by Kaspik** [comment] 2021-04-09 18:15
Unfortunately duplicate of https://github.com/Sequel-Ace/Sequel-Ace/issues/811 - we are aware of this memory leak... were not able to fix it yet 😞

**Closed by Kaspik** 2021-04-09 18:15 UTC
