### ISSUE TITLE
please enhance the speed of auto complete in query~

### ISSUE THREAD

**Issue by ysnows** [Sequel-Ace/Sequel-Ace#474] opened 2020-11-09 23:58 UTC
please enhance the speed of auto prompt in query~

-- thanks for your wonderful work

**Comment by jamesstout** [comment] 2020-11-10 04:01
related: #269 #366

I've made a start: https://github.com/Sequel-Ace/Sequel-Ace/commits/improve-query-history-search

**Comment by Kaspik** [comment] 2020-11-17 21:54
Duplicate of https://github.com/Sequel-Ace/Sequel-Ace/issues/269 as mentioned, I'll close this one. :)

**Closed by Kaspik** 2020-11-17 21:54 UTC
Labels: Enhancement, PR Welcome

**Comment by Kaspik** [comment] 2020-11-27 22:12
Moving to Done as this has been improved.
