### ISSUE TITLE
Unable to reconnect to DB after sleep

### ISSUE THREAD

**Issue by tom10271** [Sequel-Ace/Sequel-Ace#1091] opened 2021-05-12 02:54 UTC
- Sequel Ace Version (including build number): Version 3.3.1 Build 3028
- Sequel Ace Source (App Store/GitHub/Homebrew): GitHub
- macOS Version: 10.15.2 (19C57)
- Processor Type (Intel/Apple): Intel
- MySQL Version: MariaDB 10.5 and 10.6
- macOS Localization: en_US

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

Yes in latest version

**Description**

**Steps To Reproduce**
1. Connect to DB
2. Sleep your Mac
3. Start using your Mac next morning
4. Sequel Ace prompts for reconnection, but it is just not working
5. Pathetically close the connection and restart a new one manually

**Expected Behaviour**

Works, of course.

**Related Issues**

**Additional Context**

**Comment by rickmills** [comment] 2021-05-14 09:54
The reconnect issue has been around since Sequel Pro I think. Even if you leave the app open for a couple of hours then try to switch tables it'll just completely lock up and become inactive for a few minutes, then will pop up with the reconnect window.

When you click reconnect the wheel spins but it's not actually doing anything (I tailed the log on my sql server, it never even attempted to connect to it).

With the sleep thing I've often found coming back to it the apps just gone totally unresponsive and has to be force quit.

**Comment by szepczynski** [comment] 2021-05-19 08:50
> The reconnect issue has been around since Sequel Pro I think. Even if you leave the app open for a couple of hours then try to switch tables it'll just completely lock up and become inactive for a few minutes, then will pop up with the reconnect window.
> 
> When you click reconnect the wheel spins but it's not actually doing anything (I tailed the log on my sql server, it never even attempted to connect to it).
> 
> With the sleep thing I've often found coming back to it the apps just gone totally unresponsive and has to be force quit.

In sequel pro (latest stable build) this function works for me. In sequel ace I have issue with unable to reconnect

**Comment by Jason-Morcos** [comment] 2021-05-20 05:20
I believe this is a duplicate of of #658. Let's consolidate discussion to there.

This is definitely a serious bug and we're aware of it, but fixing it has proved challenging. Ace is the _sequel_ of Sequel Pro which is itself a sequel of CocoaMysql. The app basically has been retrofitted over and over as the years passed. To really solve this issue, we may need to significantly rewrite/re-think connections.

**Closed by Jason-Morcos** 2021-05-20 05:20 UTC

**Comment by tom10271** [comment] 2021-05-20 05:23
Can we at least have query written saved and restored? Every time connection lost queries are all gone and query history is not easy to use

**Comment by Jason-Morcos** [comment] 2021-05-20 06:09
I believe this functionality was already implemented, @tom10271? #464 
@jamesstout or @Kaspik may know better than me

**Comment by tom10271** [comment] 2021-09-27 03:14
Can we allow user to disable auto reconnect? When you cannot connect again, just don't reconnect. You cleared all my SQLs and wasted by ~15 seconds on failing to reconnect. I am killing the application with Activity Monitor and restart the application which is even faster.

**Comment by tom10271** [comment] 2021-09-27 03:14
> I believe this functionality was already implemented, @tom10271? #464
> @jamesstout or @Kaspik may know better than me

I don't think so and I continuously upgrading version already.

**Comment by Jason-Morcos** [comment] 2021-09-27 05:55
<img width="879" alt="Screen Shot 2021-09-26 at 22 54 18" src="https://user-images.githubusercontent.com/10710367/134852172-a2aa9e75-7b89-432b-b0fe-7b70d7fd0419.png">
