### ISSUE TITLE
Can no longer select individual cells of the results list for custom queries MAS 3.0.1 (3008) / Catalina

### ISSUE THREAD

**Issue by Tillman-Z** [Sequel-Ace/Sequel-Ace#671] opened 2020-12-22 08:36 UTC
Run any multi table select query with multiple return params per row or call a stored proc with similar kind of output.

Expected behavior:
I should be able (and was until the update) to double click individual cells to copy / paste content.
In case of TEXT cells I should get a popup window showing the entire content of that TEXT cell.

Current behavior:
I cannot select cells but only rows. Sometimes I manage to at least get the popup window to appear for a TEXT column cell but this is also working very inconsistently. 

This regression is unfortunately makes it impossible for me to continue to use SequelAce as much as I love it.
I will be back immediately when this is fixed!

**Comment by Jason-Morcos** [comment] 2020-12-22 08:38
In the meantime, you can download a previous release manually from GitHub to use until the issue is fixed! 

https://github.com/Sequel-Ace/Sequel-Ace/releases

**Comment by Tillman-Z** [comment] 2020-12-22 08:41
Thanks Jason! I just installed build 2121 and it's working nicely again! :)

**Comment by Kaspik** [comment] 2020-12-22 14:18
Hey @Tillman-Z - just testing this, is this the behavior you are not seeing?

![2020-12-22 15 15 49](https://user-images.githubusercontent.com/7204168/102897789-dd98d380-4468-11eb-8650-9f990554d30b.gif)

I'm able to double-click any of the cells in any row and column. By any chance, did you update from older app, or did clean install?

**Comment by Tillman-Z** [comment] 2020-12-22 14:24
It was a MAS auto-update and YES that would be exactly the kind of behavior I would have expected. :)
Only it's not allowing me to select individual cells but only the entire rows.

(having had issued with the current row auto-recognition as well but that seems to be tracked in another issue ticket)

Now using the 2.3.2 (2121) behavior of the results grid is it usually was.

Best,

Tillman

**Comment by Kaspik** [comment] 2020-12-22 14:26
I would be curious if complete wipeout and clean install of 3.0.1 would fix it (we saw some things got fixed by this - it would mean we really need to find out why 😄 But make sure to export/save all your favorites) if you are able to try it out for us. :) Otherwise I', not sure how could I track or debug this...

**Comment by Tillman-Z** [comment] 2020-12-22 14:28
I am happy to try and report back once the #640 is fixed.

**Closed** 2020-12-23 09:59 UTC
Labels: Bug

**Comment by Tillman-Z** [comment] 2020-12-29 11:56
I can confirm that a fresh installation of build 3010 has solved the issue for me.
