### ISSUE TITLE
Return header design back

### ISSUE THREAD

**Issue by megaezz** [Sequel-Ace/Sequel-Ace#595] opened 2020-12-06 23:41 UTC
Please return back design of application header. Now it's so ugly and not friendly. Or please give opportunity to change this option in settings.

**Comment by Jason-Morcos** [comment] 2020-12-07 00:10
This is due to Big Sur and is outside of our control.

Duplicate of #562, #544 and #534

**Closed** 2020-12-07 00:11 UTC

**Comment by megaezz** [comment] 2020-12-07 00:13
> This is due to Big Sur and is outside of our control. There will be some UI changes coming in release 3.0.0 that will make things look a little better.
> 
> Duplicate of #562, #544 and #534

Thank you for explanation. Sorry to hear that.
