### ISSUE TITLE
Strict Host Checking is Disabled

### ISSUE THREAD

**Issue by Jason-Morcos** [Sequel-Ace/Sequel-Ace#13] opened 2020-06-13 18:13 UTC
Currently, strict host checking is disabled to allow sandboxing the app. In an ideal world, the helper should be able to turn around and prompt the user to confirm the identity of the remote key so that we can strictly check keys always.

**Comment by Jason-Morcos** [comment] 2020-06-13 18:15
@gboudreau, @jamesstout, @clayreimann
Issue to discuss strict host checking disabled (which was done to allow sandboxing)

**Comment by gboudreau** [comment] 2020-06-19 12:23
@Jason-Morcos I think this was closed by error, when you merged my PR that was reverted..?

**Comment by Jason-Morcos** [comment] 2020-06-21 18:46
@gboudreau Are you certain that strict host checking worked with sandbox off? I've been playing with sandbox off on both the helper and app, fully cleaned, and still not getting prompted to accept a host with strict host checking=yes. I had to specify a new known hosts file of course so it didn't use the old one that already knew my hosts.
I'm getting `The SSH Tunnel has unexpectedly closed.` every time, which to me suggests there me be something else broken and not just sandbox!

**Comment by gboudreau** [comment] 2020-06-21 18:48
Try using this commit: 141a3f8252ecd296d50036f429a57c2efa68ef40
I think something else broke after that commit, because I can't seem to make it work using the dev branch either...

**Comment by Jason-Morcos** [comment] 2020-06-21 18:51
You're right. It _does_ work back at that commit. So something else did get broken, probably by me

**Comment by Jason-Morcos** [comment] 2020-06-21 18:53
Was it commit https://github.com/Sequel-Ace/Sequel-Ace/commit/cd4f3602bd0fcd68971b545910ee25d75d71b74e that broke it?

**Comment by Jason-Morcos** [comment] 2020-06-21 19:31
I tried reverted that commit and it still didn't work. Can't seem to figure out what broke it (more)!

**Comment by Jason-Morcos** [comment] 2020-06-21 19:56
Well I figured something big out! Turns out the issue was a build setting `CODE_SIGN_INJECT_BASE_ENTITLEMENTS`! This is what was causing the helper to crash when sandbox was enabled. https://developer.apple.com/forums/thread/112800

I committed that to dev, however whatever broke between https://github.com/Sequel-Ace/Sequel-Ace/commit/141a3f8252ecd296d50036f429a57c2efa68ef40 and latest dev means currently the app can't find the helper for some reason

**Comment by gboudreau** [comment] 2020-06-21 19:59
Good catch! I'll use for bisect when I get back home to find when it
stopped working. Should be easy enough to find from there !

Le dim. 21 juin 2020 15 h 56, Jason Morcos <notifications@github.com> a
écrit :

**Comment by Jason-Morcos** [comment] 2020-06-21 20:13
I think I have it fixed for real!! On dev. It didn't like strict host checking being manually set to yes. Checkout dev and let me know, I think we might have this issue fixed!!

**Comment by Jason-Morcos** [comment] 2020-06-21 20:23
Made an RC to make it easier to test! https://github.com/Sequel-Ace/Sequel-Ace/releases/tag/2.0.2-rc1

**Comment by gboudreau** [comment] 2020-06-21 22:21
I can confirm 2.0.2 (I tested using the dev branch really) fixes all the issues with the Assistant; it now correctly prompts to accept new SSH host keys, uses the user-provided password to connect, if any, and prompts for passwords as needed, including the password that might be required to use an encrypted SSH key.

**Closed** 2020-06-22 23:53 UTC
Labels: Fixed & Pending Release, Highest Priority, enhancement
