### ISSUE TITLE
Socket connection failed!

### ISSUE THREAD

**Issue by steviepitman** [Sequel-Ace/Sequel-Ace#292] opened 2020-08-11 08:59 UTC
- Sequel Ace Version: 2.1.5 (2073)
- macOS Version: 10.15.6
- MySQL Version: 5.7.27

I've migrated to Sequel Ace from Sequel Pro, following your migration guide. Sequel Pro worked fine, but in Sequel Ace I get the socket error (see msg below). I know I've got the correct passwords (as I've checked these in 3 other locations: Keychain, Sequel Pro and phpMyAdmin). 

You might suggest this is a configuration issue, but given I've made zero changed to my laptop, mysql and accounts I consider this to be a 'bug' (i.e. the only thing that changed was trying to open the identical items in Sequel Ace).

Error message:

Unable to connect via the socket, or the request timed out.
Double-check that the socket path is correct and that you have the necessary privileges, and that the server is running.
MySQL said: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (1)

**Comment by stychos** [comment] 2020-08-11 10:44
Duplicate of #113, this is sandboxing issue. As a workaround, you can create a socket in `~/Library/Containers/com.sequel-ace.sequel-ace/Data` and then you'll be able to connect to it.

**Closed by stychos** 2020-08-11 10:44 UTC

**Comment by steviepitman** [comment] 2020-08-11 11:18
Thank you for your quick reply.

How does one "create a socket" in that location?

Many thanks,
Steve

**Comment by stychos** [comment] 2020-08-11 11:21
@steviepitman this can be done by changing created socket path as mentioned in https://github.com/Sequel-Ace/Sequel-Ace/issues/113#issuecomment-667965997
```
[mysqld]
socket=/Users/YourUser/Library/Containers/com.sequel-ace.sequel-ace/Data/mysql.sock
```
