### ISSUE TITLE
Cannot insert new row in content view

### ISSUE THREAD

**Issue by paolomartini** [Sequel-Ace/Sequel-Ace#2088] opened 2024-09-09 18:36 UTC
- Sequel Ace Version (including build number): 4.1.1 Build 20071
- Sequel Ace Source (App Store/GitHub/Homebrew):
- macOS Version: 14.6.1
- Processor Type (Intel/Apple): 2.2 GHz 6-Core Intel Core i7
- MySQL Version: 8.0.35
- macOS Localization:

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

**Description**
Cannot insert new row in content view

**Steps To Reproduce**
1.

CREATE TABLE `data` (
  `column_1` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '',
  `column_2` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT 'defaultvalue',
  `id` smallint unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

2.

In content view adding new row with defaults results in the following error:

"MySQL said:

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ', defaultvalue, NULL)' at line 1"

 
**Expected Behaviour**

A new row is inserted successfully.

**Related Issues**

#2079

**Additional Context**

**Comment by Jason-Morcos** [comment] 2024-09-09 22:34
Duplicate of https://github.com/Sequel-Ace/Sequel-Ace/issues/2079, as noted
Already fixed in code and will be included in the next release

**Closed by Jason-Morcos** 2024-09-09 22:34 UTC
