### ISSUE TITLE
Show color of connection also when no tabs are shown

### ISSUE THREAD

**Issue by alexander-schranz** [Sequel-Ace/Sequel-Ace#1293] opened 2021-11-22 11:50 UTC
Currently when you have a connection with a color. The color is not shown when you have just one connection open. The color is only shown when tabs are shown so when having multiple connection open.

I'm using colors to indicate if the connection is a prod or a local database, to directly know if I'm editing prod databases to be more carefully. If I have just one connection open the color indicator is not there. I think it would be great if the color bottom line is also shown when there exist no tabs.

**Comment by Kaspik** [comment] 2021-11-22 11:52
You can enable the tab even for single tab - duplicate of https://github.com/Sequel-Ace/Sequel-Ace/issues/1046#issuecomment-817933963

**Closed by Kaspik** 2021-11-22 11:52 UTC

**Comment by alexander-schranz** [comment] 2021-11-22 12:01
Thx for the fast response. If possible I think it would be great if thats the default behaviour :).
