### ISSUE TITLE
Table information shows the number of rows and auto_increment value in MiB

### ISSUE THREAD

**Issue by wethecode** [Sequel-Ace/Sequel-Ace#550] opened 2020-11-25 16:49 UTC
- Sequel Ace Version: 2.3.1
- macOS Version: 10.14.6
- MySQL Version: 5.7.32

**Description**
The Table Information pane, the Table Info tab and the 'status bar' shows the number of rows and the next auto_increment value in MiB.

**Expected Behaviour**
They should be simple integers.

![Screenshot 2020-11-25 at 17 39 46](https://user-images.githubusercontent.com/1902780/100257633-6e51c180-2f46-11eb-9097-164599bd050c.png)
![Screenshot 2020-11-25 at 17 40 24](https://user-images.githubusercontent.com/1902780/100257637-6f82ee80-2f46-11eb-9ab4-b1af98aaa0a4.png)
![Screenshot 2020-11-25 at 17 47 05](https://user-images.githubusercontent.com/1902780/100257641-70b41b80-2f46-11eb-9d88-7baf01140d6b.png)

**Comment by Kaspik** [comment] 2020-11-25 16:53
Please, please - use search on github to save us some time. 😞 

Duplicate of https://github.com/Sequel-Ace/Sequel-Ace/issues/545, https://github.com/Sequel-Ace/Sequel-Ace/issues/504 and https://github.com/Sequel-Ace/Sequel-Ace/issues/541

**Closed by Kaspik** 2020-11-25 16:53 UTC

**Comment by Kaspik** [comment] 2020-11-26 10:05
Released 2.3.2 hotfix, available in the AppStore already.
