### ISSUE TITLE
Connection details form (sometimes) not centered

### ISSUE THREAD

**Issue by gboudreau** [Sequel-Ace/Sequel-Ace#116] opened 2020-06-26 12:06 UTC
- Sequel Ace Version: 2.1.0 beta 6
- macOS Version: 10.15
- MySQL Version: N/A

**Description**
Sometimes, if the window is large enough, and the favorites sidebar is wide enough, the content of the right view, where the connection details form is, will be right-aligned, instead of centered:
![image](https://user-images.githubusercontent.com/370329/85855176-d592fc00-b783-11ea-95b4-ea9006bb8ef2.png)

**Steps To Reproduce**
One can play with the separator, and see this:
![Screen Recording 2020-06-25 at 10 46 17 PM mov](https://user-images.githubusercontent.com/370329/85855060-995f9b80-b783-11ea-96f1-3cccad743e11.gif)

**Expected Behaviour**
Connection details form should always be centered.

**Comment by nook24** [comment] 2020-12-01 08:44
Same for me.
Sequel Ace Version: 2.3.2 Build 2121
![Bildschirmfoto 2020-12-01 um 09 41 51](https://user-images.githubusercontent.com/9019992/100716960-b72bcf00-33b9-11eb-9d5d-a2becede0dbd.png)

**Comment by Jason-Morcos** [comment] 2021-01-18 18:21
I believe this issue is fixed.

As we have received no reports of this issue in version 3+ of Sequel ace, I'm gonna close this issue. If you experience this issue again in the latest release of Sequel Ace, please create a new issue and reference this issue number in your description.

**Comment by nook24** [comment] 2021-01-18 20:26
Unfortunately this is still a thing. Sequel Ace Version: 3.1.0 Build 3013
![Bildschirmfoto 2021-01-18 um 21 21 48](https://user-images.githubusercontent.com/9019992/104960008-b08e0100-59d3-11eb-86c4-86628035f8eb.jpg)

It happens if i start Sequel Ace or open a new Tab

**Comment by nook24** [comment] 2021-01-27 11:37
@Jason-Morcos Since version 3.1.1 Build 3016 the issue seems to be fixed :)

**Comment by chellman** [comment] 2021-02-22 05:28
I am seeing this issue on macOS 10.15.7 with Sequel Ace build 3020, version 3.2.1 from the app store.  If I futz with the divider as shown above, centering is restored, but if I push the divider far enough to the right, the connection fieldset gets stuck to the right edge of the window again.  I can move the divider again to restore the centered layout.

**Comment by luis-** [comment] 2022-11-22 04:24
Wasn't able to reproduce on my mac running `macos-12.5.1` nor in my vm running `macos-10.15.7`.
In both cases I was running `Sequel Ace 4.0.1 Build 20039`

**Comment by Jason-Morcos** [comment] 2023-10-05 06:25
Should be fixed in the latest v4 series

**Closed by Jason-Morcos** 2023-10-05 06:25 UTC
Labels: Bug
