### ISSUE TITLE
How to move button area?

### ISSUE THREAD

**Issue by yadgen** [Sequel-Ace/Sequel-Ace#1066] opened 2021-04-28 07:44 UTC
Hi Jason:
How to move this area？It makes me very uncomfortable to use.
<img width="1919" alt="1" src="https://user-images.githubusercontent.com/1206012/116364731-15f55780-a837-11eb-835a-2f07267eca58.png">

Like this, This is my friend's UI.
![2](https://user-images.githubusercontent.com/1206012/116366164-95375b00-a838-11eb-94d3-e42d9bb06f2e.png)

@Jason-Morcos

**Comment by Kaspik** [comment] 2021-04-28 07:45
Duplicate of Duplicate of #562, #544, #534, #578, #595. #829 and #618. Big Sur related.

**Closed by Kaspik** 2021-04-28 07:45 UTC
