### ISSUE TITLE
Crash after SQL import

### ISSUE THREAD

**Issue by pstevemichel** [Sequel-Ace/Sequel-Ace#72] opened 2020-06-22 22:29 UTC
I need to import 3 databases today, from mysql dumps. Each time, when the import was finished, the app went away, and I got the bug report dialog. One time, it showed me an import finished notification, but the other two times id didn't In each of the cases, I got the Apple crash report dialog, and clicked OK. Hope you got those reports.

It does appear that everything was imported correctly.  FWIW, I've used this feature in Sequel Pro quite often.

**Comment by Kaspik** [comment] 2020-06-22 22:30
Seems like duplicate of https://github.com/Sequel-Ace/Sequel-Ace/issues/55.

**Closed** 2020-06-22 22:30 UTC
Labels: duplicate

**Comment by pstevemichel** [comment] 2020-06-22 22:32
It is, sorry.
