### ISSUE TITLE
Opens new window when I bring app to the front

### ISSUE THREAD

**Issue by pstevemichel** [Sequel-Ace/Sequel-Ace#915] opened 2021-02-26 17:40 UTC
- Sequel Ace Version (including build number): 3.2.1, build 3020
- macOS Version: 11.2.1
- Processor Type (Intel/Apple): Intel
- MySQL Version: various
- macOS Localization:

**Steps To Reproduce**
1. switch to a different app
2. switch back to Sequel Ace, by clicking on its icon in the doc: a new connection window appears.

**Comment by Kaspik** [comment] 2021-02-26 17:50
Use search please 😔

Duplicate of https://github.com/Sequel-Ace/Sequel-Ace/issues/892

**Closed** 2021-02-26 18:01 UTC
