### ISSUE TITLE
Blank space above tables and the filter search box

### ISSUE THREAD

**Issue by advicepyro** [Sequel-Ace/Sequel-Ace#418] opened 2020-10-20 22:19 UTC
- Sequel Ace Version: 2.2.1
- macOS Version: 10.15.7
- MySQL Version: 5.6.43

**Description**
Sometimes there is an expanding blank space above the list of tables and the filter search box. Refer to this screenshot for an example:

<img width="1549" alt="Screen Shot 2020-10-20 at 6 04 54 PM" src="https://user-images.githubusercontent.com/6377466/96649878-ebfb2f80-12ff-11eb-94b6-1a24407a2d04.png">

This issue's been here for a while, since I believe when new tabs were added to Sequel Pro.

**Steps To Reproduce**
1. Resize Sequel Ace to approximately half of the screen's size
2. Quit and restart Sequel Ace. Then reconnect to a DB
3. You'll notice there is some spacing above the tables list. Now zoom the app window
4. After zooming, the space expands.
5. Now that Sequel Ace is maximized, quit the app and restart it. Reconnect to your DB
6. At the full size (in my case: HiDPI, like 2560x1440) the gap is now smaller. If you downsize the window the gap disappears.

**Expected Behaviour**
There should never be any gap between the top toolbar and the pane containing the list of tables.

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes

**Comment by Jason-Morcos** [comment] 2020-10-21 06:47
Yup, I've noticed this occasionally too. Not sure how to fix it, but would gladly review a PR aimed at doing so!

**Comment by juanvillegas** [comment] 2020-11-02 13:48
![sequel-ace](https://user-images.githubusercontent.com/773149/97875250-67a2a680-1d1a-11eb-8b49-3b187574830e.gif)

Is this the same problem? It's minor, but pretty annoying though.

macOS catalina 10.15.3
sequel ace 2.2.2 build 2104

**Comment by Kaspik** [comment] 2020-11-02 21:29
We have a lot of changes in one PR, so let's see 2.3.0.

**Comment by Kaspik** [comment] 2020-11-17 21:46
Is this still an issue on latest version?

**Comment by Jason-Morcos** [comment] 2020-11-18 00:17
> Is this still an issue on latest version?

Yeah, it is. For me at least. Hoping that PR I made last night fixes it

**Comment by Jason-Morcos** [comment] 2020-11-18 00:18
> Is this still an issue on latest version?

The root issue described in the issue is still an issue for me in the latest version. Hoping my PR from last night fixes it.
But I don't have the disappearing table list issue described above.

**Comment by advicepyro** [comment] 2020-11-24 00:21
> > Is this still an issue on latest version?
> 
> The root issue described in the issue is still an issue for me in the latest version. Hoping my PR from last night fixes it.
> But I don't have the disappearing table list issue described above.

Was it this PR? #506 
If so, do you know if that fix will make it to the 2.x builds?

If not that's fine, I can wait until 3.x makes it to release.

**Comment by Jason-Morcos** [comment] 2020-11-24 02:58
> > > Is this still an issue on latest version?
> 
> > 
> 
> > The root issue described in the issue is still an issue for me in the latest version. Hoping my PR from last night fixes it.
> 
> > But I don't have the disappearing table list issue described above.
> 
> 
> 
> Was it this PR? #506 
> 
> If so, do you know if that fix will make it to the 2.x builds?
> 
> 
> 
> If not that's fine, I can wait until 3.x makes it to release.

Yup! It'll be a 3.0 and on fix (won't be in 2.0)!
If the issue isn't fixed by that PR though we'll definitely keep trying to figure it out!

**Comment by Kaspik** [comment] 2020-12-04 18:37
I believe this is now resolved for 3.0.0

**Closed by Kaspik** 2020-12-04 18:37 UTC
Labels: Bug, Help wanted, PR Welcome
