### ISSUE TITLE
After time of inactivity, reload would try to load data from stored default database, instead of the selected database of that tab

### ISSUE THREAD

**Issue by alexanderkraemer** [Sequel-Ace/Sequel-Ace#2086] opened 2024-09-05 06:20 UTC
- Sequel Ace Version (including build number): Version 4.0.17 Build 20067
- Sequel Ace Source (App Store/GitHub/Homebrew): Homebrew
- macOS Version: 14.6.1 (23G93)
- Processor Type (Intel/Apple): Apple Silicon
- MySQL Version: 8.0.30
- macOS Localization: en-us

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?** Yes

**Description**

**Steps To Reproduce**
1. Open a window and connect to a database (db1) stored in your favourites. (database name needs to be stored in the favourites as well)
2. switch the database to another one. (db2)
3. load a table that is not existing on your in favourite stored database (db1) 
4. wait some time (hours)
5. reload the current open window (which still shows the table of db2) so that the table content gets refetched.
6. You'll get an error, that the table you are trying to fetch is not existing on db1.

**Expected Behaviour**
I'd expect the reload to happen in db2 and not in db1 as db2 was the one that was open.

**Related Issues**

**Additional Context**
This problem has been out there since years. :)

**Comment by Jason-Morcos** [comment] 2024-09-05 06:28
I think this is a duplicate of https://github.com/Sequel-Ace/Sequel-Ace/issues/1806 or https://github.com/Sequel-Ace/Sequel-Ace/issues/1594

PRs definitely welcome if folks have ideas on how to fix the bug!

**Closed by Jason-Morcos** 2024-09-05 06:28 UTC
