### ISSUE TITLE
UI becomes slow after program is open for a while

### ISSUE THREAD

**Issue by anubhav217** [Sequel-Ace/Sequel-Ace#1205] opened 2021-08-21 18:47 UTC
- Sequel Ace Version (including build number):
- Sequel Ace Source (App Store/GitHub/Homebrew):
- macOS Version:
- Processor Type (Intel/Apple):
- MySQL Version:
- macOS Localization:

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

**Description**

**Steps To Reproduce**
1.
2.

**Expected Behaviour**

**Related Issues**

**Additional Context**

**Comment by Jason-Morcos** [comment] 2021-08-22 01:43
Duplicate of https://github.com/Sequel-Ace/Sequel-Ace/issues/1197

**Closed by Jason-Morcos** 2021-08-22 01:43 UTC
