### ISSUE TITLE
...WHERE field IN (')

### ISSUE THREAD

**Issue by gluck-59** [Sequel-Ace/Sequel-Ace#1908] opened 2023-11-01 00:39 UTC
Sequel Ace Version (including build number): Version 4.0.11 Biuld 20058
Sequel Ace Source: App Store:
macOS Version: 10.14.6 (18G103)
Processor Type (Intel/Apple): Intel

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes

**Description**
An unexpected number of lines were deleted

**Steps To Reproduce**
1. Open any table, select any row(s)
2. Click "delete row" 

**Expected Behaviour**
Deleting the row

**Related Issues**
No

**Additional Context**
When I delete a row/rows with mouse or keyboard I see error  "unexpected number of lines deleted".
In the console I see "DELETE FROM `tbl_migration` WHERE `version` IN (');" This IN (') seems wrong... 
When I remove rows manually everything works correctly

**Comment by gluck-59** [comment] 2023-11-01 01:12
Additional Information
When I try to edit a field, I see in the console: UPDATE `b_popups` SET `customer_filename` = ' WHERE `id` = ';
  , with the corresponding result: all values of the customer_filename field in this table were rewritten to "WHERE `id` = "
Yes, I reinstalled Sequel Ace several times with different versions
Yes, I rebooted several times
Yes, I plugged in the mac to power line

**Comment by Jason-Morcos** [comment] 2023-11-01 03:22
Do you have the filters open by chance? Could this be related to those somehow?

**Comment by gluck-59** [comment] 2023-11-01 18:54
No

**Comment by gluck-59** [comment] 2023-11-01 19:07
This is a screencast of glitch: https://youtu.be/a9msWST0pjY

**Comment by Jason-Morcos** [comment] 2023-11-02 02:10
What version of MySQL are you using?

**Comment by gluck-59** [comment] 2023-11-02 02:13
5.7.39
I use it ≈4 years with  Sequel Pro and Sequel Ace

**Comment by Jason-Morcos** [comment] 2023-11-02 02:16
I'm not able to reproduce this issue at all with the latest macOS - I can add entires just fine. Can you share the create statement for this particular table you're having issues with?
@Sequel-Ace/all Anyone else got any ideas here?

**Comment by gluck-59** [comment] 2023-11-02 02:20
I have a very old computer and it runs 10.14 Mojave
Anyway, I've been working with him for about 2 years and have never seen anything like this

**Comment by Jason-Morcos** [comment] 2023-11-02 02:22
Just to confirm @gluck-59  - you did try older releases of Sequel Ace though and didn't see this issue, correct? That's what makes it really seem like it might be somehow related to your specific database rather than something broken in a recent release of Sequel Ace

**Comment by Jason-Morcos** [comment] 2023-11-02 02:25
Running that create statement on MySQL 5.7, and then inserting records I have zero issues at all
<img width="469" alt="Screenshot 2023-11-01 at 19 22 28" src="https://github.com/Sequel-Ace/Sequel-Ace/assets/10710367/43ba3c67-4f87-476b-a1f2-0033d9f9febb">
<img width="1439" alt="Screenshot 2023-11-01 at 19 24 03" src="https://github.com/Sequel-Ace/Sequel-Ace/assets/10710367/99a2d6b2-f094-453e-939e-4bc5286c0f9f">

**Comment by Jason-Morcos** [comment] 2023-11-02 02:26
If you change your Mac to the US/English localization, do you still see this issue? Is there a chance this is literally caused by something funky with localization?

**Comment by gluck-59** [comment] 2023-11-02 02:40
> Just to confirm @gluck-59 - you did try older releases of Sequel Ace though and didn't see this issue, correct? That's what makes it really seem like it might be somehow related to your specific database rather than something broken in a recent release of Sequel Ace

No
I tried for versions 4.0.11, 4.0.10 and 4.0.6 from https://github.com/Sequel-Ace/Sequel-Ace/releases and glitch is saves

I have several databases created at different times with different tools and the behavior is identical in all of them.

**Comment by gluck-59** [comment] 2023-11-02 02:45
> If you change your Mac to the US/English localization, do you still see this issue? Is there a chance this is literally caused by something funky with localization?

Unfortunately no :(

![Uploading _screenshot- 2023-11-02 at 07.44.15.png…]()

**Comment by robinkunde** [comment] 2023-11-02 04:01
@gluck-59 Would you mind providing the following:

1. A screenshot of the "table info" screen
2. Run these query on the database in question and post the output here: 
  `SHOW VARIABLES LIKE 'character_set%'`
  `SHOW VARIABLES LIKE 'collation%'`
  `SELECT @@character_set_database, @@collation_database`

@Jason-Morcos This looks like an encoding issue of some sort. I did find some suspect code [here](https://github.com/Sequel-Ace/Sequel-Ace/blob/23b0a38a7c7639aa3e444eb4f34b2cd12ef7b568/Frameworks/SPMySQLFramework/Source/SPMySQLConnection%20Categories/Querying%20%26%20Preparation.m#L102). If we can't reproduce the issue with the above info, we might have to try a special build with additional logging.

**Comment by gluck-59** [comment] 2023-11-02 07:58
<img width="561" alt="_screenshot- 2023-11-02 at 12 54 19" src="https://github.com/Sequel-Ace/Sequel-Ace/assets/86118746/69bf1c78-281f-46aa-92a1-e8fdd75bd899">

SHOW VARIABLES LIKE 'character_set%'
<img width="477" alt="_screenshot- 2023-11-02 at 12 56 25" src="https://github.com/Sequel-Ace/Sequel-Ace/assets/86118746/55538d9d-b88c-4880-a8d4-a1564907cf69">

SHOW VARIABLES LIKE 'collation%'
<img width="303" alt="_screenshot- 2023-11-02 at 12 57 23" src="https://github.com/Sequel-Ace/Sequel-Ace/assets/86118746/45abf1ff-b4cb-496e-a4e4-56f95381b96e">

SELECT @@character_set_database, @@collation_database;
<img width="375" alt="_screenshot- 2023-11-02 at 12 57 47" src="https://github.com/Sequel-Ace/Sequel-Ace/assets/86118746/97379344-e037-453a-b05d-544aff18ffbc">

**Comment by robinkunde** [comment] 2023-11-03 13:57
@gluck-59 That's not what I was expecting at all. Would you be willing to try out a custom build?

**Comment by samuelbradshaw** [comment] 2023-11-03 14:02
In the screencast it shows that you have the ID filter visible. Does it make a difference if you remove or uncheck that filter?

**Comment by gluck-59** [comment] 2023-11-03 14:18
No

**Comment by gluck-59** [comment] 2023-11-03 14:19
> @gluck-59Это совсем не то, чего я ожидал. Хотели бы вы попробовать кастомную сборку?

I don't even know...
but I have no other way? :)

**Comment by robinkunde** [comment] 2023-11-03 14:53
@Jason-Morcos How do I create a debug beta build I can send to @gluck-59 ?

**Comment by Jason-Morcos** [comment] 2023-11-03 14:54
> @Jason-Morcos How do I create a debug beta build I can send to @gluck-59 ?

If you want to open a PR with the changes you'd like in the temp build, I can build that and sign it after work today!

**Comment by robinkunde** [comment] 2023-11-03 15:00
@Jason-Morcos Cool, I won't be able to get to it today but I'll let you know when it's ready.

**Comment by gluck-59** [comment] 2023-11-03 15:34
In my language the words "friday" and "drink" have a similar sound
Beer everyone! :)

**Comment by robinkunde** [comment] 2023-11-06 05:46
@Jason-Morcos Does this work? https://github.com/Sequel-Ace/Sequel-Ace/compare/rk/debugLogging?expand=1

**Comment by Jason-Morcos** [comment] 2023-11-07 07:40
[Sequel Ace - Debug Logging.zip](https://github.com/Sequel-Ace/Sequel-Ace/files/13277008/Sequel.Ace.-.Debug.Logging.zip)

Perfect! Built a debug build based on that code. A couple notes
- Build mode was debug mode (so that should maximize the logging)
- Build number and version number match the upcoming 4.0.12 release, but this is 4.0.12 with the extra changes @robinkunde made
- I built this with the latest Xcode and macOS, because I had to build locally, which means this build _may_ have issues with older versions of macOS (we build the real releases in the cloud because of a bug with the latest Xcode and macOS). I know this is an older version of macOS that @gluck-59 is on. If this build doesn't work, unfortunately I don't have a way of building custom debug builds in the cloud

**Comment by gluck-59** [comment] 2023-11-07 07:44
> [Sequel Ace - Debug Logging.zip](https://github.com/Sequel-Ace/Sequel-Ace/files/13277008/Sequel.Ace.-.Debug.Logging.zip)

Hi
It crash when connecting to any database... :(

**Comment by Jason-Morcos** [comment] 2023-11-07 07:45
Yep, so that's the old macOS bug. Unfortunately I can't build debug builds for your version of macOS because of an Apple bug in Xcode.

**Comment by gluck-59** [comment] 2023-11-07 07:47
Can you tell me where can i download version earlier than 4?

**Comment by Jason-Morcos** [comment] 2023-11-07 07:48
All of the releases are stored on the GitHub repo's releases page. Downloads are on there for every version.

Honestly, you're running on a five year old OS. I highly encourage you to upgrade to a newer macOS version which likely fixes problems like these.

**Comment by gluck-59** [comment] 2023-11-07 07:51
I have been working with this OS version for more than 2 years.
When I can buy a new iMac, I will definitely install the latest version of the OS, thanks.

**Comment by robinkunde** [comment] 2023-11-07 12:42
@Jason-Morcos Could you try the lastest Xcode beta? The release notes sound like it fixed the issue https://developer.apple.com/documentation/xcode-release-notes/xcode-15_1-release-notes

**Comment by gluck-59** [comment] 2023-11-07 13:16
I took a temporary workstation with Mac OS Monerrey, installed the latest version of Sequel Ace from the Appstore and am seeing the same behavior.

I am sorry, but my “very old, unusable, 5 year old, etc. macos” has nothing to do with it.
Sorry, but it's time to return to Workbench.

https://youtu.be/ZwG835dPQVI

**Comment by gluck-59** [comment] 2023-11-07 16:32
So, I fixed this

Today I went through several clients, took another Maс with Monterrey, tried several more clients on the one (yep, I hate the Workbench), but the glitch was remained
everywhere except phpmyadmin

And as soon as I killed the sql_mode="NO_BACKSLASH_ESCAPES,NO_ENGINE_SUBSTITUTION" line from my.cnf, everything immediately went back to normal

Such a poltegeist...
and for some reason phpmyadmin didn't care...

**Comment by robinkunde** [comment] 2023-11-07 18:59
Wow, that's so interesting. I'll have to see if I can reproduce it on my end with that config.

**Comment by gluck-59** [comment] 2023-11-07 19:33
but why PMA doesn't see this problem?

**Comment by robinkunde** [comment] 2023-11-07 19:47
This is a bug in SequelAce. It should be fixed in the next release.

**Comment by gluck-59** [comment] 2023-11-07 19:50
Merci
I will wait for this update because it is painful to set the mode manually every session

**Closed** 2023-11-09 08:06 UTC
Labels: Bug, Workaround available
