### ISSUE TITLE
v3.0.0 (3005) Crashes opening About window on macOS 10.14.6

### ISSUE THREAD

**Issue by julian-tr** [Sequel-Ace/Sequel-Ace#627] opened 2020-12-15 11:30 UTC
- Sequel Ace Version: 3.0.0 (3005)
- macOS Version: 10.14.6
- Processor Type (Intel/Apple): Intel
- MySQL Version:

**Description**
Crashes instantly on selecting **About Sequel Ace** from the **Sequel Ace** menu

**Steps To Reproduce**
1. Open Sequel Ace
2. Select **About Sequel Ace** from **Sequel Ace** menu
3. Crash

**Expected Behaviour**
No crash

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
This is the latest release (3005)

**Additional Context**
[crash.txt](https://github.com/Sequel-Ace/Sequel-Ace/files/5695473/crash.txt)

**Comment by Kaspik** [comment] 2020-12-15 11:38
Duplicate of https://github.com/Sequel-Ace/Sequel-Ace/issues/625

**Closed by Kaspik** 2020-12-15 11:38 UTC
