### ISSUE TITLE
"No database selected error" when database is actually already selected

### ISSUE THREAD

**Issue by webtoolbox** [Sequel-Ace/Sequel-Ace#349] opened 2020-09-17 19:52 UTC
- Sequel Ace Version: 2.1.7
- macOS Version: 10.5.6
- MySQL Version: 5

**Description**
When selecting a table after a connection has been idle for a long period of time, a "No database selected error" appears even though a database is already selected. You can click ok and the table you attempted to select isn't actually selected. Then if you attempt to select a table again, the same error appears and this time the application crashes/shuts down and an error report to Apple dialog appears.

<img width="1206" alt="Screen Shot 2020-09-17 at 3 47 54 PM" src="https://user-images.githubusercontent.com/1911826/93521157-a19c2280-f8fd-11ea-89cf-5e85fffbfe91.png">

**Steps To Reproduce**
1. Leave the connection idle
2. Select a table

**Expected Behaviour**
The table should properly be selected and no error should appear.

**Comment by webtoolbox** [comment] 2020-09-17 19:54
Thank you for all your work on Sequel Ace @Jason-Morcos

**Comment by Jason-Morcos** [comment] 2020-09-17 21:47
Funky! Possibly related to #345 or #282

**Comment by webtoolbox** [comment] 2020-09-17 22:04
I think I do always have multiple tabs open when it happens, so #282 could be related.

**Comment by BenVim** [comment] 2020-12-03 06:57
<img width="287" alt="WechatIMG77" src="https://user-images.githubusercontent.com/936635/100974765-d07a7a00-3577-11eb-8a02-4118d33060d7.png">
1.Leave the connection idle
2. Select a table
I can't close this popover

**Comment by repsher** [comment] 2021-01-18 17:43
Not sure if this is related or not, but twice now in the past few weeks I've run into a similar issue but more concerning because it runs the query in a different database than the one selected. I haven't been able to consistently reproduce it so didn't want to put in a new ticket. Here are the details:
I'm running Version 2.3.3, Build 2121, Mac OS 10.15.7 and MySql 5.6. I usually have multiple tabs open and toggle between a QA and PROD database throughout the day. I have left the database selected to QA and after the connection has been idle overnight I have run queries that execute in the PROD database even though the QA database is selected. If I select the PROD DB from the drop down, then QA and run it again it runs in the correct database (aka QA).
Wish I could reproduce this to provide more details but wanted to mention it since it might be related.

**Comment by Jason-Morcos** [comment] 2021-01-18 18:18
We tend to not offer support for older versions of Ace at this time as we move fixed so many bugs in the latest versions. I'm actually gonna go ahead and close this issue as it has had no reports from version 3+. I encourage you to install 3.1.0 and let us know if you still encounter the issue!

**Closed by Jason-Morcos** 2021-01-18 18:18 UTC
Labels: Bug, Help wanted

**Comment by nicholaswright** [comment] 2022-07-19 13:00
> We tend to not offer support for older versions of Ace at this time as we move fixed so many bugs in the latest versions. I'm actually gonna go ahead and close this issue as it has had no reports from version 3+. I encourage you to install 3.1.0 and let us know if you still encounter the issue!

I'm using v3.5.2 and am getting this error. If I export a database, create a new database and attempt to import the export into it I get a "No database selected" error.

**Comment by Jason-Morcos** [comment] 2022-08-16 22:56
@nicholaswright Be sure that your import isn't dropping and recreating the database as part of its SQL. Because if you're dropping the database you just created and have selected, that could definitely be causing this strange behavior. If you're still having issues, please open a new issue - old issues aren't monitored.

**Comment by BilalArainRashid** [comment] 2022-10-25 06:20
my error is not please help me i have design login sign up page mysql and php
