### ISSUE TITLE
Tab content and titles disrupted

### ISSUE THREAD

**Issue by martinstoehr** [Sequel-Ace/Sequel-Ace#1056] opened 2021-04-19 09:07 UTC
- Sequel Ace Version (including build number): 3.3.1 build 3028
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 11.2.3
- Processor Type (Intel/Apple): Apple
- MySQL Version: various
- macOS Localization: German

**Description**
Tab titles and even content is disrupted after some time of usage. See the following image (green boxes are ok, red not):
![Bug Sequel Ace](https://user-images.githubusercontent.com/2726108/115210577-066f6380-a0ff-11eb-85ec-47a1866a828c.jpg)

**Steps To Reproduce**
1. Open several tab from different hosts (in my case all over ssh tunnel)
2. Do some queries, switch between tabs, close a tab, reopen it.

**Comment by Kaspik** [comment] 2021-04-19 09:13
Out of curiosity - how did you get this to work on MySQL 5.5.5 if we support MySQL 5.6+? 🤔

**Comment by martinstoehr** [comment] 2021-04-19 09:35
It's MariaDB 10.3, the "MySQL 5.5.5" is a fake string delivered by MariaDB.

**Comment by Kaspik** [comment] 2021-04-19 09:56
I wonder if it's related to https://github.com/Sequel-Ace/Sequel-Ace/issues/429 and just shows properly the titles now (which means they are wrong but they actually inform they are wrong) or to https://github.com/Sequel-Ace/Sequel-Ace/issues/282...

**Comment by martinstoehr** [comment] 2021-04-19 10:41
I think it's not related to #429 or #282, because I don't use any local connection, it's all ssh connections to completely different remote servers.

**Comment by Kaspik** [comment] 2021-04-19 10:44
#429 is not only `local vs. remote`, but common issue with SSH using wrong connection afaik, that's why I mentioned that.

**Comment by hijdena** [comment] 2021-04-22 07:22
Same issue as @martinstoehr. I use a combination of direct access and SSH tunnel access. After a while the tab names and the tab colors are not presenting the actual status. "After a while" seems to be after a Mac suspend/sleep action when connections need to be re-established (not sure though).

**Comment by martinstoehr** [comment] 2021-04-22 08:30
good point @hijdena , it happens when the app goes in background and comes to front again. Just tested it out. You can reproduce it in the following way:
- open Tabs with different connections (ssh,>=3 tabs)
- open some tables in each tab
- put app to background or put another app to front (e.g. Safari and browse some pages...)
- get SequelAce back to front, now tab titles are wrong

btw, in Menu Window titles are corrent!

**Comment by EricSocs** [comment] 2021-05-26 11:20
Version 3.3.2. 

It appears immediately after a database connection failure.

- Opened a new tab with a local connection.
- One of the remote connections open in another tab failed. Only option was to agree to close tab.
- All tabs to the right of the one with lost connection are then reassigned wrongly, with the reported discrepancy between dropdown and tab name. The tabs to the left are fine.

**Comment by dhcmega** [comment] 2021-06-08 16:36
Hi, in case it's useful, in my case, reconnect only works for non SSH connections.
For over ssh connections, when the connection breaks, it has never reconnected (that I can recall).

**Comment by Iv4nS** [comment] 2021-07-14 02:47
This type of bugs are the ones that I find extremely dangerous. I can end up doing a change in production thinking I'm working on my local dev. I wish I could fix it but this programming language is beyond my knowledge. It has been present for a while now, yes I can always roll back to a previous version I guess or perhaps reconsider my client altogether.

**Comment by domstubbs** [comment] 2021-07-15 10:34
Yeah, this has given me a few scary moments where Sequel has been telling me I’m looking at a local tab when it’s actually a production tab, and vice versa. Is there a known safe version that we can roll back to? I’d happily forego any other feature updates or bug fixes if it meant I could trust what I was looking at again.

I don’t think a connection failure/drop is necessary to trigger the bug, but it does seem more prevalent when the app has been active for some time. When I intentionally try to replicate it by opening lots of tabs in succession it’s not happening.

**Comment by Kaspik** [comment] 2021-07-15 10:36
Anything before 3.3.0 that had windows rewrite could be okay. I wasn't able to repro thus it's hard to fix - seems to be happening only with SSH connections.

**Comment by domstubbs** [comment] 2021-07-15 10:42
Thanks. I’ve installed 3.2.3 and will see if that seems more reliable. If I can manage a week or so without it happening with that version then I’d be 99% confident that the issue was introduced after that.

I am using SSH for all remote connections, so that would fit.

**Comment by martinstoehr** [comment] 2021-07-15 11:01
> Anything before 3.3.0 that had windows rewrite could be okay. I wasn't able to repro thus it's hard to fix - seems to be happening only with SSH connections.

Yes, it's happening only with SSH connections. 
@Kaspik : If i can support you in any way, feel free to ask. If you need some remote databases to test with, let me know.

**Comment by Kaspik** [comment] 2021-07-15 11:04
Yeah I have no SSH connections so whatever you can prepare for me and can repro on, send it my way!

**Comment by martinstoehr** [comment] 2021-07-15 11:58
@Kaspik : i have set up three db servers with ssh for you. I need your ssh public key for auth. How can we savely exchange it?

**Comment by Kaspik** [comment] 2021-07-15 12:06
Can you join our Slack please? Let's chat there.

**Comment by martinstoehr** [comment] 2021-07-15 12:25
> Can you join our Slack please? Let's chat there.

of course, how do i do that?

**Comment by Kaspik** [comment] 2021-07-15 14:27
> > Can you join our Slack please? Let's chat there.
> 
> of course, how do i do that?

https://github.com/Sequel-Ace/Sequel-Ace/blob/main/readme.md#contributing - added to main readme for future reference as well.

**Comment by aaronsevedge** [comment] 2021-07-15 16:48
I'm new to the community but I've been running into this bug for a while. I can't add any input about SSH-only nor after machine sleep/wake, but I do have a hard repro during my normal usage: clicking the "add tab" button in the UI when I've got multiple tabs open and my current tab is anything but the furthest to the right.

E.g if I set up these tabs:

    Title A | Title B | Title C | Title D 
    Table A | Table B | Table C | Table D

select Tab B
open new tab with "+" button
now my tabs look like this

    Title A | Title B | Title C | Title D | Title E
    Table A | Table B | Table E | Table C | Table D

Using the CMD+T keyboard shortcut instead of the button opens that new Tab E without disrupting anything, though.

**Comment by Jason-Morcos** [comment] 2021-07-21 01:24
> I'm new to the community but I've been running into this bug for a while. I can't add any input about SSH-only nor after machine sleep/wake, but I do have a hard repro during my normal usage: clicking the "add tab" button in the UI when I've got multiple tabs open and my current tab is anything but the furthest to the right.
> 
> E.g if I set up these tabs:
> 
> ```
> Title A | Title B | Title C | Title D 
> Table A | Table B | Table C | Table D
> ```
> 
> select Tab B
> open new tab with "+" button
> now my tabs look like this
> 
> ```
> Title A | Title B | Title C | Title D | Title E
> Table A | Table B | Table E | Table C | Table D
> ```
> 
> Using the CMD+T keyboard shortcut instead of the button opens that new Tab E without disrupting anything, though.

This is a great explanation about how to repoduce the bug, @aaronsevedge. Thank you.
From this description I was able to reproduce the bug _without_ any of the connections involved being SSH

**Comment by domstubbs** [comment] 2021-07-22 15:27
FWIW, having run 3.2.3 for a week I haven’t had any issues. I also can't reproduce using the steps above, so it is probably safe to assume that the bug was introduced in 3.3+ as suspected.

**Comment by Kaspik** [comment] 2021-07-22 15:29
Yeah, we already reproed the issue, just no luck with the fix.

FIY: It happens when you click the "+" next to tabs, it DOESN'T happen when you use CMD+T shortcut. Both call the same function tho, so it has to be something with system doing something behind our eyes with the system "+" icon.

**Comment by domstubbs** [comment] 2021-07-22 15:32
Yep I spotted the posts above, I was just confirming that the older release seems unaffected in case anyone watching this post wanted a stopgap fix.

**Comment by Muukuro** [comment] 2021-07-23 08:32
I'm not certain is this the exact same behavior that @aaronsevedge described, but I can consistently reproduce this in a simpler way, regardless of whether I use CMD+T, the "+" button or File > New Connection Tab, and regardless of whether I use SSH (or even connect at all):

1. Open a new window
2. Connect to a server (optional, but this makes the tab title recognizable)
3. Open a new tab through any of the methods mentioned (and connect to a server to make the title recognizable)
4. **Select the first tab** <-- this is the key for me
5. Open a new tab
6. The middle (first opened) tab is highlighted, but the title, "Choose Database..." select field, etc all belong the third connection tab

**Comment by Kaspik** [comment] 2021-07-29 15:42
I'm really sorry it took 3 months to fix this - but here we go hopefully.

**Closed** 2021-07-29 15:57 UTC
Labels: Bug, Highest Priority

**Comment by Jason-Morcos** [comment] 2021-07-30 04:10
Please try the new beta!
https://github.com/Sequel-Ace/Sequel-Ace/releases/tag/beta%2F3.4.0-3037

**Comment by EricSocs** [comment] 2022-02-16 09:41
FYI Still had this yesterday with 3.4.5. Only noticed the wrong database was updated this morning.
