### ISSUE TITLE
 auto-suggest fields

### ISSUE THREAD

**Issue by JaminYe** [Sequel-Ace/Sequel-Ace#1761] opened 2023-06-09 02:09 UTC
- Sequel Ace Version (including build number):4.0.5 (20046) 
- Sequel Ace Source (App Store/GitHub/Homebrew):  GitHub
- macOS Version: 12.6.6
- Processor Type (Intel/Apple):  Intel
- MySQL Version: 5.7.40
- macOS Localization:

**Description**
4.0.5 (20046) version Cannot auto-suggest fields,but I use the 3.2.3 it’s work,Why does this feature not exist in the subsequent versions?
<img width="848" alt="image" src="https://github.com/Sequel-Ace/Sequel-Ace/assets/45601795/1927bf30-e5b8-4419-a6c3-3953cb992aeb">

**Comment by Jason-Morcos** [comment] 2023-06-15 23:18
Closing - can't reproduce and can't understand the issue from this limited description

**Closed by Jason-Morcos** 2023-06-15 23:18 UTC
