### ISSUE TITLE
Weird hidden invisible windows in mission control

### ISSUE THREAD

**Issue by jackbentley** [Sequel-Ace/Sequel-Ace#1173] opened 2021-07-19 14:57 UTC
- Sequel Ace Version (including build number): Version 3.3.3 Build 3034
- Sequel Ace Source (App Store/GitHub/Homebrew): GitHub
- macOS Version: 11.4
- Processor Type (Intel/Apple): Intel
- MySQL Version: 5.6.48
- macOS Localization: English (GB)

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

**Description**
There are 3 hidden invisible windows visible in Mission Control / show all windows view. This causes mission control to look weird and also doesn't re-focus the actual window when clicking the app icon in the Dock.

**Steps To Reproduce**
1. Open Sequel Aces and connect to the database
2. Minimise the window
3. Right click the app icon in the dock > show all windows...
4. Hover in whitespace and find the hidden windows

**Expected Behaviour**

No hidden windows in Mission Control / Show all windows. Clicking the app icon in the dock should un-minimize the actual Sequel Ace window (you use Apple Music as an example of this expected behaviour).

**Related Issues**

**Additional Context**

<img width="1792" alt="Screenshot 2021-07-19 at 15 43 45" src="https://user-images.githubusercontent.com/9383439/126180807-511e619e-1bf8-4272-8ef9-44bafc95c959.png">
<img width="1792" alt="Screenshot 2021-07-19 at 15 43 46" src="https://user-images.githubusercontent.com/9383439/126180830-e0c52dcf-e7a0-4790-96c9-8cdd119622cf.png">
<img width="1792" alt="Screenshot 2021-07-19 at 15 43 47" src="https://user-images.githubusercontent.com/9383439/126180843-286bb644-4d22-4d76-80da-d20435721890.png">

**Comment by mfehr94** [comment] 2021-07-19 15:48
I cannot reproduce this kind of behaviour.

**Comment by studious** [comment] 2021-08-01 12:50
I've also spotted an issue like this. When I try and export as CSV the main window disappears to the background. When I bring it to the foreground it is greyed out as if waiting for a permissions window. I was trying to find the window to accept access to my folders and that is when I spotted one hidden window.
![Screen Shot 2021-08-01 at 10 44 07 pm](https://user-images.githubusercontent.com/306810/127771471-b02a44e7-081a-47ba-8244-d08c8c5649fb.png)

**Comment by Jason-Morcos** [comment] 2021-08-04 06:31
Interesting. I tried the steps you described, @studious, but was still unable to reproduce. I did see the background app grayed out when the modal window popped up (which is expected) but after exporting the app wasn't grayed out and I didn't have a tiny extra hidden window in mission control/show all windows.

**Comment by studious** [comment] 2021-08-04 10:45
I can't complete exporting. The main app greys out and that tiny window appears in mission control. I'm guessing something in that tiny invisible window is supposed to let me pick something. I'm not sure. I have the bookmarks necessary but on trying to export the folder section is not filled in either.

**Comment by Jason-Morcos** [comment] 2021-08-08 13:32
> I can't complete exporting. The main app greys out and that tiny window appears in mission control. I'm guessing something in that tiny invisible window is supposed to let me pick something. I'm not sure. I have the bookmarks necessary but on trying to export the folder section is not filled in either.

If you grant full disk access to sequel Ace in system prefs and quit and reopen, are you able to export then?

Are you using Big Sur as well?

**Comment by ianpea** [comment] 2021-08-12 10:43
#1194, I also opened up an issue for this, step to reproduce

1. Fully expand window to fill screen/maximize (NOT FULLSCREEN)
2. Minimize using top left button
3. Open the app again by clicking dock
4. Window does not appear but context is correct (u can invoke App Exposé here to return to the window)

**Comment by Kaspik** [comment] 2021-08-15 10:36
I'm not able to reproduce this in 99% cases, when I did, There was nothing obvious when debugging it - we just told the system in `- (BOOL)applicationShouldHandleReopen:(NSApplication *)sender hasVisibleWindows:(BOOL)flag` - `return YES` which should be then handled by the system... But again - in most of the cases, I'm not even able to repro this.

**Comment by Kaspik** [comment] 2022-08-09 21:31
This could be fixed in 4.0.0 Beta once we ship it this week.

**Comment by samuelbradshaw** [comment] 2023-01-02 21:20
I'm still seeing this in 4.0.4:
<img width="1000" alt="Screenshot 2023-01-02 at 2 19 23 PM" src="https://user-images.githubusercontent.com/7323052/210278719-14014186-93df-4c10-9a5f-bbdb95efcdea.png">

**Comment by AlexanderOMara** [comment] 2023-07-27 00:13
Evidently it's the "Running query..." overlay you see when a query takes a little bit. Easiest way to reproduce it:

1.  Connect to a database.
2.  In the Query panel, run: `SELECT SLEEP(3)`
3.  When the query completes, observe the new hidden window in Mission Control.
4.  In the Query panel, run: `SELECT SLEEP(10)`
5.  While it is still running, observe the hidden window has disappeared from Mission Control.
6.  When the query completes, observe the hidden window is back in Mission Control.

Interestingly, if you minimize the main window, you can see the hidden window is the loading overlay in the preview of the desktops at the top.

<img width="166" alt="overlay" src="https://github.com/Sequel-Ace/Sequel-Ace/assets/1740229/7c36ffb8-85eb-484a-9f61-d73e33087b8e">

**Comment by Jason-Morcos** [comment] 2023-10-05 06:28
I think this should be fixed in 4.0.10, but let us know if you see this in v4.0.10 or newer.

**Closed by Jason-Morcos** 2023-10-05 06:28 UTC
Labels: Bug, PR Welcome, Cannot Reproduce
